### ISSUE TITLE
TestComposeWindow. java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1019]
Compose 1.0.0-alpha1

```
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.layout.size
import androidx.compose.material.Text
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.TestComposeWindow
import androidx.compose.ui.unit.dp

fun main() {
    Thread {
        println("started1")
        run {
            while (true) {
                TestComposeWindow(500, 500).setContent {
                    Canvas(Modifier.size(100.dp)) {
                        drawCircle(Color.Red)
                    }
                    Text("Hello, World!")
                }
            }
        }
    }.start()

    Thread {
        run {
            while (true) {
                TestComposeWindow(500, 500).setContent {
                    Canvas(Modifier.size(100.dp)) {
                        drawCircle(Color.Red)
                    }
                }
            }
        }
    }.start()
    Thread.sleep(10000000)
}
```

Crash:
```
Exception in thread "Thread-1" java.lang.IllegalStateException: Reading a state that was created after the snapshot was taken or in a snapshot that has not yet been applied
	at androidx.compose.runtime.snapshots.SnapshotKt.readError(Snapshot.kt:1518)
	at androidx.compose.runtime.snapshots.SnapshotKt.readable(Snapshot.kt:1514)
	at androidx.compose.runtime.snapshots.SnapshotKt.readable(Snapshot.kt:1505)
	at androidx.compose.runtime.SnapshotMutableStateImpl.getValue(SnapshotState.kt:143)
	at androidx.compose.material.Colors.getPrimary-0d7_KjU(Colors.kt:338)
	at androidx.compose.material.ButtonDefaults.buttonColors-ro_MJ88(Button.kt:369)
	at androidx.compose.material.ButtonKt.Button(Button.kt:98)
	at ComposableSingletons$MainKt$lambda-2$1.invoke(main.kt:14)
	at ComposableSingletons$MainKt$lambda-2$1.invoke(main.kt:14)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.ui.platform.TestComposeWindow$setContent$2.invoke(TestComposeWindow.desktop.kt:105)
	at androidx.compose.ui.platform.TestComposeWindow$setContent$2.invoke(TestComposeWindow.desktop.kt:104)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:148)
	at androidx.compose.ui.platform.Wrapper_desktopKt$ProvideDesktopCompositionsLocals$1.invoke(Wrapper.desktop.kt:59)
	at androidx.compose.ui.platform.Wrapper_desktopKt$ProvideDesktopCompositionsLocals$1.invoke(Wrapper.desktop.kt:58)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
	at androidx.compose.ui.platform.Wrapper_desktopKt.ProvideDesktopCompositionsLocals(Wrapper.desktop.kt:55)
	at androidx.compose.ui.platform.Wrapper_desktopKt.access$ProvideDesktopCompositionsLocals(Wrapper.desktop.kt:1)
	at androidx.compose.ui.platform.Wrapper_desktopKt$setContent$1.invoke(Wrapper.desktop.kt:42)
	at androidx.compose.ui.platform.Wrapper_desktopKt$setContent$1.invoke(Wrapper.desktop.kt:41)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.ComposerKt.invokeComposable(Composer.kt:3336)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2583)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2579)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(SnapshotState.kt:540)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2572)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime(Composer.kt:2523)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:476)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:727)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:432)
	at androidx.compose.ui.platform.Wrapper_desktopKt.setContent(Wrapper.desktop.kt:41)
	at androidx.compose.ui.platform.Wrapper_desktopKt.setContent$default(Wrapper.desktop.kt:34)
	at androidx.compose.ui.platform.TestComposeWindow.setContent(TestComposeWindow.desktop.kt:104)
	at MainKt.main$lambda-1(main.kt:14)
	at java.base/java.lang.Thread.run(Thread.java:832)
Exception in thread "Thread-2" java.lang.IllegalArgumentException: Failed Surface.makeRasterN32Premul(500, 500)
	at org.jetbrains.skija.Surface.makeRasterN32Premul(Surface.java:298)
	at androidx.compose.ui.platform.TestComposeWindow.<init>(TestComposeWindow.desktop.kt:56)
	at androidx.compose.ui.platform.TestComposeWindow.<init>(TestComposeWindow.desktop.kt:46)
	at MainKt.main$lambda-3(main.kt:19)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by igordmn** [comment]
The cause is the same as [here](https://github.com/JetBrains/compose-jb/issues/974)
