### ISSUE TITLE
macOS Packaging fails

### ISSUE THREAD

**Issue by AshStefanOltmann** [JetBrains/compose-jb#1020]
Updating from `0.4.0` to `1.0.0-alpha3` the command `packageDmg` fails:

```
java.lang.IllegalArgumentException: path may not be null or empty string. path='null'
	at org.gradle.api.internal.file.AbstractBaseDirFileResolver.doResolve(AbstractBaseDirFileResolver.java:59)
	at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:74)
	at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:48)
	at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:122)
	at org.gradle.api.internal.project.DefaultProject.file(DefaultProject.java:909)
	at org.jetbrains.compose.desktop.application.internal.validation.ValidatedMacOSSigningSettingsKt.validate(ValidatedMacOSSigningSettings.kt:48)
	at org.jetbrains.compose.desktop.application.tasks.AbstractJPackageTask$macSigner$2.invoke(AbstractJPackageTask.kt:182)
	at org.jetbrains.compose.desktop.application.tasks.AbstractJPackageTask$macSigner$2.invoke(AbstractJPackageTask.kt:178)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
```

According to documentation https://github.com/JetBrains/compose-jb/tree/master/tutorials/Signing_and_notarization_on_macOS setting a `keychain.set("/path/to/keychain")` is only optional.

It works fine with `0.4.0` so I assume a bug.

**Comment by igordmn** [comment]
Reopened. See https://github.com/JetBrains/compose-jb/pull/1093#issuecomment-917051412

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5326">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
