### ISSUE TITLE
Exception throw while using compose.desktop.components.splitPane

### ISSUE THREAD

**Issue by sonder-joker** [JetBrains/compose-jb#1036]
```
java.lang.IllegalStateException: CompositionLocal LocalAppWindow not provided
	at androidx.compose.desktop.AppWindow_desktopKt$LocalAppWindow$1.invoke(AppWindow.desktop.kt:50)
	at androidx.compose.desktop.AppWindow_desktopKt$LocalAppWindow$1.invoke(AppWindow.desktop.kt:49)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.compose.runtime.LazyValueHolder.getCurrent(ValueHolders.kt:29)
	at androidx.compose.runtime.LazyValueHolder.getValue(ValueHolders.kt:31)
	at androidx.compose.runtime.ComposerImpl.resolveCompositionLocal(Composer.kt:1780)
	at androidx.compose.runtime.ComposerImpl.consume(Composer.kt:1750)
```
The reason is obviously that use deprecated LocalAppWindow. 
```kotlin
private fun Modifier.cursorForHorizontalResize(
    isHorizontal: Boolean
): Modifier = composed {
    var isHover by remember { mutableStateOf(false) }

    if (isHover) {
        LocalAppWindow.current.window.cursor = Cursor(
            if (isHorizontal) Cursor.E_RESIZE_CURSOR else Cursor.S_RESIZE_CURSOR
        )
    } else {
        LocalAppWindow.current.window.cursor = Cursor.getDefaultCursor()
    }
    pointerMoveFilter(
        onEnter = { isHover = true; true },
        onExit = { isHover = false; true }
    )
}
```
It's use a LocalAppWindow to get it. How about use 
```kotlin
internal val LocalWindow = compositionLocalOf<Window?> { null }
```
to instead it?
If you can give some advice about how to fix it , I will make a pull request on it.

**Comment by akurasov** [comment]
Now we have new API for cursor changing - Modifier.pointerIcon. Take a look at https://github.com/JetBrains/compose-jb/blob/242ec6bbf9b9df085e9d6e56e63e14ff82e4a52d/examples/widgets-gallery/common/src/desktopMain/kotlin/org/jetbrains/compose/demo/widgets/platform/Mouse.kt as an example. I think it should work here.

**Comment by sonder-joker** [comment]
Already create a pull request ! Wait for your review

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5314">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
