### ISSUE TITLE
Exception when inputting emoji after pressing Backspace in an empty TextField

### ISSUE THREAD

**Issue by sean-lee-zz** [JetBrains/compose-jb#1070]
### condition
1. press Backspace in empty TextField
2. input emoji
3. crash

### env
OS: MacOS Catalina
JDK: open-jdk 15

### stack trace

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: start cannot be negative. [start: -1]
	at androidx.compose.ui.text.TextRangeKt.packWithCheck(TextRange.kt:121)
	at androidx.compose.ui.text.TextRangeKt.TextRange(TextRange.kt:37)
	at androidx.compose.ui.text.input.EditingBuffer.delete$ui_text(EditingBuffer.kt:190)
	at androidx.compose.ui.text.input.DeleteSurroundingTextInCodePointsCommand.applyTo(EditCommand.kt:354)
	at androidx.compose.ui.text.input.EditProcessor.apply(EditProcessor.kt:93)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion.onEditCommand(TextFieldDelegate.kt:198)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion.access$onEditCommand(TextFieldDelegate.kt:90)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion$restartInput$1.invoke(TextFieldDelegate.kt:246)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion$restartInput$1.invoke(TextFieldDelegate.kt:246)
	at androidx.compose.ui.platform.DesktopPlatformInput.replaceInputMethodText$ui(DesktopPlatformInput.desktop.kt:135)
	at androidx.compose.ui.platform.DesktopOwners.onInputMethodEvent(DesktopOwners.desktop.kt:228)
	at androidx.compose.ui.awt.ComposeLayer$initCanvas$1$inputMethodTextChanged$1.invoke(ComposeLayer.desktop.kt:167)
	at androidx.compose.ui.awt.ComposeLayer$initCanvas$1$inputMethodTextChanged$1.invoke(ComposeLayer.desktop.kt:166)
	at androidx.compose.ui.awt.AWTDebounceEventQueue$job$1.invokeSuspend(AWTDebounceEventQueue.desktop.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:316)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by akurasov** [comment]
Same exception and similar reproduction steps as in https://github.com/JetBrains/compose-jb/issues/1067.

**Comment by prepor** [comment]
CL with a fix https://android-review.googlesource.com/c/platform/frameworks/support/+/1798088

**Comment by olonho** [comment]
Need to check if fixed in beta5.

**Comment by akurasov** [comment]
Works fine in 1.0.0-beta6-dev462

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5292">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
