### ISSUE TITLE
TextField crashes when inputing emoji using Windows 10 emoji picker

### ISSUE THREAD

**Issue by atoktoto** [JetBrains/compose-jb#112]
The code is a `desktop-template` with a single `TextField`:

```
fun main() = Window {
    var text by remember { mutableStateOf("Hello, World!") }

    MaterialTheme {
        TextField(text, onValueChange = { text = it })
    }
}
```

![obraz](https://user-images.githubusercontent.com/34739613/99518957-85fed800-2991-11eb-9876-2bcc09cc8440.png)

Emoji picker for reference:

![obraz](https://user-images.githubusercontent.com/34739613/99518981-90b96d00-2991-11eb-929c-9bb32be0ed8f.png)

The exception thrown
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: event.text must not be null
	at androidx.compose.ui.platform.DesktopPlatformInput.onInputMethodTextChanged(DesktopPlatformInput.kt:161)
	at androidx.compose.ui.platform.DesktopOwners.onInputMethodTextChanged(DesktopOwners.kt:160)
	at androidx.compose.desktop.ComposeWindow$initCanvas$1$inputMethodTextChanged$1.invoke(ComposeWindow.kt:99)
	at androidx.compose.desktop.ComposeWindow$initCanvas$1$inputMethodTextChanged$1.invoke(ComposeWindow.kt)
	at androidx.compose.desktop.AWTDebounceEventQueue$job$1.invokeSuspend(AWTDebounceEventQueue.kt:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by prepor** [comment]
It should work with 0.3.0-build133

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5618">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
