### ISSUE TITLE
copy image to BasicTextField crash 

### ISSUE THREAD

**Issue by Loror** [JetBrains/compose-jb#1148]
when i use ctr+c copy a image from filesystem, then focus in BasicTextField and tap ctr+v,it crashed

Exception in thread "AWT-EventQueue-0" java.awt.datatransfer.UnsupportedFlavorException: Unicode String
	at java.desktop/sun.awt.datatransfer.SunClipboard.getData(SunClipboard.java:215)
	at androidx.compose.ui.platform.DesktopClipboardManager.getText(DesktopClipboardManager.desktop.kt:31)
	at androidx.compose.foundation.text.selection.TextFieldSelectionManager.paste$foundation(TextFieldSelectionManager.kt:436)
	at androidx.compose.foundation.text.TextFieldKeyInput.process-ZmokQxo(TextFieldKeyInput.kt:97)
	at androidx.compose.foundation.text.TextFieldKeyInputKt$textFieldKeyInput$1$1.invoke-ZmokQxo(TextFieldKeyInput.kt:576)
	at androidx.compose.foundation.text.TextFieldKeyInputKt$textFieldKeyInput$1$1.invoke(TextFieldKeyInput.kt:576)
	at androidx.compose.ui.node.ModifiedKeyInputNode.propagateKeyEvent-ZmokQxo(ModifiedKeyInputNode.kt:44)
	at androidx.compose.ui.input.key.KeyInputModifier.processKeyInput-ZmokQxo(KeyInputModifier.kt:74)
	at androidx.compose.ui.platform.DesktopOwner.sendKeyEvent-ZmokQxo(DesktopOwner.desktop.kt:181)
	at androidx.compose.ui.platform.DesktopOwners.consumeKeyEvent(DesktopOwners.desktop.kt:157)
	at androidx.compose.ui.platform.DesktopOwners.onKeyPressed(DesktopOwners.desktop.kt:160)
	at androidx.compose.desktop.ComposeLayer$initCanvas$5$keyPressed$1.invoke(ComposeLayer.desktop.kt:194)
	at androidx.compose.desktop.ComposeLayer$initCanvas$5$keyPressed$1.invoke(ComposeLayer.desktop.kt:193)
	at androidx.compose.desktop.AWTDebounceEventQueue$job$1.invokeSuspend(AWTDebounceEventQueue.desktop.kt:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
MESSAGE_HEART:send a heart
MESSAGE_RECEIVE_MSG:udp:[ip:null,id:null,gId:null,sender:null,receiver:null,message:ok,number:0,replyed:false,canceled:false,appnull,path:null,voiceLength:0,imei:null,version:null,recType:0,mesType:0,time:null]
recive_type:0

**Comment by prepor** [comment]
What version of Compose are you using?

**Comment by prepor** [comment]
Related https://github.com/JetBrains/compose-jb/issues/818

**Comment by christoph-grimm** [comment]
Basic Textfield seems to make major problems in 344, 348. 
Lines do not match cursor positions here after copy/paste or selection operations. 

331 was still ok, no problem. Switching to 344, 348 introduces issues.

**Comment by igordmn** [comment]
It shouldn't crash in 1.0.0-beta5, when we try to paste non-text into textfield.

Let us know, if it is still crashes

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5283">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
