### ISSUE TITLE
Using common font in two instances of application on Windows

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#115]
Compose version: 0.2.0-build124
OS: Windows

1. run two instances of "codeviewer" example
2. open any ".kt" file in the first instance
3. open any ".kt" file in the second instance

```
Exception in thread "AWT-EventQueue-0" java.nio.file.AccessDeniedException: C:\Users\Igor\AppData\Local\Temp\compose\font\jetbrainsmono_regular.ttf
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:274)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
        at java.base/java.nio.file.Files.deleteIfExists(Files.java:1185)
        at java.base/java.nio.file.Files.copy(Files.java:3132)
        at androidx.compose.ui.text.platform.DesktopFontKt.getFontPathAsString(DesktopFont.kt:98)
        at androidx.compose.ui.text.platform.DesktopFontKt.typefaceResource(DesktopFont.kt:81)
        at androidx.compose.ui.text.platform.DesktopFontKt.access$typefaceResource(DesktopFont.kt)
        at androidx.compose.ui.text.platform.FontLoader.load(DesktopFont.kt:67)
        at androidx.compose.ui.text.platform.FontLoader.ensureRegistered(DesktopFont.kt:56)
        at androidx.compose.ui.text.platform.DesktopParagraphKt.toSkTextStyle(DesktopParagraph.kt:652)
        at androidx.compose.ui.text.platform.DesktopParagraphKt.access$toSkTextStyle(DesktopParagraph.kt)
        at androidx.compose.ui.text.platform.ParagraphBuilder.makeSkTextStyle(DesktopParagraph.kt:579)
        at androidx.compose.ui.text.platform.ParagraphBuilder.build(DesktopParagraph.kt:414)
        at androidx.compose.ui.text.platform.DesktopParagraphIntrinsics.<init>(DesktopParagraphIntrinsics.kt:67)
        at androidx.compose.ui.text.platform.DesktopParagraphIntrinsicsKt.ActualParagraphIntrinsics(DesktopParagraphIntrinsics.kt:37)
        at androidx.compose.ui.text.ParagraphIntrinsicsKt.ParagraphIntrinsics(ParagraphIntrinsics.kt:54)
        at androidx.compose.ui.text.MultiParagraphIntrinsics.<init>(MultiParagraphIntrinsics.kt:76)
        at androidx.compose.ui.text.TextDelegate.layoutIntrinsics(TextDelegate.kt:117)
        at androidx.compose.ui.text.TextDelegate.layoutText(TextDelegate.kt:139)
        at androidx.compose.ui.text.TextDelegate.layout-BAnaFRY(TextDelegate.kt:197)
        at androidx.compose.foundation.text.TextController$measure$1.invoke(CoreText.kt:268)
        at androidx.compose.foundation.text.TextController$measure$1.invoke(CoreText.kt)
        at androidx.compose.ui.layout.LayoutKt$measureBlocksOf$1.measure-8A2P9vY(Layout.kt:144)
        at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:47)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
        at androidx.compose.ui.node.LayerWrapper.performMeasure-BRTryo0(LayerWrapper.kt:67)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.foundation.layout.PaddingModifier.measure-za8Wrwc(LayoutPadding.kt:210)
        at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
        at androidx.compose.ui.node.LayerWrapper.performMeasure-BRTryo0(LayerWrapper.kt:67)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:94)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:133)
        at androidx.compose.ui.platform.DesktopOwner.observeMeasureModelReads(DesktopOwner.kt:200)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:93)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:66)
        at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1230)
        at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Box.kt:128)
        at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Box.kt)
        at androidx.compose.ui.layout.LayoutKt$MeasuringIntrinsicsMeasureBlocks$1.measure-8A2P9vY(Layout.kt:383)
        at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:47)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:94)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:133)
        at androidx.compose.ui.platform.DesktopOwner.observeMeasureModelReads(DesktopOwner.kt:200)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:93)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:66)
        at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1230)
        at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasureBlocks$1.invoke(RowColumnImpl.kt:90)
        at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasureBlocks$1.invoke(RowColumnImpl.kt)
        at androidx.compose.ui.layout.LayoutKt$measureBlocksOf$1.measure-8A2P9vY(Layout.kt:144)
        at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:47)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:94)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:133)
        at androidx.compose.ui.platform.DesktopOwner.observeMeasureModelReads(DesktopOwner.kt:200)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:93)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:66)
        at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1230)
        at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Box.kt:106)
        at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Box.kt)
        at androidx.compose.ui.layout.LayoutKt$MeasuringIntrinsicsMeasureBlocks$1.measure-8A2P9vY(Layout.kt:383)
        at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:47)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.foundation.layout.SizeModifier.measure-za8Wrwc(LayoutSize.kt:711)
        at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:94)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:133)
        at androidx.compose.ui.platform.DesktopOwner.observeMeasureModelReads(DesktopOwner.kt:200)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:93)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:66)
        at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1230)
        at androidx.compose.foundation.lazy.LazyListState.measure-5vC3nwU$foundation(LazyListState.kt:380)
        at androidx.compose.foundation.lazy.LazyListKt$LazyList$1.invoke(LazyList.kt:63)
        at androidx.compose.foundation.lazy.LazyListKt$LazyList$1.invoke(LazyList.kt)
        at androidx.compose.ui.layout.SubcomposeLayoutState$createMeasureBlocks$1.measure-8A2P9vY(SubcomposeLayout.kt:211)
        at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:47)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.foundation.layout.PaddingModifier.measure-za8Wrwc(LayoutPadding.kt:210)
        at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
        at androidx.compose.ui.node.LayerWrapper.performMeasure-BRTryo0(LayerWrapper.kt:67)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.foundation.layout.FillModifier.measure-za8Wrwc(LayoutSize.kt:645)
        at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:94)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:133)
        at androidx.compose.ui.platform.DesktopOwner.observeMeasureModelReads(DesktopOwner.kt:200)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:93)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:66)
        at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1230)
        at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Box.kt:128)
        at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Box.kt)
        at androidx.compose.ui.layout.LayoutKt$MeasuringIntrinsicsMeasureBlocks$1.measure-8A2P9vY(Layout.kt:383)
        at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:47)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.foundation.layout.FillModifier.measure-za8Wrwc(LayoutSize.kt:645)
        at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:127)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:94)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1721)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:128)
        at androidx.compose.ui.platform.DesktopOwner.observeMeasureModelReads(DesktopOwner.kt:200)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:93)
        at androidx.compose.ui.node.LayoutNode.remeasure-BRTryo0$ui(LayoutNode.kt:1237)
        at androidx.compose.ui.node.LayoutNode.remeasure-BRTryo0$default(LayoutNode.kt:1235)
        at androidx.compose.ui.node.LayoutNode.onBeforeLayoutChildren(LayoutNode.kt:1043)
        at androidx.compose.ui.node.LayoutNode.layoutChildren(LayoutNode.kt:932)
        at androidx.compose.ui.node.LayoutNode.onNodePlaced$ui(LayoutNode.kt:927)
        at androidx.compose.ui.node.InnerPlaceable.placeAt-iGa6aRc(InnerPlaceable.kt:119)
        at androidx.compose.ui.layout.Placeable$PlacementScope.place-z2mxYZE(Placeable.kt:206)
        at androidx.compose.ui.layout.Placeable$PlacementScope.place-z2mxYZE$default(Placeable.kt:205)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-iGa6aRc(OuterMeasurablePlaceable.kt:119)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.replace(OuterMeasurablePlaceable.kt:127)
        at androidx.compose.ui.node.LayoutNode.replace$ui(LayoutNode.kt:826)
        at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:220)
        at androidx.compose.ui.platform.DesktopOwner.measureAndLayout(DesktopOwner.kt:167)
        at androidx.compose.ui.platform.DesktopOwners.onFrame(DesktopOwners.kt:85)
        at androidx.compose.ui.platform.DesktopOwners$onFrame$1.invokeSuspend(DesktopOwners.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Failed requirement.
        at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:195)
        at androidx.compose.ui.platform.DesktopOwner.measureAndLayout(DesktopOwner.kt:167)
        at androidx.compose.ui.platform.DesktopOwner.onPointerMove-k-4lQ0M$ui(DesktopOwner.kt:275)
        at androidx.compose.ui.platform.DesktopOwners.onMouseMoved(DesktopOwners.kt:137)
        at androidx.compose.desktop.ComposeWindow$initCanvas$3$mouseMoved$1.invoke(ComposeWindow.kt:129)
        at androidx.compose.desktop.ComposeWindow$initCanvas$3$mouseMoved$1.invoke(ComposeWindow.kt)
        at androidx.compose.desktop.AWTDebounceEventQueue$job$1.invokeSuspend(AWTDebounceEventQueue.kt:58)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by loopdeer** [comment]
I believe this issue is also caused when a Dialog is opened when a custom typography is set:
I am getting a java.nio.file.AccessDeniedException when calling opening a Dialog with a custom font set.
```
MaterialTheme (
        colors = LightColors,
        typography = myTypography
            ){

        Column {
            Button({ dialogState.value = true }) {
                Text(text.value)
            }
            if (dialogState.value) {
                Dialog({dialogState.value = false}){
                    Button({}){Text("Hi")}
                }
            }

        }
    }
```

**Comment by prepor** [comment]
I think that it was solved together with https://github.com/JetBrains/compose-jb/issues/171. Feel free to reopen if you encounter this problem again

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5616">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
