### ISSUE TITLE
DesktopOwnersAmbient not provided

### ISSUE THREAD

**Issue by memonahmedanees** [JetBrains/compose-jb#1163]
when i add Material Alert Dialog to my project cant works however in android studio this works 

Exception in thread "main" java.lang.IllegalStateException: CompositionLocal DesktopOwnersAmbient not provided
	at androidx.compose.ui.platform.DesktopOwners_desktopKt$LocalDesktopOwners$1.invoke(DesktopOwners.desktop.kt:39)
	at androidx.compose.ui.platform.DesktopOwners_desktopKt$LocalDesktopOwners$1.invoke(DesktopOwners.desktop.kt:38)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.compose.runtime.LazyValueHolder.getCurrent(ValueHolders.kt:29)
	at androidx.compose.runtime.LazyValueHolder.getValue(ValueHolders.kt:31)
	at androidx.compose.runtime.ComposerImpl.resolveCompositionLocal(Composer.kt:1780)
	at androidx.compose.runtime.ComposerImpl.consume(Composer.kt:1750)
	at androidx.compose.ui.window.DesktopPopup_desktopKt.PopupLayout(DesktopPopup.desktop.kt:334)
	at androidx.compose.ui.window.DesktopPopup_desktopKt.Popup(DesktopPopup.desktop.kt:126)
	at androidx.compose.ui.window.DesktopPopup_desktopKt.Popup-_4-4ZA4(DesktopPopup.desktop.kt:87)
	at androidx.compose.material.PopupAlertDialogProvider.AlertDialog(DesktopAlertDialog.desktop.kt:180)
	at androidx.compose.material.DesktopAlertDialog_desktopKt.AlertDialog-wqdebIU(DesktopAlertDialog.desktop.kt:136)
	at androidx.compose.material.DesktopAlertDialog_desktopKt.AlertDialog-6oU6zVQ(DesktopAlertDialog.desktop.kt:78)
	at ComposableSingletons$MainKt$lambda-7$1.invoke(Main.kt:21)
	at ComposableSingletons$MainKt$lambda-7$1.invoke(Main.kt:15)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1$1.invoke(Application.desktop.kt:183)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1$1.invoke(Application.desktop.kt:182)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1.invoke(Application.desktop.kt:178)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1.invoke(Application.desktop.kt:176)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:72)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2586)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2575)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(SnapshotState.kt:563)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2575)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime(Composer.kt:2526)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:478)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:727)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:433)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:176)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5272">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
