### ISSUE TITLE
How to compile for raspberry arm64 linux ?

### ISSUE THREAD

**Issue by toplinuxsir** [JetBrains/compose-jb#1170]
I compiled in linux x86_64 platform , when run from raspberry pi arm64 linux , error as below :
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.jetbrains.skiko.SkiaLayer.<init>(SkiaLayer.kt:40)
	at org.jetbrains.skiko.SkiaLayer.<init>(SkiaLayer.kt:23)
	at androidx.compose.ui.awt.ComposeLayer$Wrapped.<init>(ComposeLayer.desktop.kt:81)
	at androidx.compose.ui.awt.ComposeLayer.<init>(ComposeLayer.desktop.kt:62)
	at androidx.compose.ui.awt.ComposeWindowDelegate.<init>(ComposeWindowDelegate.desktop.kt:37)
	at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:36)
	at androidx.compose.ui.window.Window_desktopKt$Window$3$1.invoke(Window.desktop.kt:138)
	at androidx.compose.ui.window.Window_desktopKt$Window$3$1.invoke(Window.desktop.kt:137)
	at androidx.compose.ui.window.Window_desktopKt$Window$10.invoke(Window.desktop.kt:309)
	at androidx.compose.ui.window.Window_desktopKt$Window$10.invoke(Window.desktop.kt:308)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:75)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:74)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:780)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:638)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:733)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:432)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:176)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.jetbrains.skiko.LibraryLoadException: Cannot find libskiko-linux-arm64.so.sha256, proper native dependency missing.
	at org.jetbrains.skiko.Library.load(Library.kt:71)
	at org.jetbrains.skiko.HardwareLayer.<clinit>(HardwareLayer.kt:10)

```

**Comment by toplinuxsir** [comment]
No support for raspberry linux ?

**Comment by akurasov** [comment]
Could you share your build.gradle file here? 
Do you have dependency implementation(compose.desktop.currentOs) there?

**Comment by olonho** [comment]
It depends on how did you run, dependency must include linux_arm64 Skiko library.

**Comment by toplinuxsir** [comment]
@akurasov
```
import org.jetbrains.compose.compose
import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile


plugins {
    kotlin("jvm") version "1.5.21"
    // id("org.jetbrains.compose") version "0.5.0-build270"
    id("org.jetbrains.compose") version "1.0.0-alpha3"
    id("org.jetbrains.kotlin.plugin.noarg") version "1.5.21"
}

group = "me.lhs"
version = "1.0"

repositories {
    jcenter()
    google()
    mavenCentral()
    maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    maven {
        url = uri("https://repository.apache.org/content/repositories/snapshots")
        mavenContent {
            snapshotsOnly()
        }
    }

}

dependencies {
    implementation(compose.desktop.currentOs)
    implementation("org.apache.plc4x:plc4j-api:0.9.0-SNAPSHOT")
    runtimeOnly("org.apache.plc4x:plc4j-driver-s7:0.9.0-SNAPSHOT")
    implementation("org.slf4j:slf4j-api:1.7.32")
    implementation("org.slf4j:slf4j-simple:1.7.32")
    // https://mvnrepository.com/artifact/org.zeromq/jeromq
    implementation("org.zeromq:jeromq:0.5.2")
    // https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp
    implementation("com.squareup.okhttp3:okhttp:4.9.1")
    // https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-xml
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.12.4")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.12.4")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.1")
    // https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-jdk8
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.5.1")

    // https://mvnrepository.com/artifact/com.arkivanov.decompose/decompose
    // runtimeOnly("com.arkivanov.decompose:decompose:0.2.6")
// https://mvnrepository.com/artifact/com.arkivanov.decompose/extensions-compose-jetpack
    // implementation("com.arkivanov.decompose:extensions-compose-jetpack:0.2.6")

    // https://mvnrepository.com/artifact/com.arkivanov.decompose/extensions-compose-jetbrains
    // implementation("com.arkivanov.decompose:extensions-compose-jetbrains:0.2.6")


    // https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-yaml
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.12.4")

}

tasks.withType<KotlinCompile>() {
    kotlinOptions.jvmTarget = "1.8"
}


compose.desktop {
    application {
        mainClass = "MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "PlcReader"
            packageVersion = "1.0.0"
        }
    }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5268">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
