### ISSUE TITLE
Crashed：Unsupported concurrent change during composition. A state object was modified by composition as well as being modified outside composition.

### ISSUE THREAD

**Issue by FlyingYu-Z** [JetBrains/compose-jb#1180]
I got this error when using **mutableStateListOf**

and i update  **mutableStateListOf** in other thread

tried:
![image](https://user-images.githubusercontent.com/23566361/134141138-68070f24-73bb-4db0-9147-5abb86f0b113.png)
tried:
![image](https://user-images.githubusercontent.com/23566361/134141226-9a7e61eb-907f-48aa-9e43-cb06be1c6cc4.png)

```
Exception in thread "main" java.lang.IllegalStateException: Unsupported concurrent change during composition. A state object was modified by composition as well as being modified outside composition.
	at androidx.compose.runtime.Recomposer.applyAndCheck(Recomposer.kt:801)
	at androidx.compose.runtime.Recomposer.access$applyAndCheck(Recomposer.kt:103)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1064)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:103)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:447)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:416)
	at androidx.compose.ui.window.YieldFrameClock.withFrameNanos(Application.desktop.kt:210)
	at androidx.compose.ui.window.YieldFrameClock$withFrameNanos$1.invokeSuspend(Application.desktop.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
how to solve the problem?

**Comment by igordmn** [comment]
Do you have a minimal reproducer? It looks like a bug.

I have tried this:
```
import androidx.compose.foundation.layout.Row
import androidx.compose.material.Text
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.ui.window.singleWindowApplication
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

val list = mutableStateListOf<Int>()

fun main() = singleWindowApplication {
    Row {
        for (item in list) {
            Text(item.toString())
        }
    }
    LaunchedEffect(Unit) {
        withContext(Dispatchers.IO) {
            repeat(1000) {
                list.add(it)
            }
        }
    }
}
```
there is no crash.

**Comment by FlyingYu-Z** [comment]
wait,i am writing the example

**Comment by FlyingYu-Z** [comment]
> Do you have a minimal reproducer? It looks like a bug.
> 
> I have tried this:
> 
> ```
> import androidx.compose.foundation.layout.Row
> import androidx.compose.material.Text
> import androidx.compose.runtime.LaunchedEffect
> import androidx.compose.runtime.mutableStateListOf
> import androidx.compose.ui.window.singleWindowApplication
> import kotlinx.coroutines.Dispatchers
> import kotlinx.coroutines.withContext
> 
> val list = mutableStateListOf<Int>()
> 
> fun main() = singleWindowApplication {
>     Row {
>         for (item in list) {
>             Text(item.toString())
>         }
>     }
>     LaunchedEffect(Unit) {
>         withContext(Dispatchers.IO) {
>             repeat(1000) {
>                 list.add(it)
>             }
>         }
>     }
> }
> ```
> 
> there is no crash.

Sorry for late reply,finally I finished the bug example.
Link is here：https://drive.google.com/file/d/1ylKpIgvxI7OzeEIWZoXTHzeHfPgY_EdG/view?usp=sharing

Run the project,and click "Click to show First Dialog" > "Click me to display bug",then you will get crash

**Comment by igordmn** [comment]
Thanks! I reproduced the crash.

After looking at the code, it no longer looks like a bug.

The crash happened because we modify the list simultaneously from the composition:
```
if(it.dismissed){
   dialogList.remove(it)
}
```
and from another thread (`dialogList.add`)

This is usually not a valid code if you modify any state inside Composable function (this is only valid, if you reading the state immediately after modifying it, and don't modify it anywhere else)

To solve the issue, you should move `dialogList.remove` to non-Composable function. For example, after moving it to `DialogState.dismiss`, the crash disappeared.

**Comment by FlyingYu-Z** [comment]
OK,Thank you for sovle the problem.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5261">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
