### ISSUE TITLE
When using BasicTextField, an error will occur if the Chinese input method is used

### ISSUE THREAD

**Issue by DilongX** [JetBrains/compose-jb#122]
Devices: Windows 10
Microsoft Input Method

Error message:
DesktopPlatformInput.showSoftwareKeyboard
Exception in thread "AWT-EventQueue-0 @coroutine#2" java.lang.NullPointerException: event.text must not be null
	at androidx.compose.ui.platform.DesktopPlatformInput.onInputMethodTextChanged(DesktopPlatformInput.kt:163)
	at androidx.compose.ui.platform.DesktopOwners.onInputMethodTextChanged(DesktopOwners.kt:160)
	at androidx.compose.desktop.ComposeWindow$initCanvas$1$inputMethodTextChanged$1.invoke(ComposeWindow.kt:99)
	at androidx.compose.desktop.ComposeWindow$initCanvas$1$inputMethodTextChanged$1.invoke(ComposeWindow.kt)
	at androidx.compose.desktop.AWTDebounceEventQueue$job$1.invokeSuspend(AWTDebounceEventQueue.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by DilongX** [comment]
Devices: Windows 10
Microsoft Pinyin Input Method

**Comment by olonho** [comment]
Looks like a dup of https://github.com/JetBrains/compose-jb/issues/112.

**Comment by DilongX** [comment]
There seems to be this problem when using Microsoft input method to input languages other than English (including Emoji)

**Comment by prepor** [comment]
It should work 0.3.0-build133

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5609">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
