### ISSUE TITLE
Internal compiler error with generic @Composable function

### ISSUE THREAD

**Issue by NorbertSandor** [JetBrains/compose-jb#1226]
Should generic `@Composable` `fun`s work with Compose/Web?
I get _internal compiler error_ in case of this function:

```
@Composable
fun <T> MySelect(
    options: List<T>,
    onChange: (T?) -> Unit
) ...
```

If I remove the generic type parameter (and replace `T` with `Any` in the parameters) then it compiles.

Kotlin: 1.5.31
Compose/Web: 1.0.0-alpha4-build366

Stack trace:
```
java.lang.IllegalStateException: FULL: FUN name:MySelect$composable visibility:public modality:FINAL <T> (options:kotlin.collections.List<T of ...component.MySelect$composable>, onChange:kotlin.Function1<T of ...component.MySelect$composable?, kotlin.Unit>, $composer:androidx.compose.runtime.Composer?, $changed:kotlin.Int) returnType:kotlin.Unit
 Ir: ...component#MySelect$composable(kotlin.collections.List<0:0>;kotlin.Function1<0:0?,kotlin.Unit>;androidx.compose.runtime.Composer?;kotlin.Int){0�<kotlin.Any?>}
 Descriptor: ...component#MySelect$composable(kotlin.collections.List<0:0>;kotlin.Function1<0:0,kotlin.Unit>;androidx.compose.runtime.Composer?;kotlin.Int){0�<kotlin.Any?>}

	at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker$visitDeclaration$2.invoke(ManglerChecker.kt:63)
	at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker$visitDeclaration$2.invoke(ManglerChecker.kt:62)
	at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.checkAllEqual(ManglerChecker.kt:42)
	at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitDeclaration(ManglerChecker.kt:62)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFunction(IrElementVisitorVoid.kt:49)
	at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitFunction(ManglerChecker.kt:17)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSimpleFunction(IrElementVisitorVoid.kt:52)
	at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitSimpleFunction(ManglerChecker.kt:17)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSimpleFunction(IrElementVisitorVoid.kt:53)
	at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitSimpleFunction(ManglerChecker.kt:17)
	at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitSimpleFunction(ManglerChecker.kt:17)
	at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:28)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.acceptChildren(IrFileImpl.kt:84)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:275)
	at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitElement(ManglerChecker.kt:22)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:30)
	at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitPackageFragment(ManglerChecker.kt:17)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:37)
	at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitFile(ManglerChecker.kt:17)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:38)
	at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitFile(ManglerChecker.kt:17)
	at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitFile(ManglerChecker.kt:17)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.accept(IrFileImpl.kt:81)
	at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.acceptChildren(IrModuleFragmentImpl.kt:40)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:275)
	at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitElement(ManglerChecker.kt:22)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:27)
	at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitModuleFragment(ManglerChecker.kt:17)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:28)
	at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitModuleFragment(ManglerChecker.kt:17)
	at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitModuleFragment(ManglerChecker.kt:17)
	at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.accept(IrModuleFragmentImpl.kt:37)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptVoid(IrElementVisitorVoid.kt:271)
	at org.jetbrains.kotlin.ir.backend.js.KlibKt.generateKLib(klib.kt:174)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:243)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:182)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:75)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:191)
	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:77)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:358)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally$default(IncrementalCompilerRunner.kt:300)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:160)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:81)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile$default(IncrementalCompilerRunner.kt:72)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execJsIncrementalCompiler(CompileServiceImpl.kt:550)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execJsIncrementalCompiler(CompileServiceImpl.kt:96)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1745)
...
```

**Comment by eymar** [comment]
Hi @NorbertSandor 
I know it doesn't help much, but just in case: you can have `onChange: (T) -> Unit` instead of `onChange: (T?) -> Unit` and it should work. We had similar issues https://youtrack.jetbrains.com/issue/KT-48431 It appears to be fixed in kotlin 1.6.0-M1, but it will take time until compose uses 1.6.0

**Comment by NorbertSandor** [comment]
> Hi @NorbertSandor I know it doesn't help much, but just in case: you can have `onChange: (T) -> Unit` instead of `onChange: (T?) -> Unit` and it should work. We had similar issues https://youtrack.jetbrains.com/issue/KT-48431 It appears to be fixed in kotlin 1.6.0-M1, but it will take time until compose uses 1.6.0

@eymar , thanks, it solved the problem when I replaced every nullable parameters of the function with non-nullable parameters.
OMG, it will take ages until Compose will support Kotlin 1.6.0 :(

**Comment by NorbertSandor** [comment]
@eymar , just one more question: is it expected that serialization breaks Compose even is the serialization Gradle plugin is not applied to the Compose project?
In my case these are the project.plugins (printed from `afterEvaluate` of the Compose/Web project):

-     com.android.ide.gradle.model.builder.AndroidStudioToolingPlugin
-     org.gradle.api.plugins.HelpTasksPlugin
-     org.gradle.buildinit.plugins.BuildInitPlugin
-     org.gradle.buildinit.plugins.WrapperPlugin
-     org.jetbrains.compose.ComposeCompilerKotlinSupportPlugin
-     org.jetbrains.compose.ComposePlugin
-     org.gradle.language.base.plugins.LifecycleBasePlugin
-     org.gradle.api.plugins.BasePlugin
-     org.gradle.api.plugins.JvmEcosystemPlugin
-     org.gradle.api.plugins.ReportingBasePlugin
-     org.gradle.api.plugins.JavaBasePlugin$Inject
-     org.jetbrains.kotlin.gradle.scripting.internal.ScriptingKotlinGradleSubplugin
-     org.jetbrains.kotlin.gradle.scripting.internal.ScriptingGradleSubplugin
-     org.jetbrains.kotlin.gradle.plugin.KotlinMultiplatformPluginWrapper
-     org.gradle.kotlin.dsl.provider.plugins.KotlinScriptBasePlugin
-     org.jetbrains.kotlin.gradle.targets.js.npm.NpmResolverPlugin

As you see, the org.jetbrains.kotlinx.serialization.gradle.SerializationGradleSubplugin is not applied (it is applied only in a project that is a dependency of the Compose/Web project).

**Comment by NorbertSandor** [comment]
Some more examples:
```
// Compilation fails:
//
// java.lang.IllegalStateException: FULL: FUN name:CompilationFails$composable visibility:public modality:FINAL <T> (onChange:kotlin.Function1<T of xxx.CompilationFails$composable?, kotlin.Unit>, value:T of xxx.CompilationFails$composable?, $composer:androidx.compose.runtime.Composer?, $changed:kotlin.Int) returnType:kotlin.Unit
// Ir: ...#CompilationFails$composable(kotlin.Function1<0:0?,kotlin.Unit>;0:0?;androidx.compose.runtime.Composer?;kotlin.Int){0�<kotlin.Any?>}
// Descriptor: ...#CompilationFails$composable(kotlin.Function1<0:0,kotlin.Unit>;0:0;androidx.compose.runtime.Composer?;kotlin.Int){0�<kotlin.Any?>}
// 
// at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker$visitDeclaration$2.invoke(ManglerChecker.kt:63)
// at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker$visitDeclaration$2.invoke(ManglerChecker.kt:62)
// at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.checkAllEqual(ManglerChecker.kt:42)
// at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitDeclaration(ManglerChecker.kt:62)
// at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFunction(IrElementVisitorVoid.kt:49)
// at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitFunction(ManglerChecker.kt:17)
// at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSimpleFunction(IrElementVisitorVoid.kt:52)
// at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitSimpleFunction(ManglerChecker.kt:17)
// at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSimpleFunction(IrElementVisitorVoid.kt:53)
// at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitSimpleFunction(ManglerChecker.kt:17)
// at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitSimpleFunction(ManglerChecker.kt:17)
// at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:28)
// at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.acceptChildren(IrFileImpl.kt:84)
// at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:275)
// at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitElement(ManglerChecker.kt:22)
// at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:30)
// at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitPackageFragment(ManglerChecker.kt:17)
// at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:37)
// at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitFile(ManglerChecker.kt:17)
// at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:38)
// at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitFile(ManglerChecker.kt:17)
// at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitFile(ManglerChecker.kt:17)
// at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.accept(IrFileImpl.kt:81)
// at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.acceptChildren(IrModuleFragmentImpl.kt:40)
// at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:275)
// at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitElement(ManglerChecker.kt:22)
// at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:27)
// at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitModuleFragment(ManglerChecker.kt:17)
// at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:28)
// at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitModuleFragment(ManglerChecker.kt:17)
// at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker.visitModuleFragment(ManglerChecker.kt:17)
// at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.accept(IrModuleFragmentImpl.kt:37)
// at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptVoid(IrElementVisitorVoid.kt:271)
// at org.jetbrains.kotlin.ir.backend.js.KlibKt.generateKLib(klib.kt:174)
// at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:243)
// at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:182)
// at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:75)
// at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
// at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
// at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
// at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:191)
// at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:77)
// at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:358)
// at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally$default(IncrementalCompilerRunner.kt:300)
// at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl$rebuild(IncrementalCompilerRunner.kt:119)
// at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:170)
// at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:81)
// at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile$default(IncrementalCompilerRunner.kt:72)
// at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execJsIncrementalCompiler(CompileServiceImpl.kt:550)
// at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execJsIncrementalCompiler(CompileServiceImpl.kt:96)
// at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1745)
// at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
// at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
// at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
// at java.base/java.lang.reflect.Method.invoke(Method.java:566)
// at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
// at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
// at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
// at java.base/java.security.AccessController.doPrivileged(Native Method)
// at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
// at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
// at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
// at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
// at java.base/java.security.AccessController.doPrivileged(Native Method)
// at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
// at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
// at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
// at java.base/java.lang.Thread.run(Thread.java:834)
@Composable
fun <T> CompilationFails(
    onChange: (T?) -> Unit,
    value: T?
) {
    TODO()
}

// Compilation succeeds...
@Composable
fun <T> CompilationSucceeds(
    onChange: (NullableWrapper<T>) -> Unit,
    valueWrapper: NullableWrapper<T> // ... but would fail with 'java.lang.IllegalStateException: Not found Idx for ...' if this parameter would have a default value: = NullWrapper()
) {
    TODO()
}

// TODO delete after Kotlin 1.6.0 upgrade: https://github.com/JetBrains/compose-jb/issues/1226
sealed class NullableWrapper<T> {
    companion object {
        fun <T> of(value: T?): NullableWrapper<T> =
            if (value != null) {
                NonNullWrapper(value)
            } else {
                NullWrapper()
            }
    }

    abstract val value: T?
}

class NonNullWrapper<T>(override val value: T) : NullableWrapper<T>()

class NullWrapper<T> : NullableWrapper<T>() {
    override val value: T? get() = null
}
```

**Comment by eymar** [comment]
> @eymar , just one more question: is it expected that serialization breaks Compose even if the serialization Gradle plugin is not applied to the Compose project? In my case these are the project.plugins (printed from `afterEvaluate` of the Compose/Web project):
> 
> ....
> 
> As you see, the org.jetbrains.kotlinx.serialization.gradle.SerializationGradleSubplugin is not applied (it is applied only in a project that is a dependency of the Compose/Web project).


In my opinion, it's safe to use kotlinx.serialization and compose plugins in different modules. Moreover, starting from kotlin 1.5.30 they both are supposed to work  fine when applied within the same module. 

The stacktrace of the above issue doesn't really mention kotlinx.serialization (`org.jetbrains.kotlin.backend.common.serialization.mangle` is another package related to kotlin compiler, but not kotlinx.serialization ).
```
at org.jetbrains.kotlin.backend.common.serialization.mangle.ManglerChecker
.....
at org.jetbrains.kotlin.ir.backend.js.KlibKt.generateKLib(klib.kt:174)
at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:243)
```


And thank you for adding more examples!

**Comment by eymar** [comment]
these issues were fixed. Should work in 1.0.1-rc2 with kotlin 1.6.10

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6163">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
