### ISSUE TITLE
[Windows] - RuntimeException : Can't wrap nullptr

### ISSUE THREAD

**Issue by Ethras** [JetBrains/compose-jb#125]
Hello, 
Running the code from the Getting Started guide I'm getting the following exception on a brand new installation of Windows 10 with OpenJDK 14.

> SkIcuLoader: datafile missing: C:\Users\mbassi\.jdks\adopt-openj9-14.0.2\bin\icudtl.dat.
>Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Can't wrap nullptr
	at org.jetbrains.skija.impl.Native.<init>(Native.java:12)
	at org.jetbrains.skija.impl.Managed.<init>(Managed.java:15)
	at org.jetbrains.skija.impl.Managed.<init>(Managed.java:11)
	at org.jetbrains.skija.impl.RefCnt.<init>(RefCnt.java:7)
	at org.jetbrains.skija.Context.<init>(Context.java:20)
	at org.jetbrains.skiko.RenderTargetsKt.makeGLContext(RenderTargets.kt:6)
	at org.jetbrains.skiko.SkiaLayer.draw(SkiaWindow.kt:55)
	at org.jetbrains.skiko.HardwareLayer.redrawLayer(Native Method)
	at androidx.compose.desktop.FrameSkiaLayer.onFrame(FrameSkiaLayer.kt:49)
	at androidx.compose.desktop.FrameSkiaLayer$onFrame$1.invokeSuspend(FrameSkiaLayer.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.desktop/java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:316)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Here is the actual window I get
![image](https://user-images.githubusercontent.com/17152220/99689061-cb510180-2a86-11eb-8040-dba7c04b4fd3.png)

**Comment by olonho** [comment]
Seems Skia cannot create OpenGL context. Could you please check if other OpenGL program works on the same computer.

**Comment by Ethras** [comment]
My bad, I was trying to use Compose in a Hyper-V VM. Guess that's my issue

**Comment by yuhailong626** [comment]
I ran into the same problem on VirtualBox VM. Does this mean that compose-lib cannot run on a virtual machine?

**Comment by Fabian-K** [comment]
I just stumbled upon this on a "normal" windows laptop

```
SkIcuLoader: datafile missing: I:\download\openjdk-11+28_windows-x64_bin\jdk-11\bin\icudtl.dat.
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Can't wrap nullptr
        at org.jetbrains.skija.impl.Native.<init>(Native.java:12)
...
```

**Comment by Itsusinn** [comment]
I have the same problem on win10
SkIcuLoader: datafile missing  jdk\bin\icudtl.dat

**Comment by Shabinder** [comment]
Same Upon , ./gradlew :desktop:run

Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Can't wrap nullptr

**Comment by ypujante** [comment]
Same here (using brand new demo app created by IDEA 2020.3 wizard)

On Windows 10 using zulu

```
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment Zulu15.28+51-CA (build 15.0.1+9)
OpenJDK 64-Bit Server VM Zulu15.28+51-CA (build 15.0.1+9, mixed mode, sharing)
```

```
.\gradlew.bat run

> Task :run
SkIcuLoader: datafile missing: C:\Program Files\Zulu\zulu-15\bin\icudtl.dat.
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Can't wrap nullptr
        at org.jetbrains.skija.impl.Native.<init>(Native.java:12)
        at org.jetbrains.skija.impl.Managed.<init>(Managed.java:15)
        at org.jetbrains.skija.impl.Managed.<init>(Managed.java:11)
        at org.jetbrains.skija.impl.RefCnt.<init>(RefCnt.java:7)
        at org.jetbrains.skija.DirectContext.<init>(DirectContext.java:21)
        at org.jetbrains.skiko.RenderTargetsKt.makeGLContext(RenderTargets.kt:6)
        at org.jetbrains.skiko.SkiaLayer.draw(SkiaWindow.kt:55)
        at org.jetbrains.skiko.HardwareLayer.redrawLayer(Native Method)
        at androidx.compose.desktop.ComposeLayer.onFrame(ComposeLayer.kt:75)
        at androidx.compose.desktop.ComposeLayer$onFrame$1.invokeSuspend(ComposeLayer.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Can't wrap nullptr
```

**Comment by ypujante** [comment]
I just tried with a different version of the JDK (the official Oracle distribution) and it is the same error:

```
java version "15.0.2" 2021-01-19
Java(TM) SE Runtime Environment (build 15.0.2+7-27)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)
```

```
SkIcuLoader: datafile missing: C:\Program Files\Java\jdk-15.0.2\bin\icudtl.dat.
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Can't wrap nullptr
```

**Comment by Shabinder** [comment]
I tried in linux and it is working , but issue still occurs in windows.

**Comment by ypujante** [comment]
I also made sure I was using the most recent version of compose-jb (I was not due to the IDEA wizard generating the build file with an old version).

```
plugins {
    kotlin("jvm") version "1.4.21"
    id("org.jetbrains.compose") version "0.3.0-build141"
}
```

And with the most recent version it still doesn't work.

**Comment by olonho** [comment]
Shall be fixed by software rendering support.

**Comment by gagarin55** [comment]
Got same error with VirtualBox, Windows 10, JDK 15 ;(

**Comment by olonho** [comment]
Please check with 0.3.0-rc1.

**Comment by moodi1999** [comment]
Upgrade to 

```
kotlin("jvm") version "1.4.31"
id("org.jetbrains.compose") version "0.3.2"
```
with JDK 15 

error disappeared :)

**Comment by akurasov** [comment]
Does anyone still have this issue?

**Comment by Fabian-K** [comment]
For me this is resolved :)

**Comment by akurasov** [comment]
Closing then

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5607">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
