### ISSUE TITLE
Unable to run desktop-template on aarch64 device

### ISSUE THREAD

**Issue by MFAshby** [JetBrains/compose-jb#126]
Reproduction steps: 
* Using a pinebook-pro laptop running manjaro arm linux (aarch64 CPU architecture)
* Clone the desktop-template https://github.com/JetBrains/compose-jb/tree/master/templates/desktop-template 
* Run the script to start the application `./gradlew run`

Expected behaviour: 
* Application starts and runs

Actual behaviour: 
* Application crashes with the following stacktrace :
```
$ ./gradlew run

> Task :run
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: /home/martin/.skiko/15d8e668e3911ea79b7f1749f03ab121f61e5b31cc9dfae81c7505455e590092/libskiko.so: /home/martin/.skiko/15d8e668e3911ea79b7f1749f03ab121f61e5b31cc9dfae81c7505455e590092/libskiko.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64 .so on a AARCH64 platform)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2452)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2508)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2704)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2637)
        at java.base/java.lang.Runtime.load0(Runtime.java:745)
        at java.base/java.lang.System.load(System.java:1871)
        at org.jetbrains.skiko.Library.loadOrGet(Library.kt:25)
        at org.jetbrains.skiko.Library.load(Library.kt:44)
        at androidx.compose.desktop.ComposeInit.<clinit>(ComposeInit.kt:45)
        at androidx.compose.desktop.ComposeInitKt.initCompose(ComposeInit.kt:40)
        at androidx.compose.desktop.ComposeWindow.<clinit>(ComposeWindow.kt:39)
        at androidx.compose.desktop.AppWindow.<init>(AppWindow.kt:77)
        at androidx.compose.desktop.AppWindow.<init>(AppWindow.kt)
        at androidx.compose.desktop.AppWindowKt$Window$1.run(AppWindow.kt:53)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

BUILD SUCCESSFUL in 7s
4 actionable tasks: 1 executed, 3 up-to-date
```

**Comment by MFAshby** [comment]
I see it might just have been fixed https://github.com/JetBrains/compose-jb/pull/113/files

**Comment by olonho** [comment]
Linux ARM is not supported by Compose at the moment, as Skiko library is not ported yet.

**Comment by olonho** [comment]
As of 0.5.0-build229 we support linux-arm64 in Compose builds.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5606">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
