### ISSUE TITLE
LazyColumn crashes with empty list.

### ISSUE THREAD

**Issue by Klurige** [JetBrains/compose-jb#1266]
LazyColumn crashes on mouseOver (and probable other events) if the list is empty.
Tested on Ubuntu 20.04.

Run the following and move the mouse over the window:

        fun main() = application {
            Window(onCloseRequest = ::exitApplication) {
                val myList: List<String> = emptyList()
                MaterialTheme {
                    Box(Modifier.fillMaxSize())
                    {
                        Column {
                            LazyColumn {
                                items(myList) {
                                    Text(it)
                                }
                            }
                        }
                    }
                }
            }
        }

The app crashes with the following exception:
        Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at androidx.compose.ui.platform.SkiaLayer.isInLayer-k-4lQ0M(SkiaLayer.desktop.kt:132)
	at androidx.compose.ui.node.LayoutNodeWrapper.withinLayerBounds-3MmeM6k(LayoutNodeWrapper.kt:640)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.hitTest-9KIMszo(DelegatingLayoutNodeWrapper.kt:77)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.hitTest-9KIMszo(DelegatingLayoutNodeWrapper.kt:79)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.hitTest-9KIMszo(DelegatingLayoutNodeWrapper.kt:79)
	at androidx.compose.ui.node.LayoutNode.hitTest-9KIMszo$ui(LayoutNode.kt:858)
	at androidx.compose.ui.node.InnerPlaceable.hitTest-9KIMszo(InnerPlaceable.kt:146)
	at androidx.compose.ui.node.LayoutNode.hitTest-9KIMszo$ui(LayoutNode.kt:858)
	at androidx.compose.ui.node.InnerPlaceable.hitTest-9KIMszo(InnerPlaceable.kt:146)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.hitTest-9KIMszo(DelegatingLayoutNodeWrapper.kt:79)
	at androidx.compose.ui.node.LayoutNode.hitTest-9KIMszo$ui(LayoutNode.kt:858)
	at androidx.compose.ui.node.InnerPlaceable.hitTest-9KIMszo(InnerPlaceable.kt:146)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.hitTest-9KIMszo(DelegatingLayoutNodeWrapper.kt:79)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.hitTest-9KIMszo(DelegatingLayoutNodeWrapper.kt:79)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.hitTest-9KIMszo(DelegatingLayoutNodeWrapper.kt:79)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.hitTest-9KIMszo(DelegatingLayoutNodeWrapper.kt:79)
	at androidx.compose.ui.node.LayoutNode.hitTest-9KIMszo$ui(LayoutNode.kt:858)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:67)
	at androidx.compose.ui.platform.DesktopOwner.processPointerInput-8iAsVTc$ui(DesktopOwner.desktop.kt:340)
	at androidx.compose.ui.platform.DesktopOwners.sendPointerEvent-DHzpxOM(DesktopOwners.desktop.kt:374)
	at androidx.compose.ui.awt.ComposeLayer_desktopKt.onMouseEvent(ComposeLayer.desktop.kt:260)
	at androidx.compose.ui.awt.ComposeLayer_desktopKt.access$onMouseEvent(ComposeLayer.desktop.kt:1)
	at androidx.compose.ui.awt.ComposeLayer$3$mouseEntered$1.invoke(ComposeLayer.desktop.kt:171)
	at androidx.compose.ui.awt.ComposeLayer$3$mouseEntered$1.invoke(ComposeLayer.desktop.kt:170)
	at androidx.compose.ui.awt.AWTDebounceEventQueue$job$1.invokeSuspend(AWTDebounceEventQueue.desktop.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Here is teh contents of build.gradle.kts:

    import org.jetbrains.compose.compose
    import org.jetbrains.compose.desktop.application.dsl.TargetFormat
    import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
    
    plugins {
        kotlin("jvm") version "1.5.31"
        id("org.jetbrains.compose") version "1.0.0-alpha4-build398"
    }
    
    group = "me.test"
    version = "1.0"
    
    repositories {
        google()
        mavenCentral()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    }
    
    dependencies {
        implementation(compose.desktop.currentOs)
    }
    
    tasks.withType<KotlinCompile>() {
        kotlinOptions.jvmTarget = "16"
    }
    
    kotlin.sourceSets.all {
        languageSettings.optIn("kotlin.RequiresOptIn")
    }
    
    compose.desktop {
        application {
            mainClass = "MainKt"
            nativeDistributions {
                targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
                packageName = "untitled"
                packageVersion = "1.0.0"
            }
        }
    }

**Comment by igordmn** [comment]
This crash should be fixed in `1.0.0-beta5`. If it still crashes on your side, let us know.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6258">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
