### ISSUE TITLE
java.lang.IllegalStateException: Only Sp can convert to Px; BasicTextField

### ISSUE THREAD

**Issue by yandroidUA** [JetBrains/compose-jb#133]
After update to `0.2.0-build128` program fails with:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Only Sp can convert to Px
	at androidx.compose.ui.unit.Density$DefaultImpls.toPx--R2X_6o(Density.kt:86)
	at androidx.compose.ui.unit.DensityImpl.toPx--R2X_6o(Density.kt:34)
	at androidx.compose.ui.text.platform.ComputedStyle.<init>(DesktopParagraph.kt:416)
	at androidx.compose.ui.text.platform.ParagraphBuilder.makeOps(DesktopParagraph.kt:637)
	at androidx.compose.ui.text.platform.ParagraphBuilder.build(DesktopParagraph.kt:521)
	at androidx.compose.ui.text.platform.DesktopParagraphIntrinsics.<init>(DesktopParagraphIntrinsics.kt:67)
	at androidx.compose.ui.text.platform.DesktopParagraphKt.ActualParagraph(DesktopParagraph.kt:88)
	at androidx.compose.ui.text.ParagraphKt.Paragraph(Paragraph.kt:288)
	at androidx.compose.ui.text.ParagraphKt.Paragraph$default(Paragraph.kt:278)
	at androidx.compose.foundation.text.TextFieldDelegateKt.computeSizeForEmptyText(TextFieldDelegate.kt:75)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion.notifyFocusedRect$foundation(TextFieldDelegate.kt:197)
	at androidx.compose.foundation.text.CoreTextFieldKt$CoreTextField-NLzSDI8$$inlined$onGloballyPositioned$1.onGloballyPositioned(OnGloballyPositionedModifier.kt:63)
	at androidx.compose.ui.node.LayoutNode.dispatchOnPositionedCallbacks$ui(LayoutNode.kt:1141)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:53)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:57)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:57)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:57)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:57)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatch(OnPositionedDispatcher.kt:46)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.dispatchOnPositionedCallbacks(MeasureAndLayoutDelegate.kt:254)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.dispatchOnPositionedCallbacks$default(MeasureAndLayoutDelegate.kt:250)
	at androidx.compose.ui.platform.DesktopOwner.measureAndLayout(DesktopOwner.kt:169)
	at androidx.compose.ui.platform.DesktopOwners.onFrame(DesktopOwners.kt:85)
	at androidx.compose.ui.platform.DesktopOwners$onFrame$1.invokeSuspend(DesktopOwners.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

when deleting last symbol from `BasicTextField`
Please, look at this gif to have more info:

![edit_text_fail](https://user-images.githubusercontent.com/46822605/99905689-13686200-2cdb-11eb-8b3e-2f2bd7318f42.gif)

Code of my input composable:
```
@Composable
fun EditText(
        value: String,
        onValueChange: (String) -> Unit,
        error: String? = null,
        errorIcon: String = "error.png",
        onErrorIconClicked: (String) -> Unit = { onErrIconClicked(it) },
        modifier: Modifier = Modifier,
        textStyle: TextStyle = TextStyle.Default,
        maxLines: Int = Int.MAX_VALUE,
        onImeActionPerformed: (ImeAction) -> Unit = {},
        visualTransformation: VisualTransformation = VisualTransformation.None,
        onTextLayout: (TextLayoutResult) -> Unit = {},
        onTextInputStarted: (SoftwareKeyboardController) -> Unit = {},
        cursorColor: Color = Color.Black
) = Row(modifier) {
    BasicTextField(
            value = value,
            onValueChange = onValueChange,
            textStyle = textStyle,
            onImeActionPerformed = onImeActionPerformed,
            visualTransformation = visualTransformation,
            onTextLayout = onTextLayout,
            onTextInputStarted = onTextInputStarted,
            cursorColor = cursorColor,
            maxLines = maxLines,
            modifier = Modifier
                    .border(
                            shape = RoundedCornerShape(size = 4.dp),
                            color = if (error.isNullOrBlank()) Color.Black else Color.Red,
                            width = 2.dp
                    )
                    .padding(start = 8.dp, end = 8.dp, top = 4.dp, bottom = 4.dp)
    )
    if (!error.isNullOrBlank()) {
        Spacer(modifier = Modifier.height(1.dp).width(5.dp))
        Image(imageFromResource(errorIcon),
                modifier = Modifier
                        .width(18.dp)
                        .height(18.dp)
                        .align(alignment = Alignment.CenterVertically)
                        .clickable { onErrorIconClicked(error) }
        )
    }
}
```

**Comment by prepor** [comment]
Thank you for the report! I pushed a CL with a fix https://android-review.googlesource.com/c/platform/frameworks/support/+/1507302

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5600">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
