### ISSUE TITLE
Compose uiTestJUnit4 artifact does not find skia dependency in multiplatform projects

### ISSUE THREAD

**Issue by burnoo** [JetBrains/compose-jb#1352]
Sample project: https://github.com/burnoo/compose-multiplatform-jvmtest-demo/
Compose: `1.0.0`
Kotlin: `1.5.31`
Tested on targets: `linux-x64` ([GitHub Actions logs](https://github.com/burnoo/compose-multiplatform-jvmtest-demo/runs/4094745142?check_suite_focus=true#step:4:613)), `macos-x64` ([GitHub Actions logs](https://github.com/burnoo/compose-multiplatform-jvmtest-demo/runs/4094744835?check_suite_focus=true#step:4:609)), `macos-arm64`

./build.gradle.kts:
```kotlin
import org.jetbrains.compose.compose

plugins {
    kotlin("multiplatform") version "1.5.31"
    id("org.jetbrains.compose") version "1.0.0"
}

kotlin {
    jvm()
    sourceSets {
        named("commonMain") {
            dependencies {
                api(compose.runtime)
            }
        }
        named("jvmTest") {
            dependencies {
                implementation(compose.uiTestJUnit4)
                implementation(compose.material)
            }
        }
        named("jvmMain")
    }
}

//...
```
./src/jvmTest/kotlin/BasicTest.kt:
```kotlin
class BasicTest {
    @get:Rule
    val composeTestRule = createComposeRule()

    @Test
    fun test() {
        composeTestRule.setContent {
            Text("Hello World")
        }

       assertText("Hello World")
    }

    private fun assertText(text: String, index: Int = 0) {
        composeTestRule.onNode(isRoot()).onChildAt(index).assertTextEquals(text)
    }
}
```

After running `./gradlew jvmTest`, tests are crashing with:
```
org.jetbrains.skiko.LibraryLoadException: Cannot find libskiko-linux-x64.so.sha256, proper native dependency missing.
    at org.jetbrains.skiko.Library.load(Library.kt:72)
    at org.jetbrains.skia.impl.Library$Companion.staticLoad(Library.jvm.kt:12)
    at org.jetbrains.skia.Surface.<clinit>(Surface.kt:532)
    ... 3 more
```

## Workaround
Add skia dependency explicitly:
./build.gradle.kts:
```kotlin
kotlin {
    jvm()
    sourceSets {
        // ...
        named("jvmTest") {
            dependencies {
                implementation(compose.uiTestJUnit4)
                implementation(getSkiaDependency()) // WORKAROUND
                implementation(compose.material)
            }
        }
        // ...
    }
}

fun getSkiaDependency() : String {
    val target = getTarget()
    val version = "0.6.7"
    return "org.jetbrains.skiko:skiko-jvm-runtime-$target:$version"
}

fun getTarget(): String {
    val osName = System.getProperty("os.name")
    val targetOs = when {
        osName == "Mac OS X" -> "macos"
        osName.startsWith("Win") -> "windows"
        osName.startsWith("Linux") -> "linux"
        else -> error("Unsupported OS: $osName")
    }

    val targetArch = when (val osArch = System.getProperty("os.arch")) {
        "x86_64", "amd64" -> "x64"
        "aarch64" -> "arm64"
        else -> error("Unsupported arch: $osArch")
    }

    return "${targetOs}-${targetArch}"
}
```

**Comment by robstoll** [comment]
experiencing a similar problem with a non-mulitplatform jetbrains.compose project (jvm only).
Kotlin 1.5.21 and jetbrain.compose 1.0.0-alpha4-build310
The problem appears when running main. It worked a week ago, I guess some incompatibility with ubuntu 20.04 latest updates.

**Comment by akurasov** [comment]
It is expected that jvm sourceSets will have implementation(compose.desktop.currentOs) dependency. It will included necessary skiko library.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5195">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
