### ISSUE TITLE
runDistributable -KotlinLogging exception

### ISSUE THREAD

**Issue by changjinzhuan** [JetBrains/compose-jb#1358]
> Task :createDistributable
The distribution is written to E:\KotlinWorkSpace\BigAmountAPP\build\compose\binaries\main\app

> Task :runDistributable
Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError: javax/naming/NamingException
	at ch.qos.logback.classic.joran.JoranConfigurator.addInstanceRules(JoranConfigurator.java:48)
	at ch.qos.logback.core.joran.GenericConfigurator.buildInterpreter(GenericConfigurator.java:134)
	at ch.qos.logback.core.joran.JoranConfiguratorBase.buildInterpreter(JoranConfiguratorBase.java:95)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:162)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
	at mu.KotlinLogging.logger(KotlinLogging.kt:32)
	at MainKt.<clinit>(Main.kt:40)
Caused by: java.lang.ClassNotFoundException: javax.naming.NamingException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 17 more
Exception in thread "main" java.lang.NoClassDefFoundError: javax/naming/NamingException
	at ch.qos.logback.classic.joran.JoranConfigurator.addInstanceRules(JoranConfigurator.java:48)
	at ch.qos.logback.core.joran.GenericConfigurator.buildInterpreter(GenericConfigurator.java:134)
	at ch.qos.logback.core.joran.JoranConfiguratorBase.buildInterpreter(JoranConfiguratorBase.java:95)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:162)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
	at mu.KotlinLogging.logger(KotlinLogging.kt:32)
	at MainKt.<clinit>(Main.kt:40)
Caused by: java.lang.ClassNotFoundException: javax.naming.NamingException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 17 more
Failed to launch JVM

**Comment by changjinzhuan** [comment]
//Log
    implementation ("org.slf4j:slf4j-api:1.7.32")
    implementation ("ch.qos.logback:logback-core:1.2.6")
    implementation ("ch.qos.logback:logback-classic:1.2.6")
    implementation ("io.github.microutils:kotlin-logging-jvm:2.0.10")

**Comment by changjinzhuan** [comment]
#1154 i see

**Comment by Colerar** [comment]
How did you solve it?  I had the same problem. 
I added `modules("java.compiler", "java.instrument", "java.sql", "jdk.unsupported")` in `nativeDistributions` but not works. 
Also, I try to add `"javax.naming"` to `modules`, but error throwed `Error: Module javax.naming not found`.
🤔 Can you tell me how it solved?

**Comment by Colerar** [comment]
Okay, sorry for disturbing. I fixed it by adding `"java.naming"` to `modules`. I forget that `javax` and `java` are same thing.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5190">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
