### ISSUE TITLE
ClassCastException when importing a JS module

### ISSUE THREAD

**Issue by brianguertin** [JetBrains/compose-jb#1360]
Kotlin 1.5.31
org.jetbrains.compose 1.0.0-alpha4-build398

The following code causes a ClassCastException:
```kotlin
external interface BwipJs {
   fun toCanas(canvas: HTMLCanvasElement)
}
external fun <Module : Any> import(path: String): Promise<Module>

@Composable
fun Barcode() {
  val bwip = remember { mutableStateOf<BwipJs?>(null) }
  LaunchedEffect(Unit) {
    bwip.value = import<BwipJs>("bwip-js").await() // ClassCastException
  }
}
```

While this code in plain Kotlin/JS works just fine:
```kotlin
val canvas = document.createElement("canvas") as HTMLCanvasElement
import<BwipJs>("bwip-js").then { bwipjs ->
    bwipjs.toCanvas(canvas)
}
```

I suspect the issue would be the same regardless of what JS module is being loaded, but in this case I'm using https://github.com/metafloor/bwip-js

```
ClassCastException
    at THROW_CCE (webpack-internal:///./kotlin/combined-jgosdk.js:32134:11)
    at toState (webpack-internal:///./kotlin/combined-jgosdk.js:37552:87)
    at CancellableContinuationImpl.resumeWith_bnunh2_k$ (webpack-internal:///./kotlin/combined-jgosdk.js:37052:15)
    at _no_name_provided__129.invoke_iav7o_k$ (webpack-internal:///./kotlin/combined-jgosdk.js:53075:44)
    at eval (webpack-internal:///./kotlin/combined-jgosdk.js:53114:9)
```

**Comment by brianguertin** [comment]
Further investigating this, it seems to be a bug in kotlinx coroutines, not Compose specifically. I'll file over there...

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5188">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
