### ISSUE TITLE
Kotlin: [Internal Error] java.lang.IllegalStateException: The provided plugin androidx.compose.compiler.plugins.kotlin.ComposeComponentRegistrar is not compatible with this version of compiler

### ISSUE THREAD

**Issue by JacobLoveCode** [JetBrains/compose-jb#1443]
**I created a new project of Compose for Desktop by IntelliJ  and do nothing changes, It can work well by click run button, but when I export a jar file this error was came to me.  
I upgrade last new version of kotlin plugin but it still in there . 
Please help me to figure out this error .
Thank you very much.**

```
Kotlin: [Internal Error] java.lang.IllegalStateException: The provided plugin androidx.compose.compiler.plugins.kotlin.ComposeComponentRegistrar is not compatible with this version of compiler
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli(KotlinCoreEnvironment.kt:675)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.registerExtensionsFromPlugins(KotlinCoreEnvironment.kt:169)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:216)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:111)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:485)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:227)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:153)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1542)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.AbstractMethodError: Receiver class androidx.compose.compiler.plugins.kotlin.ComposeComponentRegistrar does not define or inherit an implementation of the resolved method 'abstract void registerProjectComponents(com.intellij.mock.MockProject, org.jetbrains.kotlin.config.CompilerConfiguration)' of interface org.jetbrains.kotlin.compiler.plugin.ComponentRegistrar.
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli(KotlinCoreEnvironment.kt:667)
	... 28 more


```

**Comment by akurasov** [comment]
Hello! 

What do you mean by export . jar file? Build jar file and run it via java -jar? 

What is your OS and IDEA?

**Comment by JacobLoveCode** [comment]
> Hello!
> 
> What do you mean by export . jar file? Build jar file and run it via java -jar?
> 
> What is your OS and IDEA?


Yes . Build a jar file. But it throw this error when I was building.

My OS is Monterey(M1) ， ItelliJ IDEA is 2021.2 and on windows also has this error .

**Comment by JacobLoveCode** [comment]
@akurasov 

Yes . Build a jar file. But it throw this error when I was building.

My OS is Monterey(M1) ， ItelliJ IDEA is 2021.2 and on windows also has this error .

**Comment by akurasov** [comment]
@JacobLoveCode what was the issue? So others could use your solution

**Comment by JacobLoveCode** [comment]
> @JacobLoveCode what was the issue? So others could use your solution

Silly me. I should use the gradle tool to package a dmg file rather than use the IntelliJ IDEA's Artifcats to build a jar file. 
and thanks for your attention.

**Comment by JacobLoveCode** [comment]
> @JacobLoveCode what was the issue? So others could use your solution

Silly me. I should use the gradle tool to package a dmg file rather than use the IntelliJ IDEA's Artifcats to build a jar file.
And thanks for your attention.

<img width="327" alt="图片" src="https://user-images.githubusercontent.com/93966926/143400003-82c6bfe8-30e0-4fa4-8ec4-243688a94f5d.png">

**Comment by adriantache** [comment]
After much Googling, I was able to solve this by adding this block to the `compose.desktop` config. Be aware that the version for this compiler is not the same as the one for Android...

```
compose.desktop {
    compose {
        kotlinCompilerPlugin.set("androidx.compose.compiler:compiler:1.5.10")
    }

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5172">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
