### ISSUE TITLE
Can't run web examples

### ISSUE THREAD

**Issue by gnawf** [JetBrains/compose-jb#1454]
I'm getting the following stacktraces when running `jsBrowserRun` on the `web-landing` and `falling-balls-web` modules.

```
java.lang.IllegalStateException: Could not find "org.jetbrains.kotlinx:kotlinx-coroutines-core" in [/Users/fwang/Library/Application Support/kotlin/daemon]
	at org.jetbrains.kotlin.cli.js.K2JsIrCompilerKt$messageCollectorLogger$1.fatal(K2JsIrCompiler.kt:539)
	at org.jetbrains.kotlin.library.KotlinLibrarySearchPathResolver.resolve(SearchPathResolver.kt:175)
	at org.jetbrains.kotlin.library.SearchPathResolver$DefaultImpls.resolve$default(SearchPathResolver.kt:20)
	at org.jetbrains.kotlin.library.SearchPathResolverKt.resolve(SearchPathResolver.kt:29)
	at org.jetbrains.kotlin.library.resolver.impl.KotlinLibraryResolverImpl$resolveDependencies$2$2.invoke(KotlinLibraryResolverImpl.kt:122)
	at org.jetbrains.kotlin.library.resolver.impl.KotlinLibraryResolverImpl$resolveDependencies$2$2.invoke(KotlinLibraryResolverImpl.kt:122)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
	at org.jetbrains.kotlin.library.resolver.impl.KotlinLibraryResolverImpl.resolveDependencies(KotlinLibraryResolverImpl.kt:135)
	at org.jetbrains.kotlin.library.resolver.impl.KotlinLibraryResolverImpl.resolveWithDependencies(KotlinLibraryResolverImpl.kt:44)
	at org.jetbrains.kotlin.ir.backend.js.JsLibraryResolverKt.jsResolveLibraries(JsLibraryResolver.kt:53)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:186)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:182)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:75)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:191)
	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:77)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:358)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally$default(IncrementalCompilerRunner.kt:300)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl$rebuild(IncrementalCompilerRunner.kt:119)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:170)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:81)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile$default(IncrementalCompilerRunner.kt:72)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execJsIncrementalCompiler(CompileServiceImpl.kt:550)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execJsIncrementalCompiler(CompileServiceImpl.kt:96)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1745)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
I haven't modified the projects at all, I just cloned them and tried to run them using IntelliJ Ultimate 2021.2.3

The `/Users/fwang/Library/Application Support/kotlin/daemon` directory is empty.

Creating a new project following https://github.com/JetBrains/compose-jb/tree/master/tutorials/Web/Getting_Started doesn't work either.

Edit, HEAD on my local clone is fe03732d3bff6d475c8b63693c9d9f969255dc44

**Comment by gnawf** [comment]
Ok so I did a little more digging and I found

https://youtrack.jetbrains.com/issue/KT-43500 but the solution here doesn't work, I've tried

```diff
$ git diff .   
diff --git a/templates/web-template/build.gradle.kts b/templates/web-template/build.gradle.kts
index ae1ee33..93254c3 100644
--- a/templates/web-template/build.gradle.kts
+++ b/templates/web-template/build.gradle.kts
@@ -26,6 +26,7 @@ kotlin {
             resources.srcDir("src/main/resources")
 
             dependencies {
+                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2")
                 implementation(compose.web.core)
                 implementation(compose.runtime)
             }
```

which doesn't work.

I also found https://youtrack.jetbrains.com/issue/KTIJ-18321 but the only suggestion here is switching to the LEGACY compiler which isn't an option.

I tried upgrading to Kotlin 1.6.0 to see if upgrading the compiler could fix it, but Compose errors out saying

> e: This version (1.1.0-beta01) of the Compose Compiler requires Kotlin version 1.5.31 but you appear to be using Kotlin version 1.6.0 which is not known to be compatible.  Please fix your configuration (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).

I tried

```diff
diff --git a/templates/web-template/build.gradle.kts b/templates/web-template/build.gradle.kts
index ae1ee33..d6e2cba 100644
--- a/templates/web-template/build.gradle.kts
+++ b/templates/web-template/build.gradle.kts
@@ -4,9 +4,9 @@ import org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootExtension
 
 plugins {
     // __KOTLIN_COMPOSE_VERSION__
-    kotlin("multiplatform") version "1.5.31"
+    kotlin("multiplatform") version "1.6.0"
     // __LATEST_COMPOSE_RELEASE_VERSION__
-    id("org.jetbrains.compose") version ("1.0.0-beta5")
+    id("org.jetbrains.compose") version ("1.0.0-rc3")
 }
 
 repositories {
@@ -39,5 +39,12 @@ afterEvaluate {
         versions.webpackDevServer.version = "4.0.0"
         versions.webpackCli.version = "4.9.0"
     }
-}
 
+    tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
+        kotlinOptions {
+            freeCompilerArgs += listOf(
+                "-P", "plugin:androidx.compose.compiler.plugins.kotlin:suppressKotlinVersionCompatibilityCheck=true"
+            )
+        }
+    }
+}
```

And the `suppressKotlinVersionCompatibilityCheck` bypass doesn't seem to work, so no luck running with Kotlin 1.6.0

**Comment by eymar** [comment]
looks weird. Couldn't reproduce unfortunately.
Could you please check if it can build any other kotlin/js project? for example https://github.com/kotlin-hands-on/web-app-react-kotlin-js-gradle

**Comment by gnawf** [comment]
Ok I ended up deleting my `~/.gradle` directory and that seems to have done the trick. No idea why, but it works now.

For what it's worth, I was able to run the repo you linked above, before I wiped my `.gradle` directory.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5166">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
