### ISSUE TITLE
Cannot convert bitmap to buffered image

### ISSUE THREAD

**Issue by wakaztahir** [JetBrains/compose-jb#1661]
My Code 

```kotlin
    val bitmap = Bitmap()
    bitmap.setImageInfo(ImageInfo(this.size.width.toInt(),this.size.height.toInt(),colorType = ColorType.ARGB_4444,alphaType = ColorAlphaType.UNKNOWN))
    if(!bitmap.allocPixels()){
        println("Couldn't allocate pixels for the image")
    }

    if(this.drawContext.canvas.nativeCanvas.readPixels(bitmap,0,0)){
        println("Couldn't read pixels from the canvas")
    }
    val data = bitmap.toBufferedImage().toImage().encodeToData()
    val randFile = File.createTempFile(UUID.randomUUID().toString(), ".png")
    if(data!=null) {
        randFile.writeBytes(data.bytes)
    }else{
        println("Data returned null")
    }
    return randFile
```

I don't know if I am doing something wrong , I get a null pointer exception 

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.jetbrains.skiko.Convertors_jvmKt.toBufferedImage(Convertors.jvm.kt:26)
	at com.wakaztahir.tlui.screens.RememberSketchSaveLauncherKt$rememberSketchSaveLauncher$1.saveToFile(rememberSketchSaveLauncher.kt:29)
	at com.wakaztahir.tlui.screens.SketchScreenKt$SketchScreen$1$4.invoke(SketchScreen.kt:60)
	at com.wakaztahir.tlui.screens.SketchScreenKt$SketchScreen$1$4.invoke(SketchScreen.kt:56)
	at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:101)
	at androidx.compose.ui.node.ModifiedDrawNode.performDraw(ModifiedDrawNode.kt:102)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:255)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:98)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:255)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:69)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:255)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:69)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:255)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:837)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:141)
	at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:267)
	at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:266)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1798)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:121)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:88)
	at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:266)
	at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:59)
	at androidx.compose.ui.platform.SkiaLayer.performDrawLayer(SkiaLayer.skiko.kt:264)
	at androidx.compose.ui.platform.SkiaLayer.drawLayer(SkiaLayer.skiko.kt:222)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:250)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:837)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:141)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:255)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:69)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:255)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:69)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:255)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:69)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:255)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:69)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:255)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:69)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:255)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:69)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:255)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:837)
	at androidx.compose.ui.platform.SkiaBasedOwner.draw(SkiaBasedOwner.skiko.kt:336)
	at androidx.compose.ui.platform.SkiaBasedOwner.render(SkiaBasedOwner.skiko.kt:236)
	at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:354)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:224)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:222)
	at androidx.compose.ui.awt.ComposeLayer.catchExceptions(ComposeLayer.desktop.kt:89)
	at androidx.compose.ui.awt.ComposeLayer.access$catchExceptions(ComposeLayer.desktop.kt:70)
	at androidx.compose.ui.awt.ComposeLayer$1.onRender(ComposeLayer.desktop.kt:222)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.jvm.kt:433)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer.update(Direct3DRedrawer.kt:56)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer.access$update(Direct3DRedrawer.kt:12)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invokeSuspend(Direct3DRedrawer.kt:30)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invoke(Direct3DRedrawer.kt)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invoke(Direct3DRedrawer.kt)
	at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
The error is due to this peakpixels() method which is returning null causing null pointer exception as you can see
![Screenshot 2022-01-02 204108](https://user-images.githubusercontent.com/42442700/147888934-4e5393b8-1602-4658-a2fd-ca4de9f39438.png)

**Comment by denchic45** [comment]
Have you solved this problem? I am facing the same problem

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1661">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
