### ISSUE TITLE
kotlin.Result in Compose

### ISSUE THREAD

**Issue by alialbaali** [JetBrains/compose-jb#189]
There seems to be an issue when using kotlin.Result with Compose.
by running the code below, the first call will work and print "success", however the second will throw an exception.

```kotlin
public suspend fun main() {
    getImage()
        .fold(
            onSuccess = { println("success") },
            onFailure = { println("failure") }
        )
    Window {
        LaunchedEffect(null) {
            getImage()
                .fold(
                    onSuccess = { println("success") },
                    onFailure = { println("failure") }
                )
        }
    }
}
public suspend fun getImage(): Result<ByteReadChannel> = runCatching<ByteReadChannel> {
    client.get<ByteReadChannel>("https://i.redd.it/22bexa3ozc461.png")
}
```

Output:
```
success
Exception in thread "AWT-EventQueue-0 @coroutine#9" java.lang.ClassCastException: kotlin.Result incompatible with io.ktor.utils.io.ByteReadChannel
	at MainKt$main$4$1$1.invokeSuspend(main.kt:84)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by olonho** [comment]
Seems this is an issue with ktor/coroutines/API misuse, there's even no Compose code in the backtrace.

**Comment by alialbaali** [comment]
I've managed to make a reproducer.

```kotlin
class ResultFetcher {
    suspend fun fetch(url: Url): Result<ByteReadChannel> = runCatching {
        HttpClient().get(url)
    }
}

suspend fun main() {
    val data = "https://images.wallpaperscraft.com/image/roses_colorful_rainbow_120036_3840x2160.jpg"

    val url = Url(data)
    coroutineScope {
        launch {
            ResultFetcher().fetch(url)
                .getOrThrow()
                .also { println(it.readByte()) }
                .also(::println)
        }
    }

}
```
with this gradle config
```kotlin
plugins {
    kotlin("jvm") version "1.4.21"
    id("org.jetbrains.compose") version "0.3.0-build141"
}

repositories {
    maven { url = uri("https://maven.pkg.jetbrains.space/public/p/compose/dev") }
    mavenLocal()
    jcenter()
    maven { url = uri("https://kotlin.bintray.com/ktor") }
}

dependencies {
    implementation(compose.desktop.currentOs)
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.21")
    implementation("io.ktor:ktor-client-core:1.5.0")
    implementation("io.ktor:ktor-client-core-jvm:1.5.0")
    implementation("io.ktor:ktor-client-apache:1.5.0")
}


kotlin {
    target {
        compilations.all {
            kotlinOptions {
                jvmTarget = "11"
                freeCompilerArgs = listOf("-Xallow-result-return-type")
            }
        }
    }
}

 
```

if you try to remove the compose plugin and the dependency it'll compile just fine.
if you keep them it'll throw the exception
if you keep them and you remove launching new coroutine like this, it'll compile with no problems.

```kotlin 

  ResultFetcher().fetch(url)
                .getOrThrow()
                .also { println(it.readByte()) }
                .also(::println)
                
```

so It basically happens when launching a new coroutine when compose enabled.

OS : Windows 10 20H2
JDK : 11
Kotlin Version : 1.4.21
Ktor version : 1.5.0

**Comment by akurasov** [comment]
@olonho could it be the compiler plugin issue?

**Comment by akurasov** [comment]
Both examples work fine with 1.0.0-alpha4-build348. Seems the issue was fixed, whatever it had been.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6293">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
