### ISSUE TITLE
"Module with the Main dispatcher is missing" after update to v1.1.1

### ISSUE THREAD

**Issue by AshStefanOltmann** [JetBrains/compose-jb#1954]
After updating from version 1.1.0 to 1.1.1 I get this error:

```
Exception in thread "main @coroutine#1" java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core'
	at kotlinx.coroutines.internal.MainDispatchersKt.throwMissingMainDispatcherException(MainDispatchers.kt:81)
	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:115)
	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:96)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:319)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.startCoroutineImpl(Builders.common.kt:192)
	at kotlinx.coroutines.BuildersKt.startCoroutineImpl(Unknown Source)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:134)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
```

This code is the first call:
```
        launch {

            photoSyncService.observeState().collect { photoSyncState ->
                dispatch(PhotoAction.SyncStateUpdate(photoSyncState))
            }
        }
```

This is my dependency definition:
```
    val commonMain by sourceSets.getting {

        dependencies {

            api("org.jetbrains.kotlinx:kotlinx-coroutines-core") {
                version {
                    strictly("1.6.0-native-mt")
                }
            }

            // other stuff
        }
    }
```

If I flip it back to version 1.1.0 everything works fine.

What changed?

**Comment by mcpiroman** [comment]
Does [release notes/API Changes](https://github.com/JetBrains/compose-jb/releases/tag/v1.1.1) not answer that?

**Comment by AshStefanOltmann** [comment]
@mcpiroman Yes, that was the problem. Thank you!

I didn't read the release notes because I didn't expect necessary migration steps on a patch level update. ^^

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1954">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
