### ISSUE TITLE
1.1.1 causes crash when pressing a button

### ISSUE THREAD

**Issue by xdevs23** [JetBrains/compose-jb#1989]
I upgraded to Compose 1.1.1 and Kotlin 1.6.10.

I am using Compose Desktop (not multiplatform) on JVM

On Windows and Linux clicking any button yields following error:
```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: 'boolean androidx.compose.ui.input.pointer.PointerEvent_skikoKt.isPrimaryPressed-aHzCx-E(int)'
	at androidx.compose.foundation.gestures.TapGestureDetectorKt.isPrimaryButton(TapGestureDetector.kt:259)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt.awaitFirstDownOnPass(TapGestureDetector.kt:251)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$awaitFirstDownOnPass$1.invokeSuspend(TapGestureDetector.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:511)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:406)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:419)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:310)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:297)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:297)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:297)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:179)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:98)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:80)
	at androidx.compose.ui.platform.SkiaBasedOwner.doProcessPointerInput-8iAsVTc(SkiaBasedOwner.skiko.kt:401)
	at androidx.compose.ui.platform.SkiaBasedOwner.processPointerInput-8iAsVTc$ui(SkiaBasedOwner.skiko.kt:397)
	at androidx.compose.ui.ComposeScene.onMousePressed(ComposeScene.skiko.kt:421)
	at androidx.compose.ui.ComposeScene.sendPointerEvent-Kr8mkKM(ComposeScene.skiko.kt:403)
	at androidx.compose.ui.ComposeScene.sendPointerEvent-Kr8mkKM$default(ComposeScene.skiko.kt:369)
	at androidx.compose.ui.awt.ComposeLayer_desktopKt.onMouseEvent(ComposeLayer.desktop.kt:263)
	at androidx.compose.ui.awt.ComposeLayer_desktopKt.access$onMouseEvent(ComposeLayer.desktop.kt:1)
	at androidx.compose.ui.awt.ComposeLayer.onMouseEvent(ComposeLayer.desktop.kt:197)
	at androidx.compose.ui.awt.ComposeLayer.access$onMouseEvent(ComposeLayer.desktop.kt:59)
	at androidx.compose.ui.awt.ComposeLayer$3.mousePressed(ComposeLayer.desktop.kt:174)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Looking at the source code, in the `commonMain` source set, it expects `isPrimaryPressed`: https://github.com/JetBrains/androidx/blob/5dccc825fe4c5a5403e5313c5da9e5cb9ca16ab3/compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/input/pointer/PointerEvent.kt#L153

However, PointerEvent.desktop.kt does not exist in the `desktopMain` source set in the androidx revision referenced by v1.1.1: https://github.com/JetBrains/androidx/tree/5dccc825fe4c5a5403e5313c5da9e5cb9ca16ab3/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/input/pointer

It is defined for android here: https://github.com/JetBrains/androidx/blob/5dccc825fe4c5a5403e5313c5da9e5cb9ca16ab3/compose/ui/ui/src/androidMain/kotlin/androidx/compose/ui/input/pointer/PointerEvent.android.kt#L118=

In the jb-main branch, it does exist: https://github.com/JetBrains/androidx/blob/43679cfb8920e83e39ebece75ae99f6b6ea5ad62/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/input/pointer/PointerEvent.desktop.kt

Could you please release a new Compose version with a newer version of androidx that has this fixed? The current 1.1.1 version is broken on Desktop.

**Comment by xdevs23** [comment]
Workaround is to upgrade to `1.2.0-alpha01-dev620`.

**Comment by igordmn** [comment]
Could you please perform these commands:
```
./gradlew dependencyInsight --dependency org.jetbrains.compose.ui:ui-desktop
./gradlew dependencyInsight --dependency org.jetbrains.compose.foundation:foundation-desktop
```

and post here the output.

This crash can happen, if some library uses Compose 1.2. Compose 1.2 still isn't backward compatible with 1.1 (but it will be in the near future).

**Comment by xdevs23** [comment]
Sorry for the delay, was quite busy.

`./gradlew dependencyInsight --dependency org.jetbrains.compose.ui:ui-desktop`

```
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :dependencyInsight
org.jetbrains.compose.ui:ui-desktop:1.2.0-alpha01-dev620
   variant "desktopApiElements-published" [
      org.gradle.category                = library
      org.gradle.libraryelements         = jar (compatible with: classes)
      org.gradle.usage                   = java-api
      org.jetbrains.kotlin.platform.type = jvm
      org.gradle.status                  = release (not requested)

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling     = external
         org.gradle.jvm.environment         = standard-jvm
         org.gradle.jvm.version             = 17
   ]

org.jetbrains.compose.ui:ui-desktop:1.2.0-alpha01-dev620
\--- org.jetbrains.compose.ui:ui:1.2.0-alpha01-dev620
     +--- org.jetbrains.compose.desktop:desktop-jvm:1.1.1 (requested org.jetbrains.compose.ui:ui:1.1.1)
     |    \--- org.jetbrains.compose.desktop:desktop:1.1.1
     |         \--- org.jetbrains.compose.desktop:desktop-jvm-linux-x64:1.1.1
     |              \--- compileClasspath
     +--- org.jetbrains.compose.material:material-desktop:1.1.1 (requested org.jetbrains.compose.ui:ui:1.1.1)
     |    \--- org.jetbrains.compose.material:material:1.1.1
     |         \--- org.jetbrains.compose.desktop:desktop-jvm:1.1.1 (*)
     +--- org.jetbrains.compose.foundation:foundation-desktop:1.1.1 (requested org.jetbrains.compose.ui:ui:1.1.1)
     |    \--- org.jetbrains.compose.foundation:foundation:1.1.1
     |         +--- org.jetbrains.compose.desktop:desktop-jvm:1.1.1 (*)
     |         +--- org.jetbrains.compose.material:material-desktop:1.1.1 (*)
     |         \--- org.jetbrains.compose.material:material-ripple-desktop:1.1.1
     |              \--- org.jetbrains.compose.material:material-ripple:1.1.1
     |                   \--- org.jetbrains.compose.material:material-desktop:1.1.1 (*)
     +--- org.jetbrains.compose.animation:animation-desktop:1.1.1 (requested org.jetbrains.compose.ui:ui:1.1.1)
     |    \--- org.jetbrains.compose.animation:animation:1.1.1
     |         \--- org.jetbrains.compose.foundation:foundation-desktop:1.1.1 (*)
     +--- org.jetbrains.compose.material:material-icons-core-desktop:1.2.0-alpha01-dev620
     |    \--- org.jetbrains.compose.material:material-icons-core:1.2.0-alpha01-dev620
     |         +--- org.jetbrains.compose.material:material-desktop:1.1.1 (requested org.jetbrains.compose.material:material-icons-core:1.1.1) (*)
     |         \--- org.jetbrains.compose.material:material-icons-extended-desktop:1.2.0-alpha01-dev620
     |              \--- org.jetbrains.compose.material:material-icons-extended:1.2.0-alpha01-dev620
     |                   \--- compileClasspath
     \--- org.jetbrains.compose.foundation:foundation-layout-desktop:1.1.1 (requested org.jetbrains.compose.ui:ui:1.1.1)
          \--- org.jetbrains.compose.foundation:foundation-layout:1.1.1
               \--- org.jetbrains.compose.animation:animation-desktop:1.1.1 (*)

(*) - dependencies omitted (listed previously)

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 8s
1 actionable task: 1 executed
```

`./gradlew dependencyInsight --dependency org.jetbrains.compose.foundation:foundation-desktop`

```

> Task :dependencyInsight
org.jetbrains.compose.foundation:foundation-desktop:1.1.1
   variant "desktopApiElements-published" [
      org.gradle.category                = library
      org.gradle.libraryelements         = jar (compatible with: classes)
      org.gradle.usage                   = java-api
      org.jetbrains.kotlin.platform.type = jvm
      org.gradle.status                  = release (not requested)

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling     = external
         org.gradle.jvm.environment         = standard-jvm
         org.gradle.jvm.version             = 17
   ]

org.jetbrains.compose.foundation:foundation-desktop:1.1.1
\--- org.jetbrains.compose.foundation:foundation:1.1.1
     +--- org.jetbrains.compose.desktop:desktop-jvm:1.1.1
     |    \--- org.jetbrains.compose.desktop:desktop:1.1.1
     |         \--- org.jetbrains.compose.desktop:desktop-jvm-linux-x64:1.1.1
     |              \--- compileClasspath
     +--- org.jetbrains.compose.material:material-desktop:1.1.1
     |    \--- org.jetbrains.compose.material:material:1.1.1
     |         \--- org.jetbrains.compose.desktop:desktop-jvm:1.1.1 (*)
     \--- org.jetbrains.compose.material:material-ripple-desktop:1.1.1
          \--- org.jetbrains.compose.material:material-ripple:1.1.1
               \--- org.jetbrains.compose.material:material-desktop:1.1.1 (*)

(*) - dependencies omitted (listed previously)

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
```

Looks like you're right. Following dependency is 1.2.0:

```
    implementation("org.jetbrains.compose.material:material-icons-extended:1.2.0-alpha01-dev620")
``

Changing it to 1.1.1 solves the issue. I wonder why it worked on 1.0.0 and why not on 1.1.1 even though the 1.2.0 dependency was being used.
If semver is used, 1.1.1 should not crash when 1.0.0 didn't given the same circumstances. Or am I missing something here?

I'll consider this specific issue solved, and since you said compatibility will come in the future, I'll close the issue.

Thank you very much!

**Comment by igordmn** [comment]
>  Changing it to 1.1.1 solves the issue. I wonder why it worked on 1.0.0 and why not on 1.1.1 even though the 1.2.0 dependency was being used.

foundation 1.1 depends on method, which exists in ui 1.1, but doesn't exist in ui 1.0/1.2
if you downgrade foundation to 1.0, it will no longer depend on this method, and everything will compile fine.

**Comment by xdevs23** [comment]
> Please check the [following ticket](https://youtrack.jetbrains.com/issue/CMP-1989) on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

Cool, thanks.

I liked GitHub issues a lot more, though.
