### ISSUE TITLE
NoSuchMethodError JvmIrUtilsKt.isInlineParameter while compiling for iOS

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-jb#2007]
Hello. I'm playing with the new Darwin targets of Compose and Decompose. It builds locally just fine on my MacBook Air M1. However the build fails on CI (GitHub Actions). Because of that I couldn't find the causing code yet.

Kotlin version: `1.6.10`
Compose version: `1.2.0-alpha01-dev662`
CI run: [link](https://github.com/arkivanov/Decompose/runs/6033023973)

I have fixed a branch for this crash: [compose-ios-crash-1](https://github.com/arkivanov/Decompose/tree/compose-ios-crash-1)

Error message:

```
e: java.lang.NoSuchMethodError: 'boolean org.jetbrains.kotlin.backend.jvm.ir.JvmIrUtilsKt.isInlineParameter(org.jetbrains.kotlin.ir.declarations.IrValueParameter)'
```

<details>
  <summary>Stack trace</summary>
  
```
> Task :extensions-compose-jetbrains:compileKotlinIosArm64
e: Compilation failed: 'boolean org.jetbrains.kotlin.backend.jvm.ir.JvmIrUtilsKt.isInlineParameter(org.jetbrains.kotlin.ir.declarations.IrValueParameter)'

 * Source files: Children.kt, SubscribeAsState.kt, ChildAnimation.kt, ChildAnimator.kt, DefaultChildAnimation.kt, DefaultChildAnimator.kt, Direction.kt, EmptyChildAnimation.kt, Fade.kt, Scale.kt, Slide.kt, LifecycleComposableBuilder.kt
 * Compiler version info: Konan: 1.6.10 / Kotlin: 1.6.10
 * Output kind: LIBRARY

e: java.lang.NoSuchMethodError: 'boolean org.jetbrains.kotlin.backend.jvm.ir.JvmIrUtilsKt.isInlineParameter(org.jetbrains.kotlin.ir.declarations.IrValueParameter)'
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitFunctionAccess(IrInlineReferenceLocator.kt:72)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitFunctionAccess(IrInlineReferenceLocator.kt:39)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitCall(IrElementVisitor.kt:77)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitCall(IrInlineReferenceLocator.kt:39)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitCall(IrInlineReferenceLocator.kt:39)
	at org.jetbrains.kotlin.ir.expressions.impl.IrCallImpl.accept(IrCallImpl.kt:47)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.acceptChildren(IrBody.kt:57)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitElement(IrInlineReferenceLocator.kt:42)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitElement(IrInlineReferenceLocator.kt:39)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitBody(IrElementVisitor.kt:46)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitBody(IrInlineReferenceLocator.kt:39)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitBody(IrInlineReferenceLocator.kt:39)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitBlockBody(IrElementVisitor.kt:48)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitBlockBody(IrInlineReferenceLocator.kt:39)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitBlockBody(IrInlineReferenceLocator.kt:39)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBody.kt:54)
	at org.jetbrains.kotlin.ir.declarations.IrFunction.acceptChildren(IrFunction.kt:58)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitDeclaration(IrInlineReferenceLocator.kt:47)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitDeclaration(IrInlineReferenceLocator.kt:39)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitFunction(IrElementVisitor.kt:33)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitFunction(IrInlineReferenceLocator.kt:39)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitFunction(IrInlineReferenceLocator.kt:39)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitSimpleFunction(IrElementVisitor.kt:34)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitSimpleFunction(IrInlineReferenceLocator.kt:39)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitSimpleFunction(IrInlineReferenceLocator.kt:39)
	at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:28)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.acceptChildren(IrFileImpl.kt:84)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitElement(IrInlineReferenceLocator.kt:42)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitElement(IrInlineReferenceLocator.kt:39)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitPackageFragment(IrElementVisitor.kt:26)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitPackageFragment(IrInlineReferenceLocator.kt:39)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitPackageFragment(IrInlineReferenceLocator.kt:39)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitFile(IrElementVisitor.kt:27)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitFile(IrInlineReferenceLocator.kt:39)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitFile(IrInlineReferenceLocator.kt:39)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.accept(IrFileImpl.kt:81)
	at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.acceptChildren(IrModuleFragmentImpl.kt:40)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitElement(IrInlineReferenceLocator.kt:42)

	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitElement(IrInlineReferenceLocator.kt:39)
> Task :extensions-compose-jetbrains:compileKotlinIosArm64 FAILED
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitModuleFragment(IrElementVisitor.kt:25)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitModuleFragment(IrInlineReferenceLocator.kt:39)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator.visitModuleFragment(IrInlineReferenceLocator.kt:39)
	at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.accept(IrModuleFragmentImpl.kt:37)
	at androidx.compose.compiler.plugins.kotlin.lower.IrInlineReferenceLocator$Companion.scan(IrInlineReferenceLocator.kt:124)
	at androidx.compose.compiler.plugins.kotlin.lower.AbstractComposeLowering.lower(AbstractComposeLowering.kt:176)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposerLambdaMemoization.lower(ComposerLambdaMemoization.kt:375)
	at androidx.compose.compiler.plugins.kotlin.ComposeIrGenerationExtension.generate(ComposeIrGenerationExtension.kt:126)
	at org.jetbrains.kotlin.backend.konan.PsiToIrKt.psiToIr$lambda-14(PsiToIr.kt:173)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:88)
	at org.jetbrains.kotlin.backend.konan.PsiToIrKt.psiToIr(PsiToIr.kt:178)
	at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$psiToIrPhase$1.invoke(ToplevelPhases.kt:119)
	at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$psiToIrPhase$1.invoke(ToplevelPhases.kt:117)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:96)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:94)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:29)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:43)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:34)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:81)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:37)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:76)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:45)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:227)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit$default(CLITool.kt:225)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:214)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:380)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:379)
	at org.jetbrains.kotlin.util.UtilKt.profileIf(Util.kt:22)
	at org.jetbrains.kotlin.util.UtilKt.profile(Util.kt:16)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:379)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:633)
	at org.jetbrains.kotlin.cli.utilities.MainKt$main$1.invoke(main.kt:60)
	at org.jetbrains.kotlin.cli.utilities.MainKt$main$1.invoke(main.kt:60)
	at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:17)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:60)
```
</details>

**Comment by zeruth** [comment]
I think you may need to update your Compose compiler:
https://github.com/arkivanov/Decompose/blob/7608f66f63ebf39254501593fc0ac819dca1ee17/deps.versions.toml#L11

Kotlin 1.6.10 was supported starting at 1.2.0 as shown in:
https://developer.android.com/jetpack/androidx/releases/compose-compiler

**Comment by arkivanov** [comment]
@zeruth That version definition `jetpackComposeCompiler` is for Jetpack Compose, which is used by `extensions-compose-jetpack` module. However the error in question happens while compiling the `extensions-compose-jetbrains` module. Anyway, I tried updating Jetpack Compose version to `1.2.0-alpha07` and the error is still there.

**Comment by zeruth** [comment]
hmmm. strange. This error usually occurs with a mismatching compose / kotlin configuration.

**Comment by hfhbd** [comment]
I can reproduce the same error with js (html dom api), kotlin `1.6.20` and compose-jb `1.2.0-alpha01-dev667`:
[chartJS-compose.zip](https://github.com/JetBrains/compose-jb/files/8514270/chartJS-compose.zip)

**Comment by IlyaGulya** [comment]
I have the same issue with experimental sample https://github.com/JetBrains/compose-jb/tree/master/experimental/examples/minesweeper
I'm trying to compile on Macbook Air M1. Xcode 13.3.1.
https://gist.github.com/IlyaGulya/5fb6df7ec5cf804b0269868402df1838

**Comment by IlyaGulya** [comment]
UPD: Problem is gone with kotlin `1.6.20` and compose-jb `0.0.0-on-rebase-12-apr-2022-dev668`

**Comment by arkivanov** [comment]
Yes, `0.0.0-on-rebase-12-apr-2022-dev668` works

**Comment by arkivanov** [comment]
Works fine with `1.2.0-alpha01-dev675`, thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2007">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
