### ISSUE TITLE
1.2.0-alpha01-dev667: Build fails (js/desktop/android): java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-jb#2019]
```kt
plugins {
    kotlin("multiplatform") version "1.6.20"
    id("org.jetbrains.compose") version "1.2.0-alpha01-dev667"
}
```
JS only project (reproducer untitled1.zip): `./gradlew assemble`

android/desktop project (reproducer untitled2.zip):
android/desktop: `./gradlew assemble`

Stacktrace for all builds (js/android/desktop) is always the same
```
java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.ir.declarations.impl.IrFunctionImpl.<init>(int, int, org.jetbrains.kotlin.ir.declarations.IrDeclarationOrigin, org.jetbrains.kotlin.ir.symbols.IrSimpleFunctionSymbol, org.jetbrains.kotlin.name.Name, org.jetbrains.kotlin.descriptors.DescriptorVisibility, org.jetbrains.kotlin.descriptors.Modality, org.jetbrains.kotlin.ir.types.IrType, boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean, org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedContainerSource)'
	at androidx.compose.compiler.plugins.kotlin.lower.ComposerParamTransformer.copy(ComposerParamTransformer.kt:374)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposerParamTransformer.copy$default(ComposerParamTransformer.kt:367)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposerParamTransformer.copyWithComposerParam(ComposerParamTransformer.kt:502)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposerParamTransformer.withComposerParamIfNeeded(ComposerParamTransformer.kt:351)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposerParamTransformer.visitFunction(ComposerParamTransformer.kt:155)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:72)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:73)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:28)
	at org.jetbrains.kotlin.ir.IrElement$DefaultImpls.transform(IrElement.kt:32)
	at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:19)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.transformChildren(IrFileImpl.kt:89)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitPackageFragment(IrElementTransformerVoid.kt:41)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFile(IrElementTransformerVoid.kt:47)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFile(IrElementTransformerVoid.kt:48)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFile(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.accept(IrFileImpl.kt:81)
	at org.jetbrains.kotlin.ir.declarations.IrFile.transform(IrFile.kt:52)
	at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.transformChildren(IrModuleFragmentImpl.kt:45)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:346)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposerParamTransformer.lower(ComposerParamTransformer.kt:119)
	at androidx.compose.compiler.plugins.kotlin.ComposeIrGenerationExtension.generate(ComposeIrGenerationExtension.kt:173)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr$lambda-1(JvmIrCodegenFactory.kt:139)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:99)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:170)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:50)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.convertToIr(KotlinToJVMBytecodeCompiler.kt:275)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:116)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:60)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:172)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:54)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:91)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:43)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:471)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:123)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:367)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally$default(IncrementalCompilerRunner.kt:309)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl$rebuild(IncrementalCompilerRunner.kt:115)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:167)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:77)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:623)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1718)
	at jdk.internal.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
[untitled1.zip](https://github.com/JetBrains/compose-jb/files/8514091/untitled1.zip)
[untitled2.zip](https://github.com/JetBrains/compose-jb/files/8514093/untitled2.zip)

**Comment by kirill-grouchnikov** [comment]
1.6.20 is not yet supported

**Comment by hfhbd** [comment]
The latest stable release does not support `1.6.20`, but this build should support `1.6.20`, after chatting with Oleksandr.

**Comment by eymar** [comment]
I apologise for disinformation. The support for 1.6.20 is currently available only in `0.0.0-on-rebase-12-apr-2022-dev668`. It's from an intermediate branch. 
I will update here as soon as 1.2.0-alpha01xxx build supports 1.6.20 and 1.6.21.

**Comment by wakaztahir** [comment]
So the current stable release is 1.1.1

But I want to get the current snapshot release , to at least compose version 1.2.0-alpha06 which has fixes for `WindowInsets`

Maybe even the current latest which includes LazyLayout

How to know like which Dev versions of compose I can use rather than just the releases on the releases page , Are there any dev releases apart from what's on the releases page of this repo.

Thanks in advance !

**Comment by arkivanov** [comment]
I'm getting similar error with Compose for iOS with both Kotlin 1.6.10 and 1.6.20 - #2007

**Comment by dragossusi** [comment]
@arkivanov compose for iOS is working in alpha?

**Comment by arkivanov** [comment]
@dragossusi there are dev builds

**Comment by dragossusi** [comment]
@arkivanov can you give a sample of how to set things up?

**Comment by arkivanov** [comment]
@dragossusi You may check the [example](https://github.com/JetBrains/compose-jb/tree/master/experimental/examples/minesweeper). I used this one to get my head around.

**Comment by eymar** [comment]
1.2.0-alpha01-dev675 is out. It's based on kotlin 1.6.21.

**Comment by dragossusi** [comment]
@eymar is it published on Maven? I can find it in github releases, but using maven the dependency is not found

**Comment by chris-hatton** [comment]
Please don't raise issues directed at JetBrains Devs for problems encountered while trying a Dev build.
In my opinion, doing so is a bit disrespectful of JetBrains' time, and of the spirit in which they make the Dev builds public.
I do enjoy trying out the Dev builds too; but would ask related questions in Slack which is more focused to the community and not the maintainers.

**Comment by hfhbd** [comment]
@chris-hatton I get your point, that's why I asked Oleksander first before creating this issue. 
I think, issues are more visible and better to track than a discussion in Slack, but maybe JetBrains could add this to its contribution/issue template if bugs in dev builds should be reported.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2019">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
