### ISSUE TITLE
Compose crashes when clicking on scrollbar with empty LazyColumn

### ISSUE THREAD

**Issue by DareFox** [JetBrains/compose-jb#2179]
When the list of items is in the `LazyColumn` and I try to click on the scroll bar, Compose crashes with an I`llegalArgumentException`.

https://user-images.githubusercontent.com/47672780/178140077-9fddcdc5-7e73-4ff3-8e27-0d152be5df74.mp4

Here's sample code to reproduce this error:
Switch `isEmpty` variable to true, to see the error 
```kotlin
fun main() {
    singleWindowApplication {
        Box(Modifier.fillMaxWidth().fillMaxHeight()) {
            // CHANGE THIS VARIABLE TO SEE DIFFERENCE
            // On true (empty list), compose will crash
            val isEmpty = false

            val list = mutableListOf<Int>().also {
                val sequence = (1..10).asSequence()
                if (!isEmpty) it.addAll(sequence)
            }
            val lazyListState = rememberLazyListState()


            Column(horizontalAlignment = Alignment.CenterHorizontally){
                Text("Try to click on scrollbar")

                Spacer(modifier = Modifier.fillMaxWidth().height(10.dp))

                LazyColumn(state = lazyListState) {
                    items(list) {
                        Text(it.toString(), style = MaterialTheme.typography.h2)
                    }
                }
            }

            Box(modifier = Modifier.fillMaxWidth()) {
                VerticalScrollbar(
                    modifier = Modifier.fillMaxHeight().align(Alignment.CenterEnd).background(Color.Red.copy(0.5f)),
                    adapter = rememberScrollbarAdapter(lazyListState)
                )
            }
        }
    }
}
```

Stacktrace from sample code:
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Index should be non-negative (-1)
	at androidx.compose.foundation.lazy.list.LazyListScrollPosition.update-NTjDD6g(LazyListScrollPosition.kt:100)
	at androidx.compose.foundation.lazy.list.LazyListScrollPosition.requestPosition-NTjDD6g(LazyListScrollPosition.kt:83)
	at androidx.compose.foundation.lazy.LazyListState.snapToItemIndexInternal$foundation(LazyListState.kt:199)
	at androidx.compose.foundation.lazy.LazyListState$scrollToItem$2.invokeSuspend(LazyListState.kt:194)
	at androidx.compose.foundation.lazy.LazyListState$scrollToItem$2.invoke(LazyListState.kt)
	at androidx.compose.foundation.lazy.LazyListState$scrollToItem$2.invoke(LazyListState.kt)
	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invokeSuspend(ScrollableState.kt:148)
	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invoke(ScrollableState.kt)
	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invoke(ScrollableState.kt)
	at androidx.compose.foundation.MutatorMutex$mutateWith$2.invokeSuspend(MutatorMutex.kt:160)
	at androidx.compose.foundation.MutatorMutex$mutateWith$2.invoke(MutatorMutex.kt)
	at androidx.compose.foundation.MutatorMutex$mutateWith$2.invoke(MutatorMutex.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at androidx.compose.foundation.MutatorMutex.mutateWith(MutatorMutex.kt:153)
	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invokeSuspend(ScrollableState.kt:145)
	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invoke(ScrollableState.kt)
	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invoke(ScrollableState.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at androidx.compose.foundation.gestures.DefaultScrollableState.scroll(ScrollableState.kt:144)
	at androidx.compose.foundation.gestures.ScrollableState$DefaultImpls.scroll$default(ScrollableState.kt:51)
	at androidx.compose.foundation.lazy.LazyListState.scrollToItem(LazyListState.kt:193)
	at androidx.compose.foundation.LazyScrollbarAdapter.snapTo(Scrollbar.desktop.kt:479)
	at androidx.compose.foundation.LazyScrollbarAdapter.scrollTo(Scrollbar.desktop.kt:453)
	at androidx.compose.foundation.Scrollbar_desktopKt$scrollOnPressOutsideSlider$1$1.invokeSuspend(Scrollbar.desktop.kt:321)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(CoroutineDispatchers.skiko.kt:51)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(CoroutineDispatchers.skiko.kt:46)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.performRun(CoroutineDispatchers.skiko.kt:78)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.access$performRun(CoroutineDispatchers.skiko.kt:29)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2.invokeSuspend(CoroutineDispatchers.skiko.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Process finished with exit code 0

```

One method to get around this is to check if the list is NOT empty and only then call Composable `Scrollbar`. 

But in general it's hard to understand that the problem is in the empty collection, because Stacktrace only shows internal code of the library and does not indicate the `Scrollbar` code which caused it.  Because of this, it took me a long time to find out that the error was caused by an empty collection.

If the problem is not solvable on the Jetpack Compose side, then please at least add a clearer error message.

**Comment by m-sasha** [comment]
After the recent scrollbar changes this instead crashes with
```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot round NaN value.
	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:619)
	at androidx.compose.foundation.Scrollbar_desktopKt.computeSlidePositionAndSize(Scrollbar.desktop.kt:743)
	at androidx.compose.foundation.Scrollbar_desktopKt.access$computeSlidePositionAndSize(Scrollbar.desktop.kt:1)
	at androidx.compose.foundation.Scrollbar_desktopKt$verticalMeasurePolicy$1.measure-3p2s80s(Scrollbar.desktop.kt:755)
...
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2179">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
