### ISSUE TITLE
Exception in simple preview

### ISSUE THREAD

**Issue by Burtan** [JetBrains/compose-jb#2205]
Hi, 
I'm getting a rendering error on composable previews.

Configuration:
Linux debian testing (bookworm) with Gnome.
IntelliJ IDEA 2022.1.4
id("org.jetbrains.compose") version "1.2.0-alpha01-dev750"

```
@Preview
@Composable
internal fun TestPreview() {
    Text("Test")
}
```

```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost.renderFrame(RemotePreviewHost.kt:161)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost.renderFrame(RemotePreviewHost.kt:129)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost.access$renderFrame(RemotePreviewHost.kt:47)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost$senderThread$1.invoke(RemotePreviewHost.kt:63)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost$senderThread$1.invoke(RemotePreviewHost.kt:56)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: java.awt.HeadlessException
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
	at java.desktop/java.awt.Window.init(Window.java:501)
	at java.desktop/java.awt.Window.<init>(Window.java:453)
	at java.desktop/java.awt.Frame.<init>(Frame.java:454)
	at java.desktop/java.awt.Frame.<init>(Frame.java:412)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:204)
	at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:42)
	at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:40)
	at androidx.compose.ui.window.Window_desktopKt$Window$3.invoke(Window.desktop.kt:161)
	at androidx.compose.ui.window.Window_desktopKt$Window$3.invoke(Window.desktop.kt:156)
	at androidx.compose.ui.window.Window_desktopKt$Window$10$1.invoke(Window.desktop.kt:370)
	at androidx.compose.ui.window.Window_desktopKt$Window$10$1.invoke(Window.desktop.kt:369)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:75)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:74)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1025)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:786)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:806)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:827)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:513)
	at androidx.compose.ui.platform.Wrapper_skikoKt.setContent(Wrapper.skiko.kt:45)
	at androidx.compose.ui.ComposeScene.setContent$ui(ComposeScene.skiko.kt:337)
	at androidx.compose.ui.ComposeScene.setContent$ui$default(ComposeScene.skiko.kt:318)
	at androidx.compose.ui.ComposeScene.setContent(ComposeScene.skiko.kt:300)
	at androidx.compose.ui.ImageComposeScene.<init>(ImageComposeScene.desktop.kt:119)
	at androidx.compose.ui.ImageComposeScene.<init>(ImageComposeScene.desktop.kt:105)
	at androidx.compose.ui.ImageComposeScene_desktopKt.renderComposeScene(ImageComposeScene.desktop.kt:59)
	at androidx.compose.desktop.ui.tooling.preview.runtime.NonInteractivePreviewFacade$Companion.render(NonInteractivePreviewFacade.kt:53)
	at androidx.compose.desktop.ui.tooling.preview.runtime.NonInteractivePreviewFacade.render(NonInteractivePreviewFacade.kt)
	... 10 more

```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2205">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
