### ISSUE TITLE
Qualified return in LazyColumn makes it crash

### ISSUE THREAD

**Issue by Obdormio** [JetBrains/compose-jb#2225]
You can repro with something like this:
```kotlin
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyItemScope
import androidx.compose.foundation.lazy.items
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

@Composable
fun MyScaffold(list: List<String>, itemContent: @Composable LazyItemScope.(item: String) -> Unit) {
    LazyColumn {
        items(list, itemContent = itemContent)
    }
}

@Composable
fun Line(it: String) {
    Row {
        if (it == "A") {
            Text("is A")
            return@Row
        }

        Text("is B")
    }
}

@Composable
fun App() {
    val list = remember { listOf("A", "B") }

    MyScaffold(list) {
        Line(it)
    }
}

fun main() = application {
    Window(onCloseRequest = this::exitApplication) {
        App()
    }
}
```

and it crashes with something like this:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -5 out of bounds for length 0
	at androidx.compose.runtime.SlotTableKt.key(SlotTable.kt:2570)
	at androidx.compose.runtime.SlotTableKt.access$key(SlotTable.kt:1)
	at androidx.compose.runtime.SlotReader.groupKey(SlotTable.kt:622)
	at androidx.compose.runtime.ComposerImpl.end(Composer.kt:1967)
	at androidx.compose.runtime.ComposerImpl.endGroup(Composer.kt:1323)
	at androidx.compose.runtime.ComposerImpl.endRoot(Composer.kt:1235)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2588)
...
```

**Comment by Obdormio** [comment]
if you remove the qualified return in `@Compose fun Line`, it works.

```kotlin
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyItemScope
import androidx.compose.foundation.lazy.items
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

@Composable
fun MyScaffold(list: List<String>, itemContent: @Composable LazyItemScope.(item: String) -> Unit) {
    LazyColumn {
        items(list, itemContent = itemContent)
    }
}

@Composable
fun Line(it: String) {
    Row {
        if (it == "A") {
            Text("is A")
//            return@Row     !!!!!!!!!!!! REMOVE THE QUALIFIED RETURN
        }

        Text("is B")
    }
}

@Composable
fun App() {
    val list = remember { listOf("A", "B") }

    MyScaffold(list) {
        Line(it)
    }
}

fun main() = application {
    Window(onCloseRequest = this::exitApplication) {
        App()
    }
}
```

**Comment by Obdormio** [comment]
#2230

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2225">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
