### ISSUE TITLE
IdSignature clash: Existed declaration FUN name:Button$composable

### ISSUE THREAD

**Issue by CLOVIS-AI** [JetBrains/compose-jb#2244]
The compiler crashes with this error message. I did not manage to find the cause.

Stacktrace:
```
java.lang.IllegalStateException: IdSignature clash: clovis.ui.components/Buttons.Button$composable|3863356179520890837[0]; Existed declaration FUN name:Button$composable visibility:public modality:ABSTRACT <> ($this:clovis.ui.components.Buttons, action:kotlin.Function0<kotlin.Unit>, enabled:kotlin.Boolean, loading:clovis.ui.utils.Progression, icon:kotlin.Function2<androidx.compose.runtime.Composer, kotlin.Int, kotlin.Unit>?, contents:kotlin.Function2<androidx.compose.runtime.Composer, kotlin.Int, kotlin.Unit>, $composer:androidx.compose.runtime.Composer?, $changed:kotlin.Int) returnType:kotlin.Unit clashed with new FUN name:Button$composable visibility:public modality:ABSTRACT <> ($this:clovis.ui.components.Buttons, action:kotlin.Function0<kotlin.Unit>, enabled:kotlin.Boolean, loading:clovis.ui.utils.Progression, icon:kotlin.Function2<androidx.compose.runtime.Composer, kotlin.Int, kotlin.Unit>?, contents:kotlin.Function2<androidx.compose.runtime.Composer, kotlin.Int, kotlin.Unit>, $composer:androidx.compose.runtime.Composer?, $changed:kotlin.Int) returnType:kotlin.Unit
	at org.jetbrains.kotlin.ir.backend.js.lower.serialization.ir.JsUniqIdClashTracker.commit(JsDeclarationTable.kt:27)
	at org.jetbrains.kotlin.backend.common.serialization.GlobalDeclarationTable.computeSignatureByDeclaration(DeclarationTable.kt:48)
```

Full stacktrace: https://gitlab.com/opensavvy/clovis/-/jobs/2877060532

To reproduce:
- Clone project https://gitlab.com/opensavvy/clovis
- Check out commit `267f21ba62cdf95063d4974381768d37efbc244e`
- `./gradlew :ui.tailwind:compileKotlinJs`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2244">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
