### ISSUE TITLE
Cannot invoke "String.trim()" because "in" is null

### ISSUE THREAD

**Issue by bric3** [JetBrains/compose-jb#2309]
I'm building a new project with jetbrains compose (plugin version 1.1.1), kotlin 1.7.20-RC

```
plugins {
    id("io.github.bric3.gctk.java-common-conventions")
    kotlin("jvm")
    id("org.jetbrains.compose")
    application
}
```

But the loading of the plugin fails with this error

```
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:130)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:42)
Caused by: java.lang.NullPointerException: Cannot invoke "String.trim()" because "in" is null
	at org.jetbrains.compose.ComposePlugin.apply$lambda-6$lambda-5(ComposePlugin.kt:129)
	at org.jetbrains.compose.ComposePlugin.apply$lambda-6(ComposePlugin.kt:126)
	at jdk.proxy1/jdk.proxy1.$Proxy65.afterEvaluate(Unknown Source)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:130)
```

Also when setting the jvm target, eg. `kotlinOptions.jvmTarget = "17"`, the error then become about `void org.jetbrains.kotlin.gradle.dsl.KotlinJvmOptions.setUseIR(boolean)`

```
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:130)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:42)
Caused by: org.gradle.internal.event.ListenerNotificationException: Failed to notify project evaluation listener.
	at jdk.proxy1/jdk.proxy1.$Proxy65.afterEvaluate(Unknown Source)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:130)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:42)
Caused by: java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.gradle.dsl.KotlinJvmOptions.setUseIR(boolean)'
	at org.jetbrains.compose.ComposePlugin.apply$lambda-6$lambda-5(ComposePlugin.kt:131)
	at org.jetbrains.compose.ComposePlugin.apply$lambda-6
	at jdk.proxy1/jdk.proxy1.$Proxy65.afterEvaluate(Unknown Source)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:130)
```

**Comment by hfhbd** [comment]
`1.1.1` is not compatible with Kotlin `1.7.20-RC`.

**Comment by bric3** [comment]
Yeah it was not immediately clear to me hence the issue. And at this time I played with the alpha version to get it working, but with some adjustment on the compiler module, see https://github.com/JetBrains/compose-jb/issues/2108#issuecomment-1245397563

So follow up on #2018

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2309">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
