### ISSUE TITLE
TextField not working inside Popup

### ISSUE THREAD

**Issue by ElisaMin** [JetBrains/compose-jb#2444]
I cant type anything but using windows chinese pinying IME to just input abc...xyz and also get this error. 
its working well while typing in `BasicTextFeild` but still throws the same exception.

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot read field "x" because "rc" is null
	at java.desktop/sun.awt.windows.WInputMethod$1.run(WInputMethod.java:617)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

code:
```kotlin
fun main() {
    singleWindowApplication {
        addDeviceDialog { println("sn") }
    }
}

@Composable
@OptIn(ExperimentalMaterial3Api::class)
fun addDeviceDialog(
    onSubmit:(String)->Unit={},
    onDismissing:()->Unit={}
) {
    var value by remember { mutableStateOf("") }
    // working will with this
//    BasicTextField(value,{value= it})
    Popup(alignment = Alignment.Center, onDismissRequest = onDismissing) {
        ElevatedCard(Modifier.sizeIn(maxWidth = 340.dp), elevation = CardDefaults.cardElevation(5.dp)) {
            Column(Modifier.padding(16.dp)) {
                Text("添加设备")
                OutlinedTextField(
                    value = value,
                    onValueChange = {
                        println(it)
                        value=it
                    },trailingIcon = {
                        if (value.isNotEmpty()) IconButton({onSubmit(value)}) {
                            Icon(Icons.Default.Check,"done")
                        } else IconButton(onDismissing) {
                            Icon(Icons.Default.Clear,"close it")
                        }
                    },
                )
            }
        }
    }
}
```

**Comment by igordmn** [comment]
As a workaround, change your code to this:
```
Popup(alignment = Alignment.Center, onDismissRequest = onDismissing, focusable = true)
```

Overall we have an issue that `focusable`/`non-focusable` is not properly defined/documented.

Not sure yet, but probably `focusable` parameter should only affect the popup's container itself, the children should still be focusable. In fact, they are already focusable, because you are able to click on them, and we see that they become focused. What we still need to do is to route keyboard events properly.

Related issue: https://github.com/JetBrains/compose-jb/issues/1513

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2444">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
