### ISSUE TITLE
bug(idea-plugin): exception when rendering @Preview

### ISSUE THREAD

**Issue by codymikol** [JetBrains/compose-jb#2465]
For some reason it fails to find the method that I'm clicking the compose icon for in this screenshot

![image](https://user-images.githubusercontent.com/13606342/201419196-3438d0c4-68b5-4610-8d09-58a385586012.png)

![image](https://user-images.githubusercontent.com/13606342/201421329-39c1d384-e578-47fa-b2a1-66d910160323.png)

reproduction available here: https://github.com/codymikol/git-down/tree/plugin-crash-reproduction

Most relevant line

```
Caused by: java.lang.ClassNotFoundException: Composable Method 'com.codymikol.components.commit.CommitBottomToolbarKt.CommitBottomToolbarDemo' not found
```

```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost.renderFrame(RemotePreviewHost.kt:161)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost.renderFrame(RemotePreviewHost.kt:129)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost.access$renderFrame(RemotePreviewHost.kt:47)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost$senderThread$1.invoke(RemotePreviewHost.kt:63)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost$senderThread$1.invoke(RemotePreviewHost.kt:56)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: java.lang.ClassNotFoundException: Composable Method 'com.codymikol.components.commit.CommitBottomToolbarKt.CommitBottomToolbarDemo' not found
	at androidx.compose.ui.tooling.ComposableInvoker.invokeComposable(ComposableInvoker.kt:203)
	at androidx.compose.desktop.ui.tooling.preview.runtime.NonInteractivePreviewFacade$Companion$render$1.invoke(NonInteractivePreviewFacade.kt:58)
	at androidx.compose.desktop.ui.tooling.preview.runtime.NonInteractivePreviewFacade$Companion$render$1.invoke(NonInteractivePreviewFacade.kt:54)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.ui.ComposeScene$setContent$5.invoke(ComposeScene.skiko.kt:374)
	at androidx.compose.ui.ComposeScene$setContent$5.invoke(ComposeScene.skiko.kt:373)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:177)
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2$1.invoke(Wrapper.skiko.kt:47)
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2$1.invoke(Wrapper.skiko.kt:46)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.ui.platform.Wrapper_skikoKt.provide(Wrapper.skiko.kt:63)
	at androidx.compose.ui.platform.Wrapper_skikoKt.access$provide(Wrapper.skiko.kt:1)
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2.invoke(Wrapper.skiko.kt:46)
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2.invoke(Wrapper.skiko.kt:45)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:75)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3193)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3183)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:252)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3183)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime(Composer.kt:3119)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:584)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:811)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
	at androidx.compose.ui.platform.Wrapper_skikoKt.setContent(Wrapper.skiko.kt:45)
	at androidx.compose.ui.ComposeScene.setContent$ui(ComposeScene.skiko.kt:370)
	at androidx.compose.ui.ComposeScene.setContent$ui$default(ComposeScene.skiko.kt:349)
	at androidx.compose.ui.ComposeScene.setContent(ComposeScene.skiko.kt:331)
	at androidx.compose.ui.ImageComposeScene.<init>(ImageComposeScene.desktop.kt:119)
	at androidx.compose.ui.ImageComposeScene.<init>(ImageComposeScene.desktop.kt:105)
	at androidx.compose.ui.ImageComposeScene_desktopKt.renderComposeScene(ImageComposeScene.desktop.kt:59)
	at androidx.compose.desktop.ui.tooling.preview.runtime.NonInteractivePreviewFacade$Companion.render(NonInteractivePreviewFacade.kt:54)
	at androidx.compose.desktop.ui.tooling.preview.runtime.NonInteractivePreviewFacade.render(NonInteractivePreviewFacade.kt)
	... 10 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at androidx.compose.ui.tooling.ComposableInvoker.invokeComposableMethod(ComposableInvoker.kt:155)
	at androidx.compose.ui.tooling.ComposableInvoker.invokeComposable(ComposableInvoker.kt:195)
	... 50 more
Caused by: org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index
	at org.eclipse.jgit.lib.Repository.getWorkTree(Repository.java:1573)
	at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:87)
	at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:73)
	at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:113)
	at com.codymikol.state.GitDownState$status$1.invoke(state.kt:60)
	at com.codymikol.state.GitDownState$status$1.invoke(state.kt:59)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2117)
	at androidx.compose.runtime.DerivedSnapshotState.currentRecord(DerivedState.kt:121)
	at androidx.compose.runtime.DerivedSnajava.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost.renderFrame(RemotePreviewHost.kt:161)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost.renderFrame(RemotePreviewHost.kt:129)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost.access$renderFrame(RemotePreviewHost.kt:47)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost$senderThread$1.invoke(RemotePreviewHost.kt:63)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost$senderThread$1.invoke(RemotePreviewHost.kt:56)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: java.lang.ClassNotFoundException: Composable Method 'com.codymikol.components.commit.CommitBottomToolbarKt.CommitBottomToolbarDemo' not found
	at androidx.compose.ui.tooling.ComposableInvoker.invokeComposable(ComposableInvoker.kt:203)
	at androidx.compose.desktop.ui.tooling.preview.runtime.NonInteractivePreviewFacade$Companion$render$1.invoke(NonInteractivePreviewFacade.kt:58)
	at androidx.compose.desktop.ui.tooling.preview.runtime.NonInteractivePreviewFacade$Companion$render$1.invoke(NonInteractivePreviewFacade.kt:54)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.ui.ComposeScene$setContent$5.invoke(ComposeScene.skiko.kt:374)
	at androidx.compose.ui.ComposeScene$setContent$5.invoke(ComposeScene.skiko.kt:373)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:177)
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2$1.invoke(Wrapper.skiko.kt:47)
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2$1.invoke(Wrapper.skiko.kt:46)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.ui.platform.Wrapper_skikoKt.provide(Wrapper.skiko.kt:63)
	at androidx.compose.ui.platform.Wrapper_skikoKt.access$provide(Wrapper.skiko.kt:1)
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2.invoke(Wrapper.skiko.kt:46)
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2.invoke(Wrapper.skiko.kt:45)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:75)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3193)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3183)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:252)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3183)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime(Composer.kt:3119)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:584)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:811)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
	at androidx.compose.ui.platform.Wrapper_skikoKt.setContent(Wrapper.skiko.kt:45)
	at androidx.compose.ui.ComposeScene.setContent$ui(ComposeScene.skiko.kt:370)
	at androidx.compose.ui.ComposeScene.setContent$ui$default(ComposeScene.skiko.kt:349)
	at androidx.compose.ui.ComposeScene.setContent(ComposeScene.skiko.kt:331)
	at androidx.compose.ui.ImageComposeScene.<init>(ImageComposeScene.desktop.kt:119)
	at androidx.compose.ui.ImageComposeScene.<init>(ImageComposeScene.desktop.kt:105)
	at androidx.compose.ui.ImageComposeScene_desktopKt.renderComposeScene(ImageComposeScene.desktop.kt:59)
	at androidx.compose.desktop.ui.tooling.preview.runtime.NonInteractivePreviewFacade$Companion.render(NonInteractivePreviewFacade.kt:54)
	at androidx.compose.desktop.ui.tooling.preview.runtime.NonInteractivePreviewFacade.render(NonInteractivePreviewFacade.kt)
	... 10 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at androidx.compose.ui.tooling.ComposableInvoker.invokeComposableMethod(ComposableInvoker.kt:155)
	at androidx.compose.ui.tooling.ComposableInvoker.invokeComposable(ComposableInvoker.kt:195)
	... 50 more
Caused by: org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index
	at org.eclipse.jgit.lib.Repository.getWorkTree(Repository.java:1573)
	at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:87)
	at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:73)
	at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:113)
	at com.codymikol.state.GitDownState$status$1.invoke(state.kt:60)
	at com.codymikol.state.GitDownState$status$1.invoke(state.kt:59)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2117)
	at androidx.compose.runtime.DerivedSnapshotState.currentRecord(DerivedState.kt:121)
	at androidx.compose.runtime.DerivedSnapshotState.getCurrentValue(DerivedState.kt:171)
	at androidx.compose.runtime.DerivedSnapshotState.getValue(DerivedState.kt:165)
	at com.codymikol.state.GitDownState$indexFilesAdded$1.invoke(state.kt:108)
	at com.codymikol.state.GitDownState$indexFilesAdded$1.invoke(state.kt:107)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2117)
	at androidx.compose.runtime.DerivedSnapshotState.currentRecord(DerivedState.kt:121)
	at androidx.compose.runtime.DerivedSnapshotState.getCurrentValue(DerivedState.kt:171)
	at androidx.compose.runtime.DerivedSnapshotState.getValue(DerivedState.kt:165)
	at com.codymikol.state.GitDownState$indexIsEmpty$1.invoke(state.kt:128)
	at com.codymikol.state.GitDownState$indexIsEmpty$1.invoke(state.kt:127)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2117)
	at androidx.compose.runtime.DerivedSnapshotState.currentRecord(DerivedState.kt:121)
	at androidx.compose.runtime.DerivedSnapshotState.getDependencies(DerivedState.kt:176)
	at androidx.compose.runtime.CompositionImpl.recordReadOf(Composition.kt:713)
	at androidx.compose.runtime.Recomposer$readObserverOf$1.invoke(Recomposer.kt:924)
	at androidx.compose.runtime.Recomposer$readObserverOf$1.invoke(Recomposer.kt:924)
	at androidx.compose.runtime.DerivedSnapshotState.getValue(DerivedState.kt:164)
	at com.codymikol.components.commit.CommitBottomToolbarKt.CommitBottomToolbar(CommitBottomToolbar.kt:61)
	at com.codymikol.components.commit.CommitBottomToolbarKt.CommitBottomToolbarDemo(CommitBottomToolbar.kt:25)
	... 56 more
pshotState.getCurrentValue(DerivedState.kt:171)
	at androidx.compose.runtime.DerivedSnapshotState.getValue(DerivedState.kt:165)
	at com.codymikol.state.GitDownState$indexFilesAdded$1.invoke(state.kt:108)
	at com.codymikol.state.GitDownState$indexFilesAdded$1.invoke(state.kt:107)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2117)
	at androidx.compose.runtime.DerivedSnapshotState.currentRecord(DerivedState.kt:121)
	at androidx.compose.runtime.DerivedSnapshotState.getCurrentValue(DerivedState.kt:171)
	at androidx.compose.runtime.DerivedSnapshotState.getValue(DerivedState.kt:165)
	at com.codymikol.state.GitDownState$indexIsEmpty$1.invoke(state.kt:128)
	at com.codymikol.state.GitDownState$indexIsEmpty$1.invoke(state.kt:127)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2117)
	at androidx.compose.runtime.DerivedSnapshotState.currentRecord(DerivedState.kt:121)
	at androidx.compose.runtime.DerivedSnapshotState.getDependencies(DerivedState.kt:176)
	at androidx.compose.runtime.CompositionImpl.recordReadOf(Composition.kt:713)
	at androidx.compose.runtime.Recomposer$readObserverOf$1.invoke(Recomposer.kt:924)
	at androidx.compose.runtime.Recomposer$readObserverOf$1.invoke(Recomposer.kt:924)
	at androidx.compose.runtime.DerivedSnapshotState.getValue(DerivedState.kt:164)
	at com.codymikol.components.commit.CommitBottomToolbarKt.CommitBottomToolbar(CommitBottomToolbar.kt:61)
	at com.codymikol.components.commit.CommitBottomToolbarKt.CommitBottomToolbarDemo(CommitBottomToolbar.kt:25)
	... 56 more
```

**Comment by igordmn** [comment]
Isn't this the real exception, caused by your code?

```
Caused by: org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index
```

I tried to run this code, and result is the same - we have an exception:
```
import androidx.compose.runtime.mutableStateOf
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication {
    CommitBottomToolbar(mutableStateOf("Hello!"))
}
```

If you sure that it is not your code, and something in Compose interferes, please, make a minimal reproducer without external dependencies.
