### ISSUE TITLE
More informative exception when skiko dependency is missing.

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-jb#249]
Users get a `NullPointerException` if they forget to include the `implementation(compose.desktop.currentOs)` dependency.  The NPE is really not very helpful in helping the user to identify the issue, and not really specific enough for ComposeDesktop to catch and rethrow.  Surely a more informative error message could be thrown by skiko when a dependency is missing.

```
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at androidx.compose.desktop.ComposeLayer.<init>(ComposeLayer.kt:72)
	at androidx.compose.desktop.ComposeWindow.<init>(ComposeWindow.kt:26)
	at androidx.compose.desktop.AppWindow.<init>(AppWindow.kt:107)
	at androidx.compose.desktop.AppWindow.<init>(AppWindow.kt)
	at androidx.compose.desktop.AppWindowKt$Window$1.run(AppWindow.kt:76)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.jetbrains.skiko.Library.load(Library.kt:42)
	at org.jetbrains.skija.impl.Library$Companion.staticLoad(Library.kt:9)
	at org.jetbrains.skija.impl.Library.staticLoad(Library.kt)
	at org.jetbrains.skija.PictureRecorder.<clinit>(PictureRecorder.java:9)
	... 18 more
```

Ideally after https://github.com/JetBrains/skiko/issues/35 is fixed, Compose-Desktop could then catch the thrown exception type, and rethrow it with an even more informative error message suggesting which Compose (`dependency`implementation(compose.desktop.currentOs)`) is likely missing.

**Comment by jimgoog** [comment]
Javier (slack) also suggested that maybe the gradle plugin could do something intelligent whereby if the `compose.desktop` block is present in the gradle file, but the final configuration does not include a dependency that provides the skiko binaries, then an autofix button could be provided in the IDE.

```
compose.desktop {
    application {
        mainClass = "..."
    }
}
```

Obviously correctly detecting such a failure would be more complex, but it moves it from a runtime error to a compile time error and exposes it more nicely in the IDE, so it's worth considering for a sweet user experience.

**Comment by olonho** [comment]
Skiko side is fixed with https://github.com/JetBrains/skiko/commit/b5864536c30d6e4ebeb27a7a8f22a3a210e2d0ce. However, catching this exception and error reporting is required in too many places (all places where we load JNI library), so meaningful error suggesting `dependency implementation(compose.desktop.currentOs)` doesn't look feasible.

**Comment by olonho** [comment]
Let's close for now, maybe shall fix the docs somehow.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5558">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
