### ISSUE TITLE
Upgrade compose version from 1.1.1 to 1.3.0-beta02, the TextField of my desktop application could not input any Chinese character

### ISSUE THREAD

**Issue by GaoXing0608** [JetBrains/compose-jb#2493]
2022-11-23 09:21:27,186 INFO (UncaughtExceptionHandler.kt:53)- java.lang.NullPointerException: Cannot read field "x" because "rc" is null
    at java.desktop/sun.awt.windows.WInputMethod$1.run(WInputMethod.java:617)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
    at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
    at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

------------------------------------------------------------------------------------------------------------------------------------

When I press the Space and Enter key to input the Chinese character, the application crashed. It is normal when I input english character.

**Comment by dima-avdeev-jb** [comment]
Thanks for the report!

**Comment by igordmn** [comment]
Reproducible in 1.2.1.

>  the application crashed.

In the `todoapp-lite` example, application itself doesn't crash (on my machine), we only see the crash in the logs.

We still can type Chinese text, but the popup is wrongly positioned.

Investigating further...

**Comment by GaoXing0608** [comment]
> Cannot read field "x" because "rc" is null

Because of I have set the UncaughtExceptionHandler for my application and exit the application while it catched. 

---------------------------------------------------------------------
Main.kt
fun App() {

    MaterialTheme {
        val content = mutableStateOf("")
        TextField(
            value = content.value,
            onValueChange = {
                content.value = it
            }
        )
    }
}

fun main() = application {

    Thread.setDefaultUncaughtExceptionHandler(UncaughtExceptionHandler())

    Window(onCloseRequest = ::exitApplication) {
        App()
    }
}

--------------------------------------------------------------------------------
UncaughtExceptionHandler.kt
class UncaughtExceptionHandler: Thread.UncaughtExceptionHandler {
    override fun uncaughtException(t: Thread?, e: Throwable?) {

        // Some operation for saving the crash log

        // Exit the application
        exitProcess(0)
    }
}

-----------------------------------------------------------------------------

So there are some bugs of TextFiled while inputing Chinese charcter

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2493">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
