### ISSUE TITLE
NotImplementedError when using `ImageBitmap.toPixelMap` in JS

### ISSUE THREAD

**Issue by eygraber** [JetBrains/compose-jb#2543]
Looks like `ByteArray.putBytesInto` was never implemented - https://github.com/JetBrains/androidx/blob/01ea158ab4dab7da220e6213150abbc1c59fe87b/compose/ui/ui-graphics/src/jsMain/kotlin/androidx/compose/ui/graphics/JsImageAsset.js.kt

```
"NotImplementedError: An operation is not implemented: implement js ByteArray.putBytesInto()
    at putBytesInto (webpack-internal:///./kotlin/androidx-ui-graphics.js:12430:11)
    at SkiaBackedImageBitmap.readPixels_foa4om_k$ (webpack-internal:///./kotlin/androidx-ui-graphics.js:13384:5)
    at toPixelMap (webpack-internal:///./kotlin/androidx-ui-graphics.js:3848:19)
    at toPixelMap$default (webpack-internal:///./kotlin/androidx-ui-graphics.js:3866:12)
    at colorForPosition (webpack-internal:///./kotlin/compose-color-picker-library.js:531:21)
    at eval (webpack-internal:///./kotlin/compose-color-picker-library.js:1521:30)
    at ComposableLambdaImpl.invoke_5qf8pc_k$ (webpack-internal:///./kotlin/androidx-runtime.js:34252:92)
    at eval (webpack-internal:///./kotlin/compose-color-picker-library.js:1687:25)
    at eval (webpack-internal:///./kotlin/androidx-foundation-layout.js:2265:9)
    at ComposableLambdaImpl.invoke_6harzl_k$ (webpack-internal:///./kotlin/androidx-runtime.js:34238:92)"
```

**Comment by eygraber** [comment]
Here's a very naive implementation (naive to the point that I didn't run it or test it, and I don't have much experience with js, but it looks OKish):

```
fun ByteArray.putBytesInto(array: IntArray, offset: Int, length: Int) {
  val byteBuffer = Uint8Array(this.toTypedArray()).buffer
  val intArray = Int32Array(byteBuffer, offset, length)
  for(i in 0 until intArray.length) {
    array[i] = intArray[i]
  }
}
```

**Comment by eygraber** [comment]
Built it locally and ran a test. It seems to work. Not sure how performant it is, but for my use case it works.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2543">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
