### ISSUE TITLE
Updating to 1.3.0 breaks LazyColumn in js applications

### ISSUE THREAD

**Issue by jeran** [JetBrains/compose-jb#2549]
I'm aware 1.3.0 is currently in development. Apologies if it's too early to be reporting bugs.

I recently tried to migrate to `1.3.0-beta04-dev885` from `1.2.1` because it has a fix for a performance issue with `LoadedFont`, but upgrading causes a crash when using `LazyColumn`. This crash is also present in `1.3.0-alpha01-dev849`.

```
Uncaught TypeError: $itemProvider.Item$composable_79iv1w_k$ is not a function
    at eval (LazyLayoutItemContentFactory.kt?f18b:99:38)
    at ComposableLambdaImpl.invoke_6harzl_k$ (ComposableLambda.js.kt?a45e:107:22)
    at eval (androidx-foundation.js:15074:25)
    at CompositionLocalProvider$composable (CompositionLocal.kt?857d:228:5)
    at SaveableStateHolderImpl.SaveableStateProvider$composable_n5yi3h_k$ (SaveableStateHolder.kt?22c2:84:13)
    at LazySaveableStateHolder.SaveableStateProvider$composable_n5yi3h_k$ (LazySaveableStateHolder.kt?0304:84:39)
    at eval (LazyLayoutItemContentFactory.kt?f18b:98:41)
    at ComposableLambdaImpl.invoke_6harzl_k$ (ComposableLambda.js.kt?a45e:107:22)
    at eval (androidx-foundation.js:15053:25)
    at eval (Composables.kt?f577:490:509)
```

I've reproduced the issue in a standalone project here:
https://github.com/jeran/compose-jb-bug

Thank you kindly for you time!

**Comment by AlexeyTsvetkov** [comment]
Reproduced with the sample project

**Comment by PaulWoitaschek** [comment]
We're also facing this. 

I don't think it's ever too early to report bugs. The worst thing is that some maintainer sees this and says: It's known, thank you.

The best thing is that it's not known yet and it will be fixed in a future release. And that other early adopters (like we 😊 ) now have an issue they can follow and get notfiied when it's fixed.

**Comment by jeran** [comment]
tested version 1.3.0 on our end. seems to work fine! feel free to close out

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2549">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
