### ISSUE TITLE
Skija crashed with this code

### ISSUE THREAD

**Issue by Dominaezzz** [JetBrains/compose-jb#262]
```kotlin
import androidx.compose.desktop.Window
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.material.Button
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.IntSize

enum class Orientation {
	HORIZONTAL,
	VERTICAL
}

@Composable
fun OrientedContent(
	orientation: Orientation,
	modifier: Modifier = Modifier,
	content: @Composable () -> Unit) {
	return when (orientation) {
		Orientation.HORIZONTAL -> Row(modifier = modifier) { content() }
		Orientation.VERTICAL -> Column(modifier = modifier) { content () }
	}
}

fun main() {
	Window(title = "Broken", size = IntSize(300, 300)) {
		MaterialTheme {
			var orientation by remember { mutableStateOf(Orientation.HORIZONTAL) }
			OrientedContent(orientation) {
				var counter by remember { mutableStateOf(0) }
				Button(
					onClick = {
						counter++
						orientation = if (orientation == Orientation.HORIZONTAL) Orientation.VERTICAL else Orientation.HORIZONTAL
					}
				) {
					Text("Toggle!")
				}
				Text("Clicked $counter times")
			}
		}
	}
}
```

```
17:00:31: Executing task 'run'...

> Task :wrapper

BUILD SUCCESSFUL in 121ms
1 actionable task: 1 executed
> Task :compileKotlin
> Task :compileJava NO-SOURCE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :inspectClassesForKotlinIC
> Task :jar

> Task :run
Exception in thread "AWT-EventQueue-0 @coroutine#2" java.lang.RuntimeException: Can't wrap nullptr
	at org.jetbrains.skija.impl.Native.<init>(Native.java:12)
	at org.jetbrains.skija.impl.Managed.<init>(Managed.java:15)
	at org.jetbrains.skija.impl.Managed.<init>(Managed.java:11)
	at org.jetbrains.skija.impl.RefCnt.<init>(RefCnt.java:7)
	at org.jetbrains.skija.DirectContext.<init>(DirectContext.java:21)
	at org.jetbrains.skiko.RenderTargetsKt.makeGLContext(RenderTargets.kt:6)
	at org.jetbrains.skiko.SkiaLayer.draw(SkiaWindow.kt:55)
	at org.jetbrains.skiko.HardwareLayer.redrawLayer(Native Method)
	at androidx.compose.desktop.ComposeLayer.onFrame(ComposeLayer.kt:76)
	at androidx.compose.desktop.ComposeLayer$onFrame$1.invokeSuspend(ComposeLayer.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Can't wrap nullptr
	at org.jetbrains.skija.impl.Native.<init>(Native.java:12)
	at org.jetbrains.skija.impl.Managed.<init>(Managed.java:15)
	at org.jetbrains.skija.impl.Managed.<init>(Managed.java:11)
	at org.jetbrains.skija.impl.RefCnt.<init>(RefCnt.java:7)
	at org.jetbrains.skija.DirectContext.<init>(DirectContext.java:21)
	at org.jetbrains.skiko.RenderTargetsKt.makeGLContext(RenderTargets.kt:6)
	at org.jetbrains.skiko.SkiaLayer.draw(SkiaWindow.kt:55)
	at org.jetbrains.skiko.HardwareLayer.redrawLayer(Native Method)
	at org.jetbrains.skiko.HardwareLayer.display(HardwareLayer.kt:20)
	at org.jetbrains.skiko.HardwareLayer.paint(HardwareLayer.kt:16)
	at java.desktop/sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
	at java.desktop/sun.awt.X11.XRepaintArea.paintComponent(XRepaintArea.java:66)
	at java.desktop/sun.awt.RepaintArea.paint(RepaintArea.java:240)
	at java.desktop/sun.awt.X11.XComponentPeer.handleEvent(XComponentPeer.java:555)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5072)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

BUILD SUCCESSFUL in 7s
5 actionable tasks: 4 executed, 1 up-to-date
17:00:39: Task execution finished 'run'.

```

Ran with `0.3.0-build135`.

**Comment by Dominaezzz** [comment]
Nvm, it's my computer being weird. :facepalm:

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5550">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
