### ISSUE TITLE
Kotlin 1.8 Canvas JS Error - Layout state is not idle before measure starts

### ISSUE THREAD

**Issue by eygraber** [JetBrains/compose-jb#2646]
I upgraded [my project](https://github.com/eygraber/portal/) to Kotlin 1.8.0 and when I run `gradle :samples:kotlin-inject:js-app:jsBrowserDevelopmentRun` the app loads in the browser but clicking the alarm clock icon in the center logs the following to the console (using compose-jb 1.3.0-rc01):

```
Uncaught TypeError: $itemProvider.Item$composable_79iv1w_k$ is not a function
    at eval (LazyLayoutItemContentFactory.kt?923d:99:38)
    at ComposableLambdaImpl.invoke_6harzl_k$ (ComposableLambda.js.kt?b351:107:22)
    at eval (androidx-foundation.js:19823:25)
    at CompositionLocalProvider$composable (CompositionLocal.kt?a409:228:5)
    at SaveableStateHolderImpl.SaveableStateProvider$composable_n5yi3h_k$ (SaveableStateHolder.kt?25f1:84:13)
    at LazySaveableStateHolder.SaveableStateProvider$composable_n5yi3h_k$ (LazySaveableStateHolder.kt?d891:84:39)
    at eval (LazyLayoutItemContentFactory.kt?923d:98:41)
    at ComposableLambdaImpl.invoke_6harzl_k$ (ComposableLambda.js.kt?b351:107:22)
    at eval (androidx-foundation.js:19795:25)
    at eval (Composables.kt?34cf:490:509)

IllegalStateException: layout state is not idle before measure starts
    at performMeasure (webpack-internal:///./kotlin/androidx-ui.js:25808:13)
    at MeasurePassDelegate.remeasure_nsm8rd_k$ (webpack-internal:///./kotlin/androidx-ui.js:25286:7)
    at MeasurePassDelegate.measure_ikak0q_k$ (webpack-internal:///./kotlin/androidx-ui.js:25273:10)
    at RootMeasurePolicy.measure_i7pm3b_k$ (webpack-internal:///./kotlin/androidx-ui.js:17790:52)
    at InnerNodeCoordinator.measure_ikak0q_k$ (webpack-internal:///./kotlin/androidx-ui.js:21236:27)
    at eval (webpack-internal:///./kotlin/androidx-ui.js:25834:47)
    at Companion_7.observe_3gku70_k$ (webpack-internal:///./kotlin/androidx-runtime.js:26610:25)
    at eval (webpack-internal:///./kotlin/androidx-runtime.js:34152:33)
    at observeDerivedStateRecalculations (webpack-internal:///./kotlin/androidx-runtime.js:8134:7)
    at SnapshotStateObserver.observeReads_uhozon_k$ (webpack-internal:///./kotlin/androidx-runtime.js:34206:7)
```

**Comment by eygraber** [comment]
Maybe introduced by https://github.com/JetBrains/androidx/pull/368 or https://github.com/JetBrains/androidx/pull/372

**Comment by eymar** [comment]
> Maybe introduced by [JetBrains/androidx#368](https://github.com/JetBrains/androidx/pull/368) or [JetBrains/androidx#372](https://github.com/JetBrains/androidx/pull/372)

These two commits are not a part of 1.3.0-rc01 (was published in Dec 2022).

I tried your project with 1.3.0-rc02 and kotlin 1.8.0 (as it's in master at the moment) and there is no issue:



![Screenshot 2023-01-19 120130](https://user-images.githubusercontent.com/7372778/213425901-d7f79f85-ab4a-4af5-abfc-421b39088abf.png)

**Comment by eygraber** [comment]
Looks like the issue was a dependency that was built using an older version of Kotlin/compose-jb - https://github.com/JetBrains/compose-jb/issues/2649

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2646">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
