### ISSUE TITLE
Compiler 1.4.0-rc01 fails when compiling Javascript IR

### ISSUE THREAD

**Issue by colinrtwhite** [JetBrains/compose-jb#2660]
Hi, this might be a Kotlin 1.8 issue but wanted to raise it here unless it's related. When updating [Redwood](https://github.com/cashapp/redwood) to Kotlin 1.8 and the `1.4.0-rc01` version of the Jetbrains Compose compiler we get the following compiler error:

```
> Task :redwood-protocol-compose:compileTestDevelopmentExecutableKotlinJs FAILED
e: java.lang.IllegalStateException: Symbol for app.cash.redwood.compose/RedwoodComposition.setContent$composable|8292046389414869108[0] is unbound
        at org.jetbrains.kotlin.ir.symbols.impl.IrBindablePublicSymbolBase.getOwner(IrPublicSymbolBase.kt:52)
        at org.jetbrains.kotlin.ir.backend.js.ic.CacheUpdater.collectImplementedSymbol(CacheUpdater.kt:299)
        at org.jetbrains.kotlin.ir.backend.js.ic.CacheUpdater.getExportedSignaturesAndAddMetadata-gNUL48g(CacheUpdater.kt:351)
        at org.jetbrains.kotlin.ir.backend.js.ic.CacheUpdater.rebuildDirtySourceMetadata(CacheUpdater.kt:403)
        at org.jetbrains.kotlin.ir.backend.js.ic.CacheUpdater.actualizeCaches(CacheUpdater.kt:704)
        at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:300)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:183)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:72)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:101)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1645)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

To repro:
```
git clone https://github.com/cashapp/redwood.git
cd redwood
git checkout colin/kotlin_18
./gradlew build
```

**Comment by JakeWharton** [comment]
We are only using the runtime and compiler, not Compose UI. This error occurs with runtime-1.3.0-rc05 and compiler-1.4.0-rc02 with Kotlin 1.8.0.

**Comment by eymar** [comment]
Thank you for reporting!

"1.4.0-rc03" has a fix for this issue.

**Comment by eymar** [comment]
The bug was fixed. Closing this issue.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2660">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
