### ISSUE TITLE
Skiko Linux binary depends on dynamically linked libc++

### ISSUE THREAD

**Issue by theapache64** [JetBrains/compose-jb#273]
When `run` executed, I am getting build error.

**Stacktrace**

```
7:08:39 AM: Executing task 'run'...

> Task :wrapper

BUILD SUCCESSFUL in 103ms
1 actionable task: 1 executed
> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :inspectClassesForKotlinIC UP-TO-DATE
> Task :jar UP-TO-DATE

> Task :run

BUILD SUCCESSFUL in 1s
4 actionable tasks: 1 executed, 3 up-to-date
java.lang.UnsatisfiedLinkError: /home/theapache64/.skiko/92d528bd0f0b085330000592a5dbc97e63d8b8f258b56d931579e47e178f37ce/libskiko.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/theapache64/.skiko/92d528bd0f0b085330000592a5dbc97e63d8b8f258b56d931579e47e178f37ce/libskiko.so)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2407)
	at java.base/java.lang.Runtime.load0(Runtime.java:747)
	at java.base/java.lang.System.load(System.java:1857)
	at org.jetbrains.skiko.Library.loadOrGet(Library.kt:25)
	at org.jetbrains.skiko.Library.load(Library.kt:46)
	at org.jetbrains.skija.CustomLoader.run(CustomLoader.kt:5)
	at org.jetbrains.skija.impl.Library.staticLoad(Library.java:21)
	at org.jetbrains.skija.PictureRecorder.<clinit>(PictureRecorder.java:8)
	at androidx.compose.desktop.ComposeLayer.<init>(ComposeLayer.kt:70)
	at androidx.compose.desktop.ComposeWindow.<init>(ComposeWindow.kt:26)
	at androidx.compose.desktop.AppWindow.<init>(AppWindow.kt:102)
	at androidx.compose.desktop.AppWindow.<init>(AppWindow.kt)
	at androidx.compose.desktop.AppWindowKt$Window$1.run(AppWindow.kt:72)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at androidx.compose.desktop.ComposeLayer.<init>(ComposeLayer.kt:70)
	at androidx.compose.desktop.ComposeWindow.<init>(ComposeWindow.kt:26)
	at androidx.compose.desktop.AppWindow.<init>(AppWindow.kt:102)
	at androidx.compose.desktop.AppWindow.<init>(AppWindow.kt)
	at androidx.compose.desktop.AppWindowKt$Window$1.run(AppWindow.kt:72)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Library file libskija.so not found in /
	at org.jetbrains.skija.impl.Library._extract(Library.java:85)
	at org.jetbrains.skija.impl.Library.load(Library.java:50)
	at org.jetbrains.skija.impl.Library.staticLoad(Library.java:32)
	at org.jetbrains.skija.PictureRecorder.<clinit>(PictureRecorder.java:8)
	... 18 more
Caused by: java.lang.IllegalArgumentException: Library file libskija.so not found in /
	at org.jetbrains.skija.impl.Library._extract(Library.java:68)
	... 21 more
7:08:41 AM: Task execution finished 'run'.

```
FYI, the `libskiko.so` exist in the expected path.

```bash
~$ stat /home/theapache64/.skiko/92d528bd0f0b085330000592a5dbc97e63d8b8f258b56d931579e47e178f37ce/libskiko.so
  File: '/home/theapache64/.skiko/92d528bd0f0b085330000592a5dbc97e63d8b8f258b56d931579e47e178f37ce/libskiko.so'
  Size: 33949752  	Blocks: 66320      IO Block: 4096   regular file
Device: 812h/2066d	Inode: 6565195     Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/theapache64)   Gid: ( 1000/theapache64)
Access: 2021-01-15 06:54:16.494249012 +0530
Modify: 2021-01-15 06:54:16.482248896 +0530
Change: 2021-01-15 06:54:16.482248896 +0530
```

**OS : Ubuntu 16.04**

**IntelliJ Version**

```bash
IntelliJ IDEA 2020.3.1 (Community Edition)
Build #IC-203.6682.168, built on December 29, 2020
Runtime version: 11.0.9.1+11-b1145.63 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.15.0-129-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 6

Current Desktop: Unity
```

Any idea how to fix this ?

**Comment by kirill-grouchnikov** [comment]
Probably the most relevant part is `version GLIBCXX_3.4.22 not found`

**Comment by kirill-grouchnikov** [comment]
See if this helps:

```
apt-get update
apt-get install libstdc++6
```

If it does, they might want to add it to the readme

**Comment by theapache64** [comment]
@kirill-grouchnikov I have that already installed.

```bash
~$ stat /usr/lib/x86_64-linux-gnu/libstdc++.so.6
  File: '/usr/lib/x86_64-linux-gnu/libstdc++.so.6' -> 'libstdc++.so.6.0.21'
  Size: 19        	Blocks: 0          IO Block: 4096   symbolic link
Device: 812h/2066d	Inode: 12584966    Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-01-14 19:18:58.796433104 +0530
Modify: 2019-10-05 00:06:22.000000000 +0530
Change: 2019-11-06 06:31:47.524375702 +0530
 Birth: -
```

**Comment by kirill-grouchnikov** [comment]
Is that version in there? `strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX`

**Comment by theapache64** [comment]
@kirill-grouchnikov That was the issue, I was having an old version `(GLIBCXX_3.4.21)`. I've installed the new version using 

```bash
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9
sudo apt-get upgrade libstdc++6
```

Thanks for your time  @kirill-grouchnikov 

![mp4 mp4](https://user-images.githubusercontent.com/9678279/104672588-0e85c480-5706-11eb-90d8-2f4d3314b7fd.gif)

**Comment by kirill-grouchnikov** [comment]
Maybe this needs to be reopened for the project devs to add some kind of a section of building on Linux

**Comment by theapache64** [comment]
I think I can create a separate issue for that. Thanks for noticing :+1:

**Comment by theapache64** [comment]
Yeah, that's a good idea. 

Reopening to update docs

**Comment by olonho** [comment]
Shall be fixed with https://github.com/JetBrains/skiko/commit/91e9bd02f56ae8ed4a628344c237f1097d80e99c

**Comment by theapache64** [comment]
@olonho Okay. Feel free to close this issue when the fix merged with a public release.

**Comment by jimgoog** [comment]
@olonho I am getting the same error on a fresh install of Ubuntu 16.04 (uncheck the 'install updates on installation' box) even with `build154` which presumably includes JetBrains/skiko@91e9bd0 since that was a month ago?  Repro steps in https://github.com/JetBrains/compose-jb/issues/275#issuecomment-781789808

**Comment by jimgoog** [comment]
And to be clear, it occurs not just when building the app, but also when running a pre-packaged app that was packaged by someone else.

**Comment by olonho** [comment]
Indeed previous fix was wrong, maybe smth like 
```
diff --git a/skiko/build.gradle.kts b/skiko/build.gradle.kts
index aeb56d3..358d431 100644
--- a/skiko/build.gradle.kts
+++ b/skiko/build.gradle.kts
@@ -366,6 +366,7 @@ tasks.withType(LinkSharedLibrary::class.java).configureEach {
         OS.Linux -> {
             linkerArgs.addAll(
                 listOf(
+                    "-Wl,-Bstatic", "-lstdc++", "-Wl,-Bdynamic",
                     "-lGL",
                     "-lfontconfig",
                     // Hack to fix problem with linker not always finding certain declarations.
```
shall help.

**Comment by olonho** [comment]
Shall be actually fixed with https://github.com/JetBrains/skiko/commit/b25d00bb6f14756e1518c39e8dc0daf9c32342d2

**Comment by jamesward** [comment]
I was able to workaround this with:
```
val os = System.getProperty("os.name")
val currentTarget = when {
  os.equals("Mac OS X", ignoreCase = true) -> "macos"
  os.startsWith("Win", ignoreCase = true) -> "windows"
  os.startsWith("Linux", ignoreCase = true) -> "linux"
  else -> error("Unknown OS name: $os")
}
runtimeOnly("org.jetbrains.skiko:skiko-jvm-runtime-${currentTarget}-x64:0.2.33")
```

**Comment by akurasov** [comment]
Does anyone still have this issue with the latest skiko fix?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5540">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
