### ISSUE TITLE
RuntimeException: Can't wrap nullptr

### ISSUE THREAD

**Issue by lbensaad** [JetBrains/compose-jb#279]
OS: Ubuntu 20.04.1 LTS ;  5.4.0-58-generic 64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64  GNU/Linux
GNOME: 3.36.3
Kotlin: 1.4.21
Compose Desktop: 0.3.0-build140
JDK: openjdk version "1.8.0_242-release"
GPU: GeForce GT 540M 
NVIDA Driver: 390.138

When I run this simple code:
`fun main() = Window {}`

I get black window and this exception.

> Task :MainKt.main()
Exception in thread "AWT-EventQueue-0 @coroutine#2" java.lang.RuntimeException: Can't wrap nullptr
	at org.jetbrains.skija.impl.Native.<init>(Native.java:13)
	at org.jetbrains.skija.impl.Managed.<init>(Managed.java:15)
	at org.jetbrains.skija.impl.Managed.<init>(Managed.java:11)
	at org.jetbrains.skija.impl.RefCnt.<init>(RefCnt.java:8)
	at org.jetbrains.skija.DirectContext.<init>(DirectContext.java:26)
	at org.jetbrains.skiko.RenderTargetsKt.makeGLContext(RenderTargets.kt:6)
	at org.jetbrains.skiko.SkiaLayer.draw(SkiaLayer.kt:57)
	at org.jetbrains.skiko.HardwareLayer.redrawLayer(Native Method)
	at androidx.compose.desktop.ComposeLayer.onFrame(ComposeLayer.kt:77)
	at androidx.compose.desktop.ComposeLayer$onFrame$1.invokeSuspend(ComposeLayer.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Can't wrap nullptr
	at org.jetbrains.skija.impl.Native.<init>(Native.java:13)
	at org.jetbrains.skija.impl.Managed.<init>(Managed.java:15)
	at org.jetbrains.skija.impl.Managed.<init>(Managed.java:11)
	at org.jetbrains.skija.impl.RefCnt.<init>(RefCnt.java:8)
	at org.jetbrains.skija.DirectContext.<init>(DirectContext.java:26)
	at org.jetbrains.skiko.RenderTargetsKt.makeGLContext(RenderTargets.kt:6)
	at org.jetbrains.skiko.SkiaLayer.draw(SkiaLayer.kt:57)
	at org.jetbrains.skiko.HardwareLayer.redrawLayer(Native Method)
	at org.jetbrains.skiko.HardwareLayer.display(HardwareLayer.kt:22)
	at org.jetbrains.skiko.HardwareLayer.paint(HardwareLayer.kt:17)
	at java.desktop/sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
	at java.desktop/sun.awt.X11.XRepaintArea.paintComponent(XRepaintArea.java:66)
	at java.desktop/sun.awt.RepaintArea.paint(RepaintArea.java:240)
	at java.desktop/sun.awt.X11.XComponentPeer.handleEvent(XComponentPeer.java:549)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5090)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by kirill-grouchnikov** [comment]
Isn't Java 11 the minimum required for Compose Desktop?

**Comment by lbensaad** [comment]
you are right @kirill-grouchnikov  it is jdk 11. and the issue disappeared after i restarted my pc so i am closing this issue

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5535">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
