### ISSUE TITLE
Runtime crash. Can't update example TodoApp and Decompose to 0.3.0-build140.

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-jb#283]
STR:
1. Checkout Decompose [0.1.6-crash](https://github.com/arkivanov/Decompose/tree/0.1.6-crash) branch
2. Publish Decompose locally
3. Checkout arkivanov/compose-jb fork branch [build140-crash](https://github.com/arkivanov/compose-jb/tree/build140-crash)
4. Run todoapp desktop app

AR:
Runtime crash:
```
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: com/arkivanov/decompose/extensions/compose/jetbrains/RouterStateComposableKt$children$3 (wrong name: com/arkivanov/decompose/extensions/compose/jetbrains/RouterStateComposableKt$Children$3)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.arkivanov.decompose.extensions.compose.jetbrains.RouterStateComposableKt.Children(RouterStateComposable.kt:36)
	at example.todo.common.ui.TodoRootUiKt.TodoRootContent(TodoRootUi.kt:10)
	at example.todo.desktop.MainKt$main$2$1$1$1.invoke(Main.kt:32)
	at example.todo.desktop.MainKt$main$2$1$1$1.invoke(Main.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
	at androidx.compose.desktop.DesktopThemeKt.DesktopTheme(DesktopTheme.kt:54)
	at example.todo.desktop.MainKt$main$2$1$1.invoke(Main.kt:31)
	at example.todo.desktop.MainKt$main$2$1$1.invoke(Main.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
	at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:246)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:83)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
	at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:74)
	at example.todo.desktop.MainKt$main$2$1.invoke(Main.kt:30)
	at example.todo.desktop.MainKt$main$2$1.invoke(Main.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
	at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:111)
	at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.ui.layout.LayoutKt.Layout(Layout.kt:668)
	at androidx.compose.material.SurfaceKt.SurfaceLayout(Surface.kt:137)
	at androidx.compose.material.SurfaceKt.Surface-biUpMIw(Surface.kt:102)
	at example.todo.desktop.MainKt$main$2.invoke(Main.kt:29)
	at example.todo.desktop.MainKt$main$2.invoke(Main.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.desktop.AppWindowKt$Window$1$1.invoke(AppWindow.kt:88)
	at androidx.compose.desktop.AppWindowKt$Window$1$1.invoke(AppWindow.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.desktop.AppWindow$show$1.invoke(AppWindow.kt:435)
	at androidx.compose.desktop.AppWindow$show$1.invoke(AppWindow.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
	at androidx.compose.desktop.AppWindow$onCreate$1.invoke(AppWindow.kt:409)
	at androidx.compose.desktop.AppWindow$onCreate$1.invoke(AppWindow.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.ui.platform.DesktopSelectionKt$DesktopSelectionContainer$4$1.invoke(DesktopSelection.kt:121)
	at androidx.compose.ui.platform.DesktopSelectionKt$DesktopSelectionContainer$4$1.invoke(DesktopSelection.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.ui.layout.LayoutKt.Layout(Layout.kt:668)
	at androidx.compose.ui.platform.DesktopSelectionKt.Wrap(DesktopSelection.kt:37)
	at androidx.compose.ui.platform.DesktopSelectionKt.access$Wrap(DesktopSelection.kt)
	at androidx.compose.ui.platform.DesktopSelectionKt$DesktopSelectionContainer$4.invoke(DesktopSelection.kt:120)
	at androidx.compose.ui.platform.DesktopSelectionKt$DesktopSelectionContainer$4.invoke(DesktopSelection.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
	at androidx.compose.ui.platform.DesktopSelectionKt.DesktopSelectionContainer(DesktopSelection.kt:119)
	at androidx.compose.ui.platform.DesktopSelectionKt.DesktopSelectionContainer(DesktopSelection.kt:61)
	at androidx.compose.ui.platform.WrapperKt$setContent$1$1.invoke(Wrapper.kt:45)
	at androidx.compose.ui.platform.WrapperKt$setContent$1$1.invoke(Wrapper.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
	at androidx.compose.ui.platform.AmbientsKt.ProvideCommonAmbients(Ambients.kt:290)
	at androidx.compose.ui.platform.WrapperKt$ProvideDesktopAmbients$1.invoke(Wrapper.kt:66)
	at androidx.compose.ui.platform.WrapperKt$ProvideDesktopAmbients$1.invoke(Wrapper.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
	at androidx.compose.ui.platform.WrapperKt.ProvideDesktopAmbients(Wrapper.kt:62)
	at androidx.compose.ui.platform.WrapperKt.access$ProvideDesktopAmbients(Wrapper.kt)
	at androidx.compose.ui.platform.WrapperKt$setContent$1.invoke(Wrapper.kt:44)
	at androidx.compose.ui.platform.WrapperKt$setContent$1.invoke(Wrapper.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.ComposerKt.invokeComposable(Composer.kt:2906)
	at androidx.compose.runtime.Composer.composeInitial(Composer.kt:2046)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:566)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:109)
	at androidx.compose.ui.platform.WrapperKt.setContent(Wrapper.kt:43)
	at androidx.compose.desktop.ComposeLayer.setContent$ui(ComposeLayer.kt:311)
	at androidx.compose.desktop.ComposeWindow.setContent(ComposeWindow.kt:54)
	at androidx.compose.desktop.AppWindow.onCreate(AppWindow.kt:408)
	at androidx.compose.desktop.AppWindow.show(AppWindow.kt:433)
	at androidx.compose.desktop.AppWindow.show$default(AppWindow.kt:424)
	at androidx.compose.desktop.AppWindowKt$Window$1.run(AppWindow.kt:87)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

PS: `build-135` works just fine.

**Comment by olonho** [comment]
Which platform is that? Rename one of children/Children in your code to smth else.

**Comment by arkivanov** [comment]
It is macOS. I will try renaming, thanks!

**Comment by arkivanov** [comment]
Removing deprecated `children(...)` functions fixed the issue. But this looks like a workaround, having both `children` and `Children` functions is a valid case. If you think there is nothing to fix here, please close the issue.

**Comment by olonho** [comment]
Problem is rather fundamental, and related to the fact, that names of generated .class files for entities that only differs in case end up being files with the same properties. macOS and Windows by default has case insensitive FS, so only one of `Children.class` and `children.class` actually exists. There's nothing to fix on Compose side, it's pretty generic Kotlin/JVM feature/limitation.

**Comment by arkivanov** [comment]
Maybe the compilation could fail in this case on such systems?

**Comment by olonho** [comment]
There are issues fro that in Kotlin issue tracker: see https://youtrack.jetbrains.com/issue/KT-13847 https://youtrack.jetbrains.com/issue/KT-17467 https://youtrack.jetbrains.com/issue/KT-17822

**Comment by arkivanov** [comment]
Thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5531">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
