### ISSUE TITLE
Problem with fonts on the Android platform

### ISSUE THREAD

**Issue by mezgoodle** [JetBrains/compose-jb#333]
When I run an application with a custom font on Android, I get this error (everything works fine on the Desktop):
Build version -> 0.3.0-build143
```
E/AndroidRuntime: FATAL EXCEPTION: main Process: me.max.android, PID: 7905 java.lang.IllegalStateException: Cannot create Typeface from ResourceFont(resId=0, weight=FontWeight(weight=400), style=Normal) at androidx.compose.ui.text.platform.TypefaceAdapter.create(TypefaceAdapter.kt:243) at androidx.compose.ui.text.platform.TypefaceAdapter.create(TypefaceAdapter.kt:143) at androidx.compose.ui.text.platform.extensions.TextPaintExtensionsKt.createTypeface(TextPaintExtensions.kt:132) at androidx.compose.ui.text.platform.extensions.TextPaintExtensionsKt.applySpanStyle(TextPaintExtensions.kt:54) at androidx.compose.ui.text.platform.AndroidParagraphIntrinsics.<init>(AndroidParagraphIntrinsics.kt:66) at androidx.compose.ui.text.platform.AndroidParagraphIntrinsicsKt.ActualParagraphIntrinsics(AndroidParagraphIntrinsics.kt:128) at androidx.compose.ui.text.ParagraphIntrinsicsKt.ParagraphIntrinsics(ParagraphIntrinsics.kt:54) at androidx.compose.ui.text.MultiParagraphIntrinsics.<init>(MultiParagraphIntrinsics.kt:76) at androidx.compose.ui.text.TextDelegate.layoutIntrinsics(TextDelegate.kt:116) at androidx.compose.ui.text.TextDelegate.layoutText-urungq4(TextDelegate.kt:140) at androidx.compose.ui.text.TextDelegate.layout-BAnaFRY(TextDelegate.kt:217) at androidx.compose.foundation.text.TextController$measure$1.invoke(CoreText.kt:270) at androidx.compose.foundation.text.TextController$measure$1.invoke(Unknown Source:13) at androidx.compose.ui.layout.LayoutKt$measureBlocksOf$1.measure-8A2P9vY(Layout.kt:145) at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:44) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-za8Wrwc(GraphicsLayerModifier.kt:210) at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.foundation.layout.PaddingModifier.measure-za8Wrwc(Padding.kt:215) at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:93) at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(Unknown Source:0) at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:131) at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_debug(OwnerSnapshotObserver.kt:78) at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_debug(OwnerSnapshotObserver.kt:66) at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:92) at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:65) at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1196) at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasureBlocks$1.invoke(RowColumnImpl.kt:88) at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasureBlocks$1.invoke(Unknown Source:13) at
androidx.compose.ui.layout.LayoutKt$measureBlocksOf$1.measure-8A2P9vY(Layout.kt:145) E/AndroidRuntime: at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:44) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:93) at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(Unknown Source:0) at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:131) at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_debug(OwnerSnapshotObserver.kt:78) at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_debug(OwnerSnapshotObserver.kt:66) at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:92) at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:65) at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1196) at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Box.kt:112) at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Unknown Source:13) at androidx.compose.ui.layout.LayoutKt$MeasuringIntrinsicsMeasureBlocks$1.measure-8A2P9vY(Layout.kt:391) at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:44) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.foundation.layout.FillModifier.measure-za8Wrwc(Size.kt:650) at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.foundation.layout.FillModifier.measure-za8Wrwc(Size.kt:650) at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:93) at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(Unknown Source:0) at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:131) at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_debug(OwnerSnapshotObserver.kt:78) at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_debug(OwnerSnapshotObserver.kt:66) at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:92) at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:65) at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1196) at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Box.kt:112) at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Unknown Source:13) at androidx.compose.ui.layout.LayoutKt$MeasuringIntrinsicsMeasureBlocks$1.measure-8A2P9vY(Layout.kt:391) at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:44) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-za8Wrwc(GraphicsLayerModifier.kt:210) at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-za8Wrwc(GraphicsLayerModifier.kt:210) at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at
androidx.compose.foundation.layout.FillModifier.measure-za8Wrwc(Size.kt:650) at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.foundation.layout.FillModifier.measure-za8Wrwc(Size.kt:650) at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:93) at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(Unknown Source:0) at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:131) at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_debug(OwnerSnapshotObserver.kt:78) at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_debug(OwnerSnapshotObserver.kt:66) at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:92) at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:65) at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1196) at androidx.compose.ui.layout.RootMeasureBlocks.measure-8A2P9vY(RootMeasureBlocks.kt:38) at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:44) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107) at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162) at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:93) at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(Unknown Source:0) at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1710) at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:126) at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_debug(OwnerSnapshotObserver.kt:78) at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_debug(OwnerSnapshotObserver.kt:66) at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:92) at androidx.compose.ui.node.LayoutNode.remeasure-BRTryo0$ui_debug(LayoutNode.kt:1203) at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-ivNzw_s(MeasureAndLayoutDelegate.kt:170) at androidx.compose.ui.node.MeasureAndLayoutDelegate.access$doRemeasure-ivNzw_s(Unknown Source:0) at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:211) at androidx.compose.ui.platform.AndroidComposeView.onMeasure(AndroidComposeView.kt:466) at android.view.View.measure(View.java:25029) at androidx.compose.ui.platform.AbstractComposeView.onMeasure(ComposeView.kt:221) at android.view.View.measure(View.java:25029) at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968) at android.widget.FrameLayout.onMeasure(FrameLayout.java:194) at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146) E/AndroidRuntime:
at android.view.View.measure(View.java:25029) at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968) at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552) at android.widget.LinearLayout.measureVertical(LinearLayout.java:842) at android.widget.LinearLayout.onMeasure(LinearLayout.java:721) at android.view.View.measure(View.java:25029) at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968) at android.widget.FrameLayout.onMeasure(FrameLayout.java:194) at android.view.View.measure(View.java:25029) at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968) at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552) at android.widget.LinearLayout.measureVertical(LinearLayout.java:842) at android.widget.LinearLayout.onMeasure(LinearLayout.java:721) at android.view.View.measure(View.java:25029) at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968) at android.widget.FrameLayout.onMeasure(FrameLayout.java:194) at com.android.internal.policy.DecorView.onMeasure(DecorView.java:775) at android.view.View.measure(View.java:25029) at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3245) at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2000) at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2305) at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1888) at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8043) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:969) at android.view.Choreographer.doCallbacks(Choreographer.java:793) at android.view.Choreographer.doFrame(Choreographer.java:728) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954) at android.os.Handler.handleCallback(Handler.java:914) at android.os.Handler.dispatchMessage(Handler.java:100) at android.os.Looper.loop(Looper.java:224) at android.app.ActivityThread.main(ActivityThread.java:7551) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
```
Android Resources:
```kt
actual fun font(name: String, res: String, weight: FontWeight, style: FontStyle): Font {
    val context = AmbientContext.current
    val id = context.resources.getIdentifier(res, "font", context.packageName)
    return androidx.compose.ui.text.font.font(id, weight, style)
}
```
My custom font code:
```kt
fun softLineBook() = fontFamily(
        font(
            "SoftLine Book",
            "soft_line_book",
            FontWeight.Normal,
            FontStyle.Normal
      ),
  )
```

**Comment by olonho** [comment]
This kind of problem unlikely belongs to this issue tracker. See https://source.android.com/setup/contribute/report-bugs for reporting issue to Compose tracker.

**Comment by olonho** [comment]
Closing for now, please update with Androidx issue link when created.

**Comment by emilyyikyak** [comment]
@mezgoodle Was a solution ever found? I think I'm seeing a similar issue.

**Comment by wakaztahir** [comment]
This issue should be reopened as on some devices this exception occurs

Brand:HUAWEI
Model:荣耀畅玩7X
Version:Android 7.0

On most devices its working fine but on some devices it cannot load fonts 

```
Caused by android.content.res.Resources$NotFoundException: Font resource ID #0x7f080003 could not be retrieved.
       at androidx.core.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:4)
       at androidx.core.content.res.ResourcesCompat.getFont(ResourcesCompat.java:6)
       at androidx.compose.ui.platform.AndroidFontResourceLoader.load(AndroidFontResourceLoader.java:6)
       at androidx.compose.ui.platform.AndroidFontResourceLoader.load(AndroidFontResourceLoader.java:6)
       at androidx.compose.ui.text.platform.TypefaceAdapter.create-xC2X5gM(TypefaceAdapter.java:13)
       at androidx.compose.ui.text.platform.extensions.TextPaintExtensions_androidKt.createTypeface(TextPaintExtensions_androidKt.java:25)
       at androidx.compose.ui.text.platform.AndroidParagraphIntrinsics.<init>(AndroidParagraphIntrinsics.java:25)
       at androidx.compose.ui.text.platform.AndroidParagraphIntrinsics_androidKt.ActualParagraphIntrinsics(AndroidParagraphIntrinsics_androidKt.java:62)
       at androidx.compose.ui.text.ParagraphIntrinsicsKt.ParagraphIntrinsics(ParagraphIntrinsicsKt.java:62)
       at androidx.compose.ui.text.MultiParagraphIntrinsics.<init>(MultiParagraphIntrinsics.java:62)
       at androidx.compose.foundation.text.TextDelegate.layoutIntrinsics(TextDelegate.java)
       at androidx.compose.foundation.text.TextDelegate.layoutText-K40F9xA(TextDelegate.java:67)
       at androidx.compose.foundation.text.TextController$measurePolicy$1.measure-3p2s80s(TextController.java:6)
       at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.java:10)
       at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.java:3)
       at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.java:3)
       at androidx.compose.ui.layout.Placeable.getWidth(Placeable.java)
       at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.java:5)
       at androidx.compose.foundation.layout.PaddingModifier.measure-3p2s80s(PaddingModifier.java:8)
       at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.java:5)
       at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.java:3)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.java:48)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.java:48)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.java:21)
       at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.java:21)
       at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.java:10)
       at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.java)
       at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasurePolicy$1.measure-3p2s80s(RowColumnImplKt.java:8)
       at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.java:10)
       at androidx.compose.foundation.layout.PaddingModifier.measure-3p2s80s(PaddingModifier.java:8)
       at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.java:5)
       at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.java:3)
       at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.java:3)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.java:48)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.java:48)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.java:21)
       at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.java:21)
       at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.java:10)
       at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.java)
       at androidx.compose.ui.layout.Placeable.getWidth(Placeable.java)
       at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.java:10)
       at androidx.compose.ui.layout.Placeable.getWidth(Placeable.java)
       at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.java:5)
       at androidx.compose.ui.layout.Placeable.getWidth(Placeable.java)
       at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.java:5)
       at androidx.compose.ui.layout.Placeable.getWidth(Placeable.java)
       at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.java:5)
       at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.java:3)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.java:48)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.java:48)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.java:21)
       at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.java:21)
       at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.java:10)
       at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.java)
       at androidx.compose.ui.layout.Placeable.getWidth(Placeable.java)
       at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.java:10)
       at androidx.compose.ui.layout.Placeable.getWidth(Placeable.java)
       at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.java:5)
       at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.java:3)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.java:48)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.java:48)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.java:21)
       at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.java:21)
       at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.java:7)
       at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure(MeasureAndLayoutDelegate.java:11)
       at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtree(MeasureAndLayoutDelegate.java:7)
       at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtree(MeasureAndLayoutDelegate.java:9)
       at androidx.compose.ui.platform.AndroidComposeView.forceMeasureTheSubtree(AndroidComposeView.java)
       at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.java:6)
       at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.java:10)
       at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.java)
       at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1.measure-3p2s80s(BoxKt.java:8)
       at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.java:10)
       at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.java:3)
       at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.java:41)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.java:41)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.java:41)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.java:21)
       at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.java:21)
       at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.java:7)
       at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure(MeasureAndLayoutDelegate.java:11)
       at androidx.compose.ui.node.MeasureAndLayoutDelegate.access$remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.java:4)
       at androidx.compose.ui.platform.AndroidComposeView.onMeasure(AndroidComposeView.java:12)
       at android.view.View.measure(View.java:19937)
       at androidx.compose.ui.platform.AbstractComposeView.internalOnMeasure$ui_release(AbstractComposeView.java)
       at androidx.compose.ui.platform.AbstractComposeView.onMeasure(AbstractComposeView.java)
       at android.view.View.measure(View.java:19937)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:19937)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1489)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:775)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
       at android.view.View.measure(View.java:19937)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:729)
       at android.view.View.measure(View.java:19937)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2442)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1488)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1747)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1372)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6782)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:933)
       at android.view.Choreographer.doCallbacks(Choreographer.java:742)
       at android.view.Choreographer.doFrame(Choreographer.java:674)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:919)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6605)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:999)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:889)
```

**Comment by darvld** [comment]
@wakaztahir The issue was closed since it should be reported to the Jetpack Compose developers on a different issue tracker. This GitHub repository is only for **Multiplatform** Compose. The bug seems to be related to **Jetpack** Compose, which is handled by the Google team. You should provide the stack trace and other related information in the relevant issue created on the Google Issue Tracker.
