### ISSUE TITLE
"java.lang.NoSuchMethodError" error for Compose generated code at runtime

### ISSUE THREAD

**Issue by audkar** [JetBrains/compose-jb#360]
_There is so much moving parts that I am not sure who causes root issue (IR, Compose plugin or Gradle caching). Sorry if I am rising issue in a wrong project._

#### Problem

Runtime error is thrown in application when I add some specific code to project, compile, make source code change and re-run application.

#### Steps to reproduce

1. Clone project from repository and select branch [compose-error](https://github.com/audkar/compose-sandbox/compare/compose-error)
```sh
git clone https://github.com/audkar/compose-sandbox.git && cd compose-sandbox && git checkout compose-error
```
2. Run application once (should succeed)
```sh
./gradlew :desktop:run
```
3. Change something in source code. e.g. I change String `User1` -> `User2` in [App file](https://github.com/audkar/compose-sandbox/blob/compose-error/common/src/commonMain/kotlin/app/nameplaceholder/common/App.kt#L68)
4. Re-run application
```sh
./gradlew :desktop:run
```
5. Error at runtime should happen
<details>
  <summary>Stacktrace printed at application runtime</summary>

Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: 'app.nameplaceholder.common.IViewModel app.nameplaceholder.common.DesktopWrappingViewModelKt.vModel(java.lang.String, kotlin.jvm.functions.Function0, androidx.compose.runtime.Composer, int, int)'
	at app.nameplaceholder.common.AppKt.App(App.kt:63)
	at ComposableSingletons$MainKt$lambda-1$1.invoke(main.kt:12)
	at ComposableSingletons$MainKt$lambda-1$1.invoke(main.kt:7)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:120)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
	at androidx.compose.desktop.AppWindowKt$Window$1$1.invoke(AppWindow.kt:91)
	at androidx.compose.desktop.AppWindowKt$Window$1$1.invoke(AppWindow.kt:90)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:120)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
	at androidx.compose.desktop.AppWindow$show$1.invoke(AppWindow.kt:439)
	at androidx.compose.desktop.AppWindow$show$1.invoke(AppWindow.kt:437)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:120)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:191)
	at androidx.compose.desktop.AppWindow$onCreate$1.invoke(AppWindow.kt:412)
	at androidx.compose.desktop.AppWindow$onCreate$1.invoke(AppWindow.kt:411)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:120)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
	at androidx.compose.ui.platform.WrapperKt$setContent$1$1.invoke(Wrapper.kt:41)
	at androidx.compose.ui.platform.WrapperKt$setContent$1$1.invoke(Wrapper.kt:40)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:120)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:191)
	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:121)
	at androidx.compose.ui.platform.WrapperKt$ProvideDesktopAmbients$1.invoke(Wrapper.kt:60)
	at androidx.compose.ui.platform.WrapperKt$ProvideDesktopAmbients$1.invoke(Wrapper.kt:59)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:120)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:191)
	at androidx.compose.ui.platform.WrapperKt.ProvideDesktopAmbients(Wrapper.kt:56)
	at androidx.compose.ui.platform.WrapperKt.access$ProvideDesktopAmbients(Wrapper.kt:1)
	at androidx.compose.ui.platform.WrapperKt$setContent$1.invoke(Wrapper.kt:40)
	at androidx.compose.ui.platform.WrapperKt$setContent$1.invoke(Wrapper.kt:39)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:120)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
	at androidx.compose.runtime.ComposerKt.invokeComposable(Composer.kt:3421)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime(Composer.kt:2606)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:240)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:527)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:236)
	at androidx.compose.ui.platform.WrapperKt.setContent(Wrapper.kt:39)
	at androidx.compose.desktop.ComposeLayer.initOwner(ComposeLayer.kt:256)
	at androidx.compose.desktop.ComposeLayer.access$initOwner(ComposeLayer.kt:50)
	at androidx.compose.desktop.ComposeLayer$Wrapped.init(ComposeLayer.kt:83)
	at org.jetbrains.skiko.HardwareLayer.checkIsShowing(HardwareLayer.kt:30)
	at org.jetbrains.skiko.HardwareLayer.access$checkIsShowing(HardwareLayer.kt:7)
	at org.jetbrains.skiko.HardwareLayer$1.hierarchyChanged(HardwareLayer.kt:22)
	at java.desktop/java.awt.Component.processHierarchyEvent(Component.java:6781)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.Component.createHierarchyEvents(Component.java:5628)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1466)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1466)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1466)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1466)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1466)
	at java.desktop/java.awt.Component.show(Component.java:1680)
	at java.desktop/java.awt.Window.show(Window.java:1056)
	at java.desktop/java.awt.Component.show(Component.java:1717)
	at java.desktop/java.awt.Component.setVisible(Component.java:1664)
	at java.desktop/java.awt.Window.setVisible(Window.java:1028)
	at androidx.compose.desktop.ComposeWindow.setVisible(ComposeWindow.kt:86)
	at androidx.compose.desktop.AppWindow.show(AppWindow.kt:442)
	at androidx.compose.desktop.AppWindow.show$default(AppWindow.kt:428)
	at androidx.compose.desktop.AppWindowKt$Window$1.run(AppWindow.kt:90)
</details>

All subsequent attempts to run gradle compiled app always fails after source code modification. Only solution is to re-run Gradle with clean task added e.g `./gradew clean :desktop:run`

Environment: Linux

**Comment by jimgoog** [comment]
If `gradle clean` solves the issue, then it sounds like a gradle caching issue, and I'd suggest filing the bug with them.  Or you could possibly try filing it on the Kotlin compiler repository, as there may be something they can do to influence the cache.  But there isn't really anything we can do from the Compose side AFAIK.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6476">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
