### ISSUE TITLE
"Padding must be non-negative" after resizing window with Slider and Box

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#367]
```
import androidx.compose.desktop.Window
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.width
import androidx.compose.material.Slider
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

fun main() = Window {
    Row {
        val amount = remember { mutableStateOf(0f) }
        Slider(
            value = amount.value,
            onValueChange = amount::value::set,
            modifier = Modifier.weight(1f)
        )
        Box(Modifier.width(200.dp))
    }
}
```

1. move slider
2. resize window (decrease width)
3. runtime exception:
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Padding must be non-negative
	at androidx.compose.foundation.layout.PaddingModifier.<init>(Padding.kt:344)
	at androidx.compose.foundation.layout.PaddingModifier.<init>(Padding.kt)
	at androidx.compose.foundation.layout.PaddingKt.padding-qDBjuR0(Padding.kt:55)
	at androidx.compose.foundation.layout.PaddingKt.padding-qDBjuR0$default(Padding.kt:49)
	at androidx.compose.material.SliderKt.SliderImpl-hVCEMxE(Slider.kt:245)
	at androidx.compose.material.SliderKt.access$SliderImpl-hVCEMxE(Slider.kt:1)
	at androidx.compose.material.SliderKt$Slider$2.invoke(Slider.kt:177)
	at androidx.compose.material.SliderKt$Slider$2.invoke(Slider.kt:131)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:130)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
	at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1$measurables$1.invoke(BoxWithConstraints.kt:61)
	at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1$measurables$1.invoke(BoxWithConstraints.kt:61)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
	at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2$1.invoke(SubcomposeLayout.kt:168)
	at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2$1.invoke(SubcomposeLayout.kt:168)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
	at androidx.compose.runtime.ComposerKt.invokeComposable(Composer.kt:3415)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime(Composer.kt:2602)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:240)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:524)
	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime(Composer.kt:3021)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:236)
	at androidx.compose.ui.layout.SubcomposeLayoutState.subcomposeInto(SubcomposeLayout.kt:185)
	at androidx.compose.ui.layout.SubcomposeLayoutState.access$subcomposeInto(SubcomposeLayout.kt:101)
	at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2.invoke(SubcomposeLayout.kt:161)
	at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2.invoke(SubcomposeLayout.kt:159)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.withNoObservations(SnapshotStateObserver.kt:137)
	at androidx.compose.ui.node.OwnerSnapshotObserver.withNoSnapshotReadObservation$ui(OwnerSnapshotObserver.kt:49)
	at androidx.compose.ui.node.LayoutNode.withNoSnapshotReadObservation$ui(LayoutNode.kt:1088)
	at androidx.compose.ui.layout.SubcomposeLayoutState.subcompose(SubcomposeLayout.kt:159)
	at androidx.compose.ui.layout.SubcomposeLayoutState.subcompose(SubcomposeLayout.kt:153)
	at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1.invoke-0kLqBqw(BoxWithConstraints.kt:61)
	at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1.invoke(BoxWithConstraints.kt:59)
	at androidx.compose.ui.layout.SubcomposeLayoutState$createMeasureBlocks$1.measure-3p2s80s(SubcomposeLayout.kt:214)
	at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:44)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:93)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:92)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:121)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:75)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui(OwnerSnapshotObserver.kt:63)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:92)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:65)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1197)
	at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasureBlocks$1.invoke-3p2s80s(RowColumnImpl.kt:145)
	at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasureBlocks$1.invoke(RowColumnImpl.kt:62)
	at androidx.compose.ui.layout.LayoutKt$measureBlocksOf$1.measure-3p2s80s(Layout.kt:138)
	at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:44)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:93)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:92)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:121)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:75)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui(OwnerSnapshotObserver.kt:63)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:92)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:65)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1197)
	at androidx.compose.ui.layout.RootMeasureBlocks.measure-3p2s80s(RootMeasureBlocks.kt:38)
	at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:44)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:162)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:93)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:92)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1709)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:116)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:75)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui(OwnerSnapshotObserver.kt:63)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:92)
	at androidx.compose.ui.node.LayoutNode.remeasure-BRTryo0$ui(LayoutNode.kt:1204)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-0kLqBqw(MeasureAndLayoutDelegate.kt:170)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.access$doRemeasure-0kLqBqw(MeasureAndLayoutDelegate.kt:39)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:211)
	at androidx.compose.ui.platform.DesktopOwner.measureAndLayout(DesktopOwner.kt:191)
	at androidx.compose.ui.platform.DesktopOwners.onFrame(DesktopOwners.kt:112)
	at androidx.compose.desktop.ComposeLayer$1.onRender(ComposeLayer.kt:123)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.kt:91)
	at org.jetbrains.skiko.redrawer.WindowsOpenGLRedrawer.update(WindowsOpenGLRedrawer.kt:51)
	at org.jetbrains.skiko.redrawer.WindowsOpenGLRedrawer.redrawImmediately(WindowsOpenGLRedrawer.kt:43)
	at org.jetbrains.skiko.SkiaLayer.setBounds(SkiaLayer.kt:56)
	at java.desktop/java.awt.Component.resize(Component.java:2243)
	at java.desktop/java.awt.Component.setSize(Component.java:2228)
	at androidx.compose.desktop.ComposeWindow$1.componentResized(ComposeWindow.kt:42)
	at java.desktop/java.awt.AWTEventMulticaster.componentResized(AWTEventMulticaster.java:167)
	at java.desktop/java.awt.Component.processComponentEvent(Component.java:6440)
	at java.desktop/java.awt.Component.processEvent(Component.java:6394)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Window.processEvent(Window.java:2046)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5521">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
