### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by alialbaali** [JetBrains/compose-jb#369]
Getting an error while running a simple test
```kotlin

class DesktopTest {

    private val composeTestRule = createComposeRule()

    @Test
    fun myTest() {
        composeTestRule.setContent {

        }
    }
}
```
The error: 
```kotlin
lateinit property window has not been initialized
kotlin.UninitializedPropertyAccessException: lateinit property window has not been initialized
	at androidx.compose.ui.test.junit4.DesktopComposeTestRule.getWindow(DesktopComposeTestRule.kt:64)
	at androidx.compose.ui.test.junit4.DesktopComposeTestRule$setContent$1.invoke(DesktopComposeTestRule.kt:149)
	at androidx.compose.ui.test.junit4.DesktopComposeTestRule$setContent$1.invoke(DesktopComposeTestRule.kt:148)
	at androidx.compose.ui.test.junit4.DesktopComposeTestRuleKt$sam$java_util_concurrent_Callable$0.call(DesktopComposeTestRule.kt)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
Tested with compose 0.3.0-build148 and 0.3.0-build152
OS: Windows 10 20H2

**Comment by igordmn** [comment]
Add @get:Rule:

```
import org.junit.Rule
...

@get:Rule
private val composeTestRule = createComposeRule()
```

**Comment by alialbaali** [comment]
I added the annotation and still getting the same error.
There's also a hint appears on the IDE saying ( An accessor will not be generated for 'composeTestRule', so the annotation will not be written to the class file) on the ```@get:Rule```.

**Comment by igordmn** [comment]
My mistake, `val composeTestRule` should be public.

Changed comment above.

**Comment by alialbaali** [comment]
That seems to fix it. Thank you!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5519">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
