### ISSUE TITLE
Hello world application crashes on launch

### ISSUE THREAD

**Issue by ragunathjawahar** [JetBrains/compose-jb#453]
```
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: /Users/username/.skiko/9faa870d5839f80db248373470e3b914cdde28855e4b36c4e84ae940e5dd3412/libskiko-macos-x64.dylib: dlopen(/Users/username/.skiko/9faa870d5839f80db248373470e3b914cdde28855e4b36c4e84ae940e5dd3412/libskiko-macos-x64.dylib, 1): no suitable image found.  Did find:
	/Users/username/.skiko/9faa870d5839f80db248373470e3b914cdde28855e4b36c4e84ae940e5dd3412/libskiko-macos-x64.dylib: code signature in (/Users/username/.skiko/9faa870d5839f80db248373470e3b914cdde28855e4b36c4e84ae940e5dd3412/libskiko-macos-x64.dylib) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
	at java.base/java.lang.Runtime.load0(Runtime.java:765)
	at java.base/java.lang.System.load(System.java:1866)
	at org.jetbrains.skiko.Library.loadOrGet(Library.kt:24)
	at org.jetbrains.skiko.Library.load(Library.kt:49)
	at org.jetbrains.skiko.HardwareLayer.<clinit>(HardwareLayer.kt:10)
	at androidx.compose.desktop.ComposeLayer.<init>(ComposeLayer.desktop.kt:58)
	at androidx.compose.desktop.ComposeWindow.<init>(ComposeWindow.desktop.kt:31)
	at androidx.compose.desktop.AppWindow.<init>(AppWindow.desktop.kt:114)
	at androidx.compose.desktop.AppWindow.<init>(AppWindow.desktop.kt)
	at androidx.compose.desktop.AppWindow_desktopKt$Window$1.run(AppWindow.desktop.kt:83)
```

**build.gradle**
```groovy
import org.jetbrains.compose.compose
import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.4.30"
    id("org.jetbrains.compose") version "0.3.0"
}

group = "me.ragunath"
version = "1.0.0"

repositories {
    jcenter()
    mavenCentral()
    maven { url = uri("https://maven.pkg.jetbrains.space/public/p/compose/dev") }
}

dependencies {
    implementation(compose.desktop.currentOs)
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}

compose.desktop {
    application {
        mainClass = "MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "compose-m3"
        }
    }
}
```

**Comment by olonho** [comment]
Seems your JVM cannot load third-party binaries. Try another JVM, it's not normal.

**Comment by ragunathjawahar** [comment]
You are right, it runs on **corretto-11.0.10** but not on **adoptopenjdk-12**.

**Comment by olonho** [comment]
It's JDK bug.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6465">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
