### ISSUE TITLE
createDistributable is missing dependencies

### ISSUE THREAD

**Issue by SaiNageswarS** [JetBrains/compose-jb#464]
Getting following error in distributable

```
Exception in thread "main" java.lang.NoClassDefFoundError: java/net/http/HttpClient
	at com.kotlang.util.VersionVerificationUtil.<init>(VersionVerificationUtil.kt:12)
	at com.kotlang.MainKt.<clinit>(main.kt:12)
Caused by: java.lang.ClassNotFoundException: java.net.http.HttpClient
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more
Failed to launch JVM
```

However, uberjar is working.

Platform: Ubuntu
Java version: 15

https://github.com/SaiNageswarS/Omnishell/blob/6d603fbf0311a706c9d2e18526d6d24a01ef367c/src/main/kotlin/com/kotlang/util/VersionVerificationUtil.kt#L12

**Comment by SaiNageswarS** [comment]
Adding modules in nativeDistributions helped.

Ex: 
```
nativeDistributions {
            modules("java.net.http")
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "OmniShell"
        }
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6461">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
