### ISSUE TITLE
Modifier.border() Exception

### ISSUE THREAD

**Issue by Exidel** [JetBrains/compose-jb#485]
When you size down the window and parallel border lines stick in one it throw exception:
Exception in thread "AWT-EventQueue-0 @coroutine#2" java.lang.NullPointerException: Cannot read field "_left" because "r" is null

**Comment by jimgoog** [comment]
Can you please post a minimal repro that demonstrates the issue?

**Comment by Exidel** [comment]
![01](https://user-images.githubusercontent.com/80458677/110946217-ac38f100-834f-11eb-8e30-3e026b2d02ab.jpg)
![02](https://user-images.githubusercontent.com/80458677/110946236-b0fda500-834f-11eb-9639-c89fc5d27596.jpg)
![03](https://user-images.githubusercontent.com/80458677/110946250-b65aef80-834f-11eb-86a9-7a596cdebfde.jpg)

**Comment by igordmn** [comment]
Thanks!

I have exception with this example (Compose 0.3.2):
```
import androidx.compose.desktop.Window
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.requiredSize
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

fun main() = Window {
    Box(modifier = Modifier.requiredSize(1.dp, 1.dp).border(width = 10.dp, color = Color.Red))
}
```
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Rect::makeLTRB expected l <= r, got 6.25 > -5.25
	at org.jetbrains.skija.Rect.makeLTRB(Rect.java:31)
	at androidx.compose.ui.graphics.DesktopCanvas.drawRect(DesktopCanvas.desktop.kt:106)
	at androidx.compose.ui.graphics.drawscope.CanvasDrawScope.drawRect-sdLsPrE(CanvasDrawScope.kt:168)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawRect-sdLsPrE(LayoutNodeDrawScope.kt)
	at androidx.compose.ui.graphics.drawscope.DrawScope$DefaultImpls.drawRect-sdLsPrE$default(DrawScope.kt:379)
	at androidx.compose.foundation.BorderKt$border$2$1$4.invoke(Border.kt:195)
	at androidx.compose.foundation.BorderKt$border$2$1$4.invoke(Border.kt:142)
	at androidx.compose.ui.draw.DrawContentCacheModifier.draw(DrawModifier.kt:203)
	at androidx.compose.ui.node.ModifiedDrawNode.performDraw(ModifiedDrawNode.kt:109)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:195)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:80)
	at androidx.compose.ui.node.LayoutNodeWrapper$invoke$2.invoke(LayoutNodeWrapper.kt:209)
	at androidx.compose.ui.node.LayoutNodeWrapper$invoke$2.invoke(LayoutNodeWrapper.kt:208)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1714)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:116)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:75)
	at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:208)
	at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:50)
	at androidx.compose.ui.platform.SkijaLayer.performDrawLayer(SkijaLayer.desktop.kt:205)
	at androidx.compose.ui.platform.SkijaLayer.drawLayer(SkijaLayer.desktop.kt:171)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:190)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:791)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:122)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:195)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:70)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:195)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:70)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:195)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:70)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:195)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:70)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:195)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:791)
	at androidx.compose.ui.platform.DesktopOwner.draw(DesktopOwner.desktop.kt:278)
	at androidx.compose.ui.platform.DesktopOwner.render(DesktopOwner.desktop.kt:202)
	at androidx.compose.ui.platform.DesktopOwners.onFrame(DesktopOwners.desktop.kt:129)
	at androidx.compose.desktop.ComposeLayer$1.onRender(ComposeLayer.desktop.kt:123)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.kt:117)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer.update(Direct3DRedrawer.kt:42)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer.redrawImmediately(Direct3DRedrawer.kt:37)
	at org.jetbrains.skiko.SkiaLayer.paint(SkiaLayer.kt:68)
	at java.desktop/sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
	at java.desktop/sun.awt.RepaintArea.paint(RepaintArea.java:240)
	at java.desktop/sun.awt.windows.WComponentPeer.handleEvent(WComponentPeer.java:371)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5051)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

On Android this works, because Canvas in Android allows wrong values.

I think we should limit the values in DesktopCanvas as well (or disable checking them inside skija).

**Comment by Exidel** [comment]
that was on build 1.4.20 and 0.2.0
on 1.4.31 and 0.4.0 it's still throw exception:
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Rect::makeLTRB expected l <= r, got 2.0 > -1.0
but app still work with little condition like in #476, you need to resize window to redraw gui.

**Comment by olonho** [comment]
Think what we could do, is to add coercing check into `DesktopCanvas.drawRect`.

**Comment by Exidel** [comment]
Can't reproduce in build270. Closed

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6346">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
