### ISSUE TITLE
Exception when Backspace in an TextField containing Chinese characters

### ISSUE THREAD

**Issue by sumy7** [JetBrains/compose-jb#573]
Enter "你好" in the TextField(not copy, use Chinese Input Method, press 'nihao'). Use Backspace to delete all characters. No characters can be entered then.

version
```
    kotlin("jvm") version "1.4.31"
    id("org.jetbrains.compose") version "0.3.2"
```

exception
```
Exception in thread "AWT-EventQueue-0 @coroutine#1" java.lang.IllegalArgumentException: start cannot be negative. [start: -1]
	at androidx.compose.ui.text.TextRangeKt.packWithCheck(TextRange.kt:121)
	at androidx.compose.ui.text.TextRangeKt.TextRange(TextRange.kt:37)
	at androidx.compose.ui.text.input.EditingBuffer.delete$ui_text(EditingBuffer.kt:190)
	at androidx.compose.ui.text.input.DeleteSurroundingTextInCodePointsCommand.applyTo(EditCommand.kt:354)
	at androidx.compose.ui.text.input.EditProcessor.apply(EditProcessor.kt:92)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion.onEditCommand(TextFieldDelegate.kt:198)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion.access$onEditCommand(TextFieldDelegate.kt:90)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion$onFocus$textInputSession$1.invoke(TextFieldDelegate.kt:246)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion$onFocus$textInputSession$1.invoke(TextFieldDelegate.kt:246)
	at androidx.compose.ui.platform.DesktopPlatformInput.replaceInputMethodText$ui(DesktopPlatformInput.desktop.kt:138)
	at androidx.compose.ui.platform.DesktopOwners.onInputMethodEvent(DesktopOwners.desktop.kt:170)
	at androidx.compose.desktop.ComposeLayer$initCanvas$1$inputMethodTextChanged$1.invoke(ComposeLayer.desktop.kt:143)
	at androidx.compose.desktop.ComposeLayer$initCanvas$1$inputMethodTextChanged$1.invoke(ComposeLayer.desktop.kt:142)
	at androidx.compose.desktop.AWTDebounceEventQueue$job$1.invokeSuspend(AWTDebounceEventQueue.desktop.kt:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by akurasov** [comment]
Works fine in 1.0.0-beta6-dev462
