### ISSUE TITLE
Double textfield cause java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum -1 is less than minimum 0.

### ISSUE THREAD

**Issue by sonder-joker** [JetBrains/compose-jb#600]
Just double will cause this
https://github.com/sonder-joker/mirai-compose/blob/8c78c483eeff33d9d7308c26101e9bcdbca1ba3c/mirai-compose/src/main/kotlin/ui/feature/bot/state/BotNoLoginView.kt#L198
```
java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum -1 is less than minimum 0.
	at kotlin.ranges.RangesKt___RangesKt.coerceIn(_Ranges.kt:1103)
	at androidx.compose.foundation.text.selection.TextSelectionDelegateKt.adjustSelection(TextSelectionDelegate.kt:162)
	at androidx.compose.foundation.text.selection.TextFieldSelectionDelegateKt.getTextFieldSelection-pbSknfY(TextFieldSelectionDelegate.kt:60)
	at androidx.compose.foundation.text.selection.TextFieldSelectionManager.updateSelection(TextFieldSelectionManager.kt:622)
	at androidx.compose.foundation.text.selection.TextFieldSelectionManager.access$updateSelection(TextFieldSelectionManager.kt:56)
	at androidx.compose.foundation.text.selection.TextFieldSelectionManager$mouseSelectionObserver$1.onStart-3MmeM6k(TextFieldSelectionManager.kt:272)
	at androidx.compose.foundation.text.selection.TextSelectionMouseDetectorKt$mouseSelectionDetector$2$1.invokeSuspend(TextSelectionMouseDetector.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:362)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:396)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:388)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:293)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:427)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:324)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:337)
	at androidx.compose.ui.input.pointer.Node.dispatchToPointerInputFilter(HitPathTracker.kt:361)
	at androidx.compose.ui.input.pointer.Node.dispatchChanges(HitPathTracker.kt:309)
	at androidx.compose.ui.input.pointer.Node.dispatchChanges(HitPathTracker.kt:305)
	at androidx.compose.ui.input.pointer.Node.dispatchChanges(HitPathTracker.kt:305)
	at androidx.compose.ui.input.pointer.Node.dispatchChanges(HitPathTracker.kt:305)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchChanges(HitPathTracker.kt:180)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:112)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-gBdvCQM(PointerInputEventProcessor.kt:80)
	at androidx.compose.ui.platform.DesktopOwner.processPointerInput$ui(DesktopOwner.desktop.kt:322)
	at androidx.compose.ui.platform.DesktopOwners.onMousePressed(DesktopOwners.desktop.kt:137)
	at androidx.compose.desktop.ComposeLayer$initCanvas$2$mousePressed$1.invoke(ComposeLayer.desktop.kt:150)
	at androidx.compose.desktop.ComposeLayer$initCanvas$2$mousePressed$1.invoke(ComposeLayer.desktop.kt:149)
	at androidx.compose.desktop.AWTDebounceEventQueue$job$1.invokeSuspend(AWTDebounceEventQueue.desktop.kt:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:316)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Disconnected from the target VM, address: '127.0.0.1:64570', transport: 'socket'

Process finished with exit code 1
```
Version 0.4.0-build183

**Comment by sonder-joker** [comment]
Use stable version run well

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6436">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
