### ISSUE TITLE
"Impossible" NullPointerExcepton regression in build 188

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/compose-jb#639]
This is happening in the main demo of [Aurora project](https://github.com/kirill-grouchnikov/aurora). It's quite large for a reproducer, but it might take some time for me to make it into a standalone thing. First, the crash itself:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.pushingpixels.aurora.component.AuroraRadioButtonKt.AuroraRadioButton(AuroraRadioButton.kt:188)
	at org.pushingpixels.aurora.component.AuroraRadioButtonKt$AuroraRadioButton$7.invoke(AuroraRadioButton.kt)
	at org.pushingpixels.aurora.component.AuroraRadioButtonKt$AuroraRadioButton$7.invoke(AuroraRadioButton.kt)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:96)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2116)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2374)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2516)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:2487)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:546)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:733)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:102)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:443)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:415)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:63)
	at androidx.compose.ui.platform.DesktopOwners.onFrame(DesktopOwners.desktop.kt:120)
	at androidx.compose.desktop.ComposeLayer$1.onRender(ComposeLayer.desktop.kt:122)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.kt:222)
	at org.jetbrains.skiko.redrawer.MetalRedrawer.update(MetalRedrawer.kt:48)
	at org.jetbrains.skiko.redrawer.MetalRedrawer.access$update(MetalRedrawer.kt:14)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invokeSuspend(MetalRedrawer.kt:24)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invoke(MetalRedrawer.kt)
	at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Line 188 is https://github.com/kirill-grouchnikov/aurora/blob/icicle/component/src/desktopMain/kotlin/org/pushingpixels/aurora/component/AuroraRadioButton.kt#L188 and if I print `presentationModel` right before it in the scenario below, it is indeed `null`. Except that it can't be null from the signature of the method in https://github.com/kirill-grouchnikov/aurora/blob/icicle/component/src/desktopMain/kotlin/org/pushingpixels/aurora/component/AuroraRadioButton.kt#L72 and the overall setup of the demo and composables.

Here is the reproducer:
1. Run the `AuroraDemo` demo
2. Click on the "sample check" checkbox to uncheck it
3. Move the mouse over the "sample radio" - it crashes

The same happens if you click "sample radio" to uncheck it, and then move the mouse over "sample check" checkbox. There's a similar crash in `AuroraCheckBox`.

This is a regression from build 185 to build 188, and also what looks to be an impossible scenario to get to given the signature of the matching composables, and no path in the code that I know of that sets those arguments to null.

**Comment by igordmn** [comment]
Issue and reproducer in Google tracker:

https://issuetracker.google.com/issues/188015757

**Comment by kirill-grouchnikov** [comment]
The issue in core Compose has been merged a few days ago. Looks like build-210 picked up that fix, as I'm no longer seeing this crash.

**Comment by igordmn** [comment]
Should be fixed in 0.4.0-build211, 0.4.0-build210 was built before this fix (from https://github.com/JetBrains/androidx/tree/jb-main) 🤔.

**Comment by kirill-grouchnikov** [comment]
Can be closed now?

**Comment by igordmn** [comment]
Yes, thanks.
