### ISSUE TITLE
compose desktop `run` task throws NullPointerException with gradle 6.6 or 6.7

### ISSUE THREAD

**Issue by jbluntz** [JetBrains/compose-jb#66]
**Steps to recreate**

1. Open either `multiplatform-template` or `desktop-template` projects
2. Update `gradle/wrapper/gradle-wrapper.properties`  to gradle 6.6, 6.6.1, or 6.7
3. Run `:desktop:run`

**Error Log:**
```
A problem occurred configuring project ':desktop'.
> Could not create task ':desktop:run'.
   > at index 0
```

```
* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':desktop'.
Caused by: org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreationException: Could not create task ':desktop:run'.
Caused by: java.lang.NullPointerException: at index 0
	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:225)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:215)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:209)
	at com.google.common.collect.ImmutableList.construct(ImmutableList.java:326)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:243)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$UnresolvedItemsCollector.plus(DefaultConfigurableFileCollection.java:409)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.from(DefaultConfigurableFileCollection.java:191)
	at org.jetbrains.compose.desktop.application.internal.ConfigureApplicationKt$configureRunTask$1.invoke(configureApplication.kt:159)
	at org.jetbrains.compose.desktop.application.internal.ConfigureApplicationKt$configureRunTask$1.invoke(configureApplication.kt)
	at org.jetbrains.compose.desktop.application.internal.ConfigureApplicationKt$composeTask$$inlined$apply$lambda$3.execute(configureApplication.kt:186)
	at org.jetbrains.compose.desktop.application.internal.ConfigureApplicationKt$composeTask$$inlined$apply$lambda$3.execute(configureApplication.kt)
```

**Comment by eygraber** [comment]
I don't fully understand what `app.mainJar` is supposed to be doing so I wouldn't know what the best way to fix this is, but looking through the source, [this seems to be the issue](https://github.com/JetBrains/compose-jb/blob/6ea3fca296f34cb40c4624bb5466e34ae5f6046c/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/internal/configureApplication.kt#L158).

[Starting from Gradle 6.0 `DefaultConfigurableFileCollection.from` will throw a NPE if there is a null element in the collection](https://github.com/gradle/gradle/commit/a4ae07fff31bd5527a5f311a7cc8585c9ad6f8ed#diff-aeeff5fd77deed324b428cb9dda329a395d0a9a2aa44dda84510d1727e605fcbR381) (`ImmutableList.copyOf` makes sure that elements aren't null).

`app.mainJar` is null, and is added to the collection. The next line calls `from` again (with `app._fromFiles`), and therefore throws an NPE, failing the build.

A possible fix is to replace `cp.from(app.mainJar.orNull)` with `app.mainJar.orNull.let(cp::from)`, but again, I'm not fully sure what that's supposed to be doing, so I'm not sure if that would break something else.

**Comment by ScottPierce** [comment]
Seeing this same problem

**Comment by AlexeyTsvetkov** [comment]
Fixed in https://github.com/JetBrains/compose-jb/commit/56da868a05f0014382d34aecf282db867ee67f1d

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6527">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
