### ISSUE TITLE
Compose Web: Can't use Kotlinx.Serialization 1.5.10 / 1.2.1 with Kotlin 1.5.10: IllegalStateException: IdSignature clash

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-jb#738]
In a project with the following build file:

```

plugins {
    kotlin("multiplatform") version "1.5.10"
    kotlin("plugin.serialization") version "1.5.10"
    id("org.jetbrains.compose") version "0.0.0-web-dev-14"
}

repositories {
    mavenCentral()
    maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
}

kotlin {
    js(IR) {
        browser()
        binaries.executable()
    }
    sourceSets {
        val jsMain by getting {
            dependencies {
                implementation(compose.web.core)
                implementation(compose.runtime)
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.1")
            }
        }
    }
}

```

...any attempt to serialize by adding the `@Serializable` annotation an object results in the following error messages:

```
java.lang.IllegalStateException: IdSignature clash: public /TodoItem.$serializer|null[0]; Existed declaration CLASS OBJECT name:$serializer modality:FINAL visibility:public superTypes:[kotlinx.serialization.internal.GeneratedSerializer<<root>.TodoItem>] clashed with new CLASS OBJECT name:$serializer modality:FINAL visibility:public superTypes:[kotlinx.serialization.internal.GeneratedSerializer<<root>.TodoItem>]
	at org.jetbrains.kotlin.ir.backend.js.lower.serialization.ir.JsUniqIdClashTracker.commit(JsDeclarationTable.kt:35)
	at org.jetbrains.kotlin.backend.common.serialization.GlobalDeclarationTable.computeSignatureByDeclaration(DeclarationTable.kt:46)
	at org.jetbrains.kotlin.backend.common.serialization.DeclarationTable.computeSignatureByDeclaration(DeclarationTable.kt:74)
	at org.jetbrains.kotlin.backend.common.serialization.DeclarationTable.signatureByDeclaration(DeclarationTable.kt:83)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.protoIdSignature(IrFileSerializer.kt:237)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrSymbol(IrFileSerializer.kt:291)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrDeclarationBase(IrFileSerializer.kt:1011)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrClass(IrFileSerializer.kt:1140)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeDeclaration(IrFileSerializer.kt:1214)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrClass(IrFileSerializer.kt:1144)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeDeclaration(IrFileSerializer.kt:1214)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrFile(IrFileSerializer.kt:1302)
	at org.jetbrains.kotlin.backend.common.serialization.IrModuleSerializer.serializeIrFile(IrModuleSerializer.kt:28)
	at org.jetbrains.kotlin.backend.common.serialization.IrModuleSerializer.serializedIrModule(IrModuleSerializer.kt:35)
	at org.jetbrains.kotlin.ir.backend.js.KlibKt.serializeModuleIntoKlib(klib.kt:490)
	at org.jetbrains.kotlin.ir.backend.js.KlibKt.generateKLib(klib.kt:183)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:197)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:181)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:74)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1575)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)



```

It seems to be a problem with Kotlin/JS and the Noarg plugin, but also affects Compose Web. https://youtrack.jetbrains.com/issue/KT-46793

Upd 22.07.21:
same problem reported later here - https://github.com/JetBrains/compose-jb/issues/885

**Comment by eymar** [comment]
simple repro project: https://github.com/eymar/reproducing-issues/tree/repr-compose-web-with-serialization

**Comment by darvld** [comment]
Is there a way to disable the warning displayed by the plugin? I'm using Compose only for desktop and as far as I can see this is a Web issue.

**Comment by OliverO2** [comment]
@eymar, to provide some answers to questions in https://github.com/JetBrains/compose-jb/issues/885#issuecomment-879794052:

> The advice here is to use the workaround that you've found by yourself (seperate all Serialization in a different module):
>
> moduleA (uses kotlinx.serialization)
> moduleB (uses compose + depends on moduleA)

For others to reference, here is a link to a working example, which you kindly provided: https://github.com/eymar/reproducing-issues/tree/repr-compose-web-with-serialization

> Some questions to help us analyse the use cases:
>
> What's the biggest downside of the workaround in your opinion?

Being forced to structure the project according to implementation details instead of actual re-use and domain cohesiveness: When deciding where to place a specific `commonMain` class, I'd always have to factor in whether it is serializable.

Other considerations:

* Authoring a multi-project Gradle configuration requires more Gradle knowledge. A simple wizard-created single-project configuration no longer works. Onboarding is more difficult.
* Maintaining a multi-project Gradle configuration requires more developer time and attention than a single-project one.
 
> It seems that this approach also helps separating the app layers.

In specific cases, separating serializable classes from the rest will be fine (e.g. as part of an API re-used across multiple applications). Otherwise, a multi-project configuration adds another layer of complexity on top of multiplatform's source sets.

> Is there an inevitable need to use both plugins in the same modules for your? What's your use case?

Currently, I am not aware of such a use case. The workaround can be applied as the above example shows.

Hope this helps.

**Comment by ylemoigne** [comment]
To answer question asked in #885

What's the biggest downside of the workaround in your opinion?
It seems that this approach also helps separating the app layers. Is there an inevitable need to use both plugins in the same modules for your? What's your use case?

I wouldn't say I have an `inevitable need`.

The usecase I'm working on is a fullstack framework. I've separated the part in 2 subprojects and it works.
Now, I'm working on visibility of my framework API, and I would like to mark some API as `internal`.
Unfortunatly, some method will stay public because the framework is splitted in separate project.

So this is the downside.

(I should be able to provide a link to my project repository soon)

**Comment by brianguertin** [comment]
I'm no longer getting this error with compose-jb 1.0.0-alpha4-build331 and Kotlin 1.5.30

**Comment by akurasov** [comment]
@brianguertin what error you didn't get? 
It is still prohibited to use Compose and Serialization in one module.

**Comment by ylemoigne** [comment]
@akurasov I tried this morning, the  `java.lang.IllegalStateException: IdSignature clash` does not happen anymore.

The warning about using both plugin is still here.

**Comment by akurasov** [comment]
Then I believe this issue can be closed. We do not support such scenario(compose web+serialization) at the moment anyway.

**Comment by edrd-f** [comment]
Should https://github.com/JetBrains/compose-jb/pull/900 be reverted now that this is closed?

**Comment by akurasov** [comment]
@edrd-f why do you think so?

**Comment by OliverO2** [comment]
With Kotlin 1.6.10, Compose 1.1.1, kotlinx.serialization=1.3.2, the following error still appears for `compileProductionExecutableKotlinJs`, but only if `gradle.properties` contains `kotlin.incremental.js.ir=true`:

``` 
e: java.lang.IllegalStateException: IdSignature clash: androidx.compose.runtime.snapshots/<get-sync>$accessor$qcwnlt|-5961401990873474593[0]; Existed declaration FUN DEFAULT_PROPERTY_ACCESSOR name:<get-sync>$accessor$qcwnlt visibility:internal modality:FINAL <> () returnType:kotlin.Any clashed with new FUN DEFAULT_PROPERTY_ACCESSOR name:<get-sync>$accessor$qcwnlt visibility:internal modality:FINAL <> () returnType:kotlin.Any
	at org.jetbrains.kotlin.ir.backend.js.lower.serialization.ir.JsUniqIdClashTracker.commit(JsDeclarationTable.kt:29)
	at org.jetbrains.kotlin.backend.common.serialization.GlobalDeclarationTable.computeSignatureByDeclaration(DeclarationTable.kt:48)
	at org.jetbrains.kotlin.backend.common.serialization.DeclarationTable.computeSignatureByDeclaration(DeclarationTable.kt:83)
	at org.jetbrains.kotlin.backend.common.serialization.DeclarationTable.signatureByDeclaration(DeclarationTable.kt:92)
	at org.jetbrains.kotlin.ir.backend.js.ic.IcSerializer$IcDeclarationTable.signatureByDeclaration(IcSerializer.kt:145)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.protoIdSignature(IrFileSerializer.kt:306)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrSymbol(IrFileSerializer.kt:369)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeReturn(IrFileSerializer.kt:806)
```

The issue disappears when incremental JS IR compilation in `gradle.properties` is commented out:
```
#kotlin.incremental.js.ir=true
```

In the latter case, Compose and kotlinx.serialization work, even if sharing a module. Did anything change in the mean time? Is the above still the same underlying problem?

**Comment by wakaztahir** [comment]
Kotlin1.8.0 , Jetpack Compose 1.3.0 , Compose Compiler 1.4.0

I am getting this error , using Jetpack Compose Multiplatform , The only difference is that I am getting this exception for an Enum class which hasn't been marked as Serializable , though there are other Serializable classes in the module

commonMain
```
expect enum class SketchableImageFormat {
    PNG,
    JPEG;

    fun isSupported(): Boolean
}
```

jsMain
```
actual enum class SketchableImageFormat {
    PNG, JPEG;

    actual fun isSupported(): Boolean = false
}
```

exception
```
java.lang.IllegalStateException: IdSignature clash: com.wakaztahir.sketchable.importexport.export/SketchableImageFormat|null[0]; Existed declaration CLASS ENUM_CLASS name:SketchableImageFormat modality:FINAL visibility:public superTypes:[kotlin.Enum<com.wakaztahir.sketchable.importexport.export.SketchableImageFormat>] clashed with new CLASS ENUM_CLASS name:SketchableImageFormat modality:FINAL visibility:public superTypes:[kotlin.Enum<com.wakaztahir.sketchable.importexport.export.SketchableImageFormat>]
	at org.jetbrains.kotlin.ir.backend.js.lower.serialization.ir.JsUniqIdClashTracker.commit(JsDeclarationTable.kt:27)
	at org.jetbrains.kotlin.backend.common.serialization.GlobalDeclarationTable.computeSignatureByDeclaration(DeclarationTable.kt:48)
	at org.jetbrains.kotlin.backend.common.serialization.DeclarationTable.computeSignatureByDeclaration(DeclarationTable.kt:83)
	at org.jetbrains.kotlin.backend.common.serialization.DeclarationTable.signatureByDeclaration(DeclarationTable.kt:92)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.protoIdSignature(IrFileSerializer.kt:290)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrSymbol(IrFileSerializer.kt:353)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeSimpleType(IrFileSerializer.kt:390)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrTypeData(IrFileSerializer.kt:427)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrType(IrFileSerializer.kt:494)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeExpression(IrFileSerializer.kt:1006)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrExpressionBody(IrFileSerializer.kt:173)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrValueParameter(IrFileSerializer.kt:1117)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrFunctionBase(IrFileSerializer.kt:1148)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrFunction(IrFileSerializer.kt:1165)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeDeclaration(IrFileSerializer.kt:1322)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrClass(IrFileSerializer.kt:1245)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeDeclaration(IrFileSerializer.kt:1330)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrFileImpl(IrFileSerializer.kt:1431)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.access$serializeIrFileImpl(IrFileSerializer.kt:115)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer$serializeIrFile$1.invoke(IrFileSerializer.kt:1411)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer$serializeIrFile$1.invoke(IrFileSerializer.kt:1410)
	at org.jetbrains.kotlin.backend.common.serialization.signature.PublicIdSignatureComputer.inFile(IdSignatureSerializer.kt:45)
	at org.jetbrains.kotlin.backend.common.serialization.signature.IdSignatureSerializer.inFile(IdSignatureSerializer.kt:229)
	at org.jetbrains.kotlin.backend.common.serialization.DeclarationTable.inFile(DeclarationTable.kt:62)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrFile(IrFileSerializer.kt:1410)
	at org.jetbrains.kotlin.backend.common.serialization.IrModuleSerializer.serializeIrFile(IrModuleSerializer.kt:28)
	at org.jetbrains.kotlin.backend.common.serialization.IrModuleSerializer.serializedIrModule(IrModuleSerializer.kt:35)
	at org.jetbrains.kotlin.ir.backend.js.KlibKt.serializeModuleIntoKlib(klib.kt:749)
	at org.jetbrains.kotlin.ir.backend.js.KlibKt.generateKLib(klib.kt:237)
	at org.jetbrains.kotlin.ir.backend.js.KlibKt.generateKLib$default(klib.kt:205)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:353)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:183)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:72)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:101)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:213)
	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:84)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:424)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:360)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:242)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile$default(IncrementalCompilerRunner.kt:80)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execJsIncrementalCompiler(CompileServiceImpl.kt:566)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execJsIncrementalCompiler(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1837)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5381">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
