### ISSUE TITLE
CEF initialization failed!

### ISSUE THREAD

**Issue by ragunathjawahar** [JetBrains/compose-jb#788]
### Command
`gradlew run`

### OS
macOS Big Sur Version 11.4

### Java
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

### Trace
```
> Task :run
dlopen ~/compose-jb/cef/third_party/java-cef/../Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework: dlopen(~/compose-jb/cef/third_party/java-cef/../Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework, 261): image not found
Exception in thread "AWT-EventQueue-0" java.lang.Error: CEF initialization failed!
        at org.jetbrains.compose.desktop.browser.CefBrowserWrapper.<init>(CefBrowserWrapper.kt:26)
        at org.jetbrains.compose.desktop.browser.BrowserView.load(BrowserView.kt:108)
        at org.jetbrains.compose.desktop.AppKt$main$1.invoke(App.kt:45)
        at org.jetbrains.compose.desktop.AppKt$main$1.invoke(App.kt)
        at androidx.compose.desktop.WindowEvents.invokeOnFocusGet$ui(AppFrame.kt:215)
        at androidx.compose.desktop.AppWindow$2$2.windowGainedFocus(AppWindow.kt:125)
        at java.desktop/java.awt.Window.processWindowFocusEvent(Window.java:2125)
        at java.desktop/java.awt.Window.processEvent(Window.java:2041)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
        at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1059)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:515)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4892)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

![cef-crash](https://user-images.githubusercontent.com/1141970/122344215-276bfd80-cf64-11eb-83fd-f7714a2aa632.png)

**Comment by akurasov** [comment]
Could you share a reproducer code, please?

**Comment by akurasov** [comment]
CEF is not officially supported at the moment. Closing.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6296">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
