### ISSUE TITLE
NPE race condition (when drawing icons?)

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-jb#804]
Getting a NPE race condition, I suspect related to drawing Icons.  Tested with the latest build as of today (build226) on both Linux and Mac.  Let me know if this is not a desktop issue, but the symptoms are suspiciously similar to https://github.com/JetBrains/compose-jb/issues/486
```
import androidx.compose.desktop.Window
import androidx.compose.material.*
import androidx.compose.material.icons.filled.Favorite
import androidx.compose.material.icons.Icons
import androidx.compose.runtime.*
import androidx.compose.ui.platform.TestComposeWindow

fun main() {
        for(i in 1..10000) {
                TestComposeWindow(800, 800).setContent {
                        TabRow(selectedTabIndex = 0) {
                                Tab(
                                        icon = { Icon(Icons.Filled.Favorite, null) },
                                        selected = true,
                                        onClick = {}
                                )
                        }
                        TabRow(selectedTabIndex = 0) {
                                Tab(
                                        icon = { Icon(Icons.Filled.Favorite, null) },
                                        selected = true,
                                        onClick = {}
                                )
                        }
                        TabRow(selectedTabIndex = 0) {
                                Tab(
                                        icon = { Icon(Icons.Filled.Favorite, null) },
                                        selected = true,
                                        onClick = {}
                                )
                        }
                }
        }
}
```

Crashes with the following trace:
```
> Task :run
Exception in thread "main" java.lang.NullPointerException
        at androidx.compose.runtime.collection.IdentityScopeMap.find(IdentityScopeMap.kt:319)
        at androidx.compose.runtime.collection.IdentityScopeMap.getOrCreateIdentitySet(IdentityScopeMap.kt:102)
        at androidx.compose.runtime.collection.IdentityScopeMap.add(IdentityScopeMap.kt:76)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver$ApplyMap.addValue(SnapshotStateObserver.kt:262)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver$readObserver$1.invoke(SnapshotStateObserver.kt:56)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver$readObserver$1.invoke(SnapshotStateObserver.kt:54)
        at androidx.compose.runtime.snapshots.SnapshotKt.readable(Snapshot.kt:1525)
        at androidx.compose.runtime.snapshots.SnapshotKt.readable(Snapshot.kt:1517)
        at androidx.compose.runtime.SnapshotMutableStateImpl.getValue(SnapshotState.kt:143)
        at androidx.compose.ui.graphics.vector.VectorPainter.isDirty(VectorPainter.kt:356)
        at androidx.compose.ui.graphics.vector.VectorPainter.onDraw(VectorPainter.kt:201)
        at androidx.compose.ui.graphics.painter.Painter.draw-x_KDEd0(Painter.kt:212)
        at androidx.compose.ui.draw.PainterModifier.draw(PainterModifier.kt:289)
        at androidx.compose.ui.node.ModifiedDrawNode.performDraw(ModifiedDrawNode.kt:102)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:98)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:814)
        at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:105)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:68)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:814)
        at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:105)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:814)
        at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:105)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:98)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:68)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:68)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:42)
        at androidx.compose.material.ripple.CommonRippleIndicationInstance.drawIndication(CommonRipple.kt:70)
        at androidx.compose.foundation.IndicationModifier.draw(Indication.kt:175)
        at androidx.compose.ui.node.ModifiedDrawNode.performDraw(ModifiedDrawNode.kt:102)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:68)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:814)
        at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:105)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:98)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:814)
        at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:105)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:68)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:68)
        at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:255)
        at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:254)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:124)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:75)
        at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:254)
        at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:54)
        at androidx.compose.ui.platform.SkijaLayer.performDrawLayer(SkijaLayer.desktop.kt:246)
        at androidx.compose.ui.platform.SkijaLayer.drawLayer(SkijaLayer.desktop.kt:212)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:239)
        at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:98)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:42)
        at androidx.compose.foundation.Background.draw(Background.kt:107)
        at androidx.compose.ui.node.ModifiedDrawNode.performDraw(ModifiedDrawNode.kt:102)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:68)
        at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:255)
        at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:254)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1788)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:119)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:75)
        at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:254)
        at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:54)
        at androidx.compose.ui.platform.SkijaLayer.performDrawLayer(SkijaLayer.desktop.kt:246)
        at androidx.compose.ui.platform.SkijaLayer.drawLayer(SkijaLayer.desktop.kt:212)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:239)
        at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:814)
        at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:105)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:68)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:68)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:68)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:68)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:68)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:244)
        at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:814)
        at androidx.compose.ui.platform.DesktopOwner.draw(DesktopOwner.desktop.kt:332)
        at androidx.compose.ui.platform.TestComposeWindow.setContent(TestComposeWindow.desktop.kt:115)
        at MainKt.main(main.kt:10)
        at MainKt.main(main.kt)
```

cc @igordmn @olonho

**Comment by olonho** [comment]
Does it NPE on Android as well?

**Comment by igordmn** [comment]
Don't know yet, will try with `createComposeRule` where we also have two threads

**Comment by igordmn** [comment]
The issue is probably in [SnapshotStateObserver](https://issuetracker.google.com/issues/192677711).

**Comment by akurasov** [comment]
Looks like after SnapshotStateObserver was fixed, the issue is not reproducible anymore. At least on my Mac both reproducers work fine. @jimgoog do you have this issue with the latest (or 245) build?

**Comment by igordmn** [comment]
I checked this reproducer and it is no longer throws exception on `0.5.0-build262`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6353">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
