### ISSUE TITLE
Material AlertDialog is not implemented.

### ISSUE THREAD

**Issue by sureshg** [JetBrains/compose-jb#81]
Using the following code throws the `NotImplementedError`. 

```kotlin
AlertDialog(
            onDismissRequest = {
                showDialog.value = false
            },
            confirmButton = {
                Button(onClick = {
                    showDialog.value = false
                }) {
                    Text(text = "OK")
                }
            },
            dismissButton = {
                Button(onClick = {
                    showDialog.value = false
                }) {
                    Text(text = "Cancel")
                }
            },
            title = {
                Text(text = "Alert Dialog")
            },
            text = {
                Text(text = "Compose Desktop")
            },
            shape = RoundedCornerShape(5.dp),
            backgroundColor = MaterialTheme.colors.onPrimary,
        )
```

```
kotlin.NotImplementedError: An operation is not implemented: not implemented
	at androidx.compose.ui.window.DesktopDialogKt.ActualDialog(DesktopDialog.kt:28)
	at androidx.compose.ui.window.DialogKt.Dialog(Dialog.kt:42)
	at androidx.compose.material.AlertDialogKt.AlertDialog-ubiPcs4(AlertDialog.kt:144)
	at androidx.compose.material.AlertDialogKt.AlertDialog-E7Yi3bI(AlertDialog.kt:81)
```

**Comment by igordmn** [comment]
Probably because of this:
https://github.com/JetBrains/compose-jb/issues/19

As a temporary measure you can copy-paste AlertDialog and use Dialog from desktopMain
(for use it in commonMain you should define your own expect/actual function)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6520">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
