### ISSUE TITLE
 kotlinx.serialization with jetpack compose web 

### ISSUE THREAD

**Issue by JimeFuture** [JetBrains/compose-jb#885]
Hello together,

Issue related to https://github.com/Kotlin/kotlinx.serialization/issues/1454

Compiler error when using kotlinx.serialization @Serializable with jetpack compose for web.
Issue seems to be there since release. Is there any plan to fix this issue in some of the next releases? Right now the only workaround i found is to seperate all Serialization in a different module what pretty much sucks. As we only use the dom API of the jepack compose for web which is for our usecases stable and extended enough the only thing prevending us from starting some small projects with compose for web is actually this issue. If it could not be fixed any soon, is there a better workaround than to seperate it a different module?

We would be thankfull for any advise

 `java.lang.IllegalStateException: IdSignature clash: public database.branch/BranchData.$serializer|null[0]; Existed declaration CLASS OBJECT name:$serializer modality:FINAL visibility:public superTypes:[kotlinx.serialization.internal.GeneratedSerializer<database.branch.BranchData>] clashed with new CLASS OBJECT name:$serializer modality:FINAL visibility:public superTypes:[kotlinx.serialization.internal.GeneratedSerializer<database.branch.BranchData>]
	at org.jetbrains.kotlin.ir.backend.js.lower.serialization.ir.JsUniqIdClashTracker.commit(JsDeclarationTable.kt:35)
	at org.jetbrains.kotlin.backend.common.serialization.GlobalDeclarationTable.computeSignatureByDeclaration(DeclarationTable.kt:46)
	at org.jetbrains.kotlin.backend.common.serialization.DeclarationTable.computeSignatureByDeclaration(DeclarationTable.kt:74)
	at org.jetbrains.kotlin.backend.common.serialization.DeclarationTable.signatureByDeclaration(DeclarationTable.kt:83)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.protoIdSignature(IrFileSerializer.kt:237)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrSymbol(IrFileSerializer.kt:291)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrDeclarationBase(IrFileSerializer.kt:1011)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrClass(IrFileSerializer.kt:1140)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeDeclaration(IrFileSerializer.kt:1214)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrClass(IrFileSerializer.kt:1144)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeDeclaration(IrFileSerializer.kt:1214)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrFile(IrFileSerializer.kt:1302)
	at org.jetbrains.kotlin.backend.common.serialization.IrModuleSerializer.serializeIrFile(IrModuleSerializer.kt:28)
	at org.jetbrains.kotlin.backend.common.serialization.IrModuleSerializer.serializedIrModule(IrModuleSerializer.kt:35)
	at org.jetbrains.kotlin.ir.backend.js.KlibKt.serializeModuleIntoKlib(klib.kt:490)
	at org.jetbrains.kotlin.ir.backend.js.KlibKt.generateKLib(klib.kt:183)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:197)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:181)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:74)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1575)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

**Comment by eymar** [comment]
Hi @JimeFuture 

it's true, the issue appears since the very beginning. It was also reported earlier - [here](https://github.com/JetBrains/compose-jb/issues/738) 

There's an ongoing discussion where different teams involved. There's no acceptable solution at the moment, that would help solve this without workaround. 

The advice here is to use the workaround that you've found by yourself (seperate all Serialization in a different module):

moduleA (uses kotlinx.serialization)  
moduleB (uses compose + depends on moduleA)


Some questions to help us analyse the use cases:

What's the biggest downside of the workaround in your opinion? 
It seems that this approach also helps separating the app layers. Is there an inevitable need to use both plugins in the same modules for your? What's your use case?

thanks!

**Comment by eymar** [comment]
I close this issue, since the same problem was reported earlier here: https://github.com/JetBrains/compose-jb/issues/738 
I'll add a link to this issue there.
Please add any other comments or details there if needed - https://github.com/JetBrains/compose-jb/issues/738

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5354">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
