### ISSUE TITLE
Potential Bug in LazyList with TextField and VerticalScrollbar

### ISSUE THREAD

**Issue by christoph-grimm** [JetBrains/compose-jb#937]
compose desktop version 0.5.0-build 262: 

There is an exception from AWT when a not-visible item is in Focus, then scrolled out of the Screen (not displayed anymore), and then an input is made. 

Code to reproduce the issue (move cursor to some high index, enter a letter, move back to start such that edited field is no longer visible, enter an additional letter): 

Window {
        val lines =  mutableStateListOf(TextFieldValue(" "))
        val scrollState = rememberLazyListState()
        for (l in 0..100) { lines.add(TextFieldValue("$l")) }
        Row {
            LazyColumn(state = scrollState) {
                items(100) { index -> TextField(lines[index], { lines[index] = it }) }
            }
            VerticalScrollbar(Modifier, scrollState)
        }
    }

On a Mac/M1 at least this leads to the following exception: 

Exception in thread "AWT-EventQueue-0 @coroutine#1" java.lang.IllegalStateException: KeyEvent can't be processed because this key input node is not active.
	at androidx.compose.ui.input.key.KeyInputModifier.processKeyInput-ZmokQxo(KeyInputModifier.kt:79)
	at androidx.compose.ui.platform.DesktopOwner.sendKeyEvent-ZmokQxo(DesktopOwner.desktop.kt:212)
	at androidx.compose.ui.platform.DesktopOwners.consumeKeyEvent(DesktopOwners.desktop.kt:212)
	at androidx.compose.ui.platform.DesktopOwners.onKeyPressed(DesktopOwners.desktop.kt:215)
	at androidx.compose.desktop.ComposeLayer$initCanvas$5$keyPressed$1.invoke(ComposeLayer.desktop.kt:224)
	at androidx.compose.desktop.ComposeLayer$initCanvas$5$keyPressed$1.invoke(ComposeLayer.desktop.kt:223)
	at androidx.compose.desktop.AWTDebounceEventQueue$job$1.invokeSuspend(AWTDebounceEventQueue.desktop.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by akurasov** [comment]
On Android without scrollbar everything is fine (you can enter to a field that is beyond screenborder).

**Comment by christoph-grimm** [comment]
Not on MacOS with scrollbar. 

I wonder if there is a bug in the focus management in combination with Lazy environments.
Following bug cascade could be possible: 

- Item has focus 
- LazyList updates after scrolling with scrollbar
- Non-existing (or not-displayed) item still in focus 
- Input event sent and leads to exception.

**Comment by christoph-grimm** [comment]
**Checked:** 
- Bug requires **scrollbar** use to be reproduced: 
-  (e.g. scroll to item 80, edit, leave it in focus, scroll back to 1 & 80 out of screen, press key) 
- No scrollbar - no bug. 

I wonder if on Android (and other platforms) WITH scrollbar the bug is there - looks like issue in management of focus when scrolling.

**Comment by akurasov** [comment]
There are no scrollbars on Android (. And without scrollbars it works fine. We will investigate it further.

**Comment by igordmn** [comment]
A reproducer without LazyList:

```
import androidx.compose.material.TextField
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.ReusableContent
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.window.singleWindowApplication
import kotlinx.coroutines.delay

@OptIn(ExperimentalComposeUiApi::class)
fun main() = singleWindowApplication {
    var num by remember { mutableStateOf(0) }

    ReusableContent(num) {
        DisposableEffect(Unit) {
            onDispose {
                println("dispose")
            }
        }
        TextField("", { }, singleLine = true)
    }

    LaunchedEffect(Unit) {
        while (true) {
            delay(2000)
            num++
        }
    }
}
```

1. Move the focus into TextField
2. Wait 2 sec
3. Try to press any key

**Comment by akurasov** [comment]
Fixed in 1.0.0-beta6-dev462

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6222">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
