### ISSUE TITLE
Can't use WindowDraggableArea in build 270

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/compose-jb#944]
The now-deprecated implementation of `WindowDraggableArea` throws this exception:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: CompositionLocal LocalAppWindow not provided
	at androidx.compose.desktop.AppWindow_desktopKt$LocalAppWindow$1.invoke(AppWindow.desktop.kt:50)
	at androidx.compose.desktop.AppWindow_desktopKt$LocalAppWindow$1.invoke(AppWindow.desktop.kt:49)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.compose.runtime.LazyValueHolder.getCurrent(ValueHolders.kt:29)
	at androidx.compose.runtime.LazyValueHolder.getValue(ValueHolders.kt:31)
	at androidx.compose.runtime.ComposerImpl.resolveCompositionLocal(Composer.kt:1780)
	at androidx.compose.runtime.ComposerImpl.consume(Composer.kt:1750)
	at androidx.compose.ui.window.WindowDraggableArea_jvmKt.WindowDraggableArea(WindowDraggableArea.jvm.kt:103)
```
The sources attached to the deprecated variant are:

```
@Deprecated(
    "Use another variant of WindowDraggableArea for the new Composable Window API (https://github" +
        ".com/JetBrains/compose-jb/tree/master/tutorials/Window_API_new)",
    replaceWith = ReplaceWith(
        "WindowDraggableArea(modifier, content)",
        "androidx.compose.foundation.window.WindowDraggableArea"
    )
)
```

But there is no documentation at https://github.com/JetBrains/compose-jb/tree/master/tutorials/Window_API_new and I can't find any examples on how to use this new `WindowScope.WindowDraggableArea`

**Comment by igordmn** [comment]
In the new API you can use WindowDraggableArea only inside `Window`/`singleWindowApplication` functions or in other function that accepts WindowScope as a receiver (`fun WindowScope.MyWindowContent`).

In 1.0.0-alpha1-rc1 we also added possibility to use it inside ComposeWindow.setContent.

We will add `WindowDraggableArea` to the documentation later.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6336">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
